lib/l10n/arb/app_en.arb
lib/services/user_service.dart
lib/ui/account/change_email_dialog.dart
lib/ui/account/delete_account_page.dart
lib/ui/account/email_entry_page.dart
lib/ui/account/password_entry_page.dart
lib/ui/account/password_reentry_page.dart
lib/ui/account/sessions_page.dart
lib/ui/code_widget.dart
lib/ui/home_page.dart
lib/ui/payment/child_subscription_widget.dart
lib/ui/payment/payment_web_page.dart
lib/ui/scanner_page.dart
lib/ui/settings/data_section_widget.dart
lib/ui/settings/debug_section_widget.dart
lib/ui/settings/made_with_love_widget.dart
lib/ui/settings/security_section_widget.dart
lib/ui/settings/support_section_widget.dart
lib/ui/settings/title_bar_widget.dart
lib/ui/two_factor_authentication_page.dart
lib/ui/two_factor_recovery_page.dart
lib/utils/dialog_util.dart
lib/utils/email_util.dart

Extract more localized strings. Still not complete, many more to extract, but some progress, especially some of the more common strings like "OK", "Cancel" will get translated this way.
Smoke tested by building and running the app.

Extract more strings into ARB files for localization

---

README.md

Readme: Fix link to issues

---

lib/l10n/arb/app_de.arb

Translate the app into German.

translate app to german

---

lib/l10n/arb/app_de.arb

Forgot to translate the `@@locale` string

fixed a forgotten string

---

README.md

Fix typo in read me

---

lib/app/view/app.dart
pubspec.yaml

- Restrict locale to en
- bump version to 1.0.25+25

Restrict to en locale

---

README.md
RELEASES.md

Document automated releases

---

pubspec.yaml

1.0.25 (26)

---

.gitmodules

- This is required for f-droid
- Also, as we have two projects on different flutter version, it make sense to add project specific dependency
> https://gitlab.com/fdroid/fdroiddata/-/blob/master/templates/build-flutter.yml

Add flutter as submodule

---

lib/models/code.dart
test/models/code_test.dart

Fix: Url decode the path value

---

lib/onboarding/view/setup_enter_secret_key_page.dart

Trim whitespaces from manual secret input

---

ios/Podfile.lock
lib/ui/home_page.dart
lib/utils/crypto_util.dart
lib/utils/device_info.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

- Fix typo in comparision
- Switch to maxOpsLimit for low end devices

Fix: Attempt to avoid crash on low-spec devices

---

lib/onboarding/view/setup_enter_secret_key_page.dart
pubspec.yaml

- Allow adding code without account info
- bump version to 1.0.27+27

Allow empty account name + bump version

---

lib/ui/home_page.dart
pubspec.yaml

Also bump version to 1.0.28+28

Improve UX for search

---

lib/app/view/app.dart
lib/locale.dart
lib/ui/tools/app_lock.dart
pubspec.yaml

Fix locale detection for AppLock

---

lib/ui/code_timer_progress.dart
lib/ui/code_widget.dart
pubspec.yaml

- Reduce UI rebuilds
- bump version to 1.0.30+30

Fix: Reduce UI rebuilds

---

lib/ui/home_page.dart

Log error while rendering code widgets

---

lib/app/view/app.dart
lib/locale.dart
lib/ui/account/change_email_dialog.dart
lib/ui/tools/app_lock.dart
pubspec.yaml

- Tested with and without lock screen

Fix change email

---

android/app/src/main/res/mipmap-anydpi-v26/launcher_icon.xml

Similar to https://github.com/ente-io/photos-app/pull/875
Issue:  #69

Android: Add support for theme icon

---

lib/ui/code_timer_progress.dart
lib/ui/linear_progress_widget.dart
pubspec.lock
pubspec.yaml

Related issue #70
https://user-images.githubusercontent.com/254676/224866871-e67abe08-9c63-48dd-89c0-db192d4f5d1b.mp4

Fix timer animation

---

.github/workflows/l18n-crowdin.yml
crowdin.yml

- Add crowdin config
- Add CI config for crowdin action

Integrate crowdin github action

---

lib/models/code.dart

- Fix typo
- Read issuer name from query params

Minor fixes

---

README.md

README: Add link to view codes on web

---

lib/models/code.dart
lib/onboarding/view/setup_enter_secret_key_page.dart

Fix bug in edit code

---

lib/store/code_store.dart

Sort by issuer,account

---

lib/ui/settings/social_section_widget.dart

Add links to Mastodon and Matrix

---

lib/utils/totp_util.dart

Fix: Handle empty spaces in qrCode secrets

---

migration-guides/authy.md

I've decided to write a guide on how to migrate from Authy to ente Authenticator, after Vishnu suggested that I should consider making one. The guide includes another guide on GitHub someone on ente Discord found, as well as the Python script I've made to convert that data for ente.

Authy to ente Auth migration guide

---

migration-guides/authy.md

I've added a recommendation to delete the unencrypted JSON and TXT files made during the migration process once the codes are imported. I forgot to add this earlier when I first wrote the guide, so I've added it now

Update migration guide

---

lib/store/code_store.dart

Make sort case-insensitive

---

lib/ui/code_widget.dart

Fixes #165
Removed extra padding towards right
Before:
After:

Fix alignment of codes list

---

lib/l10n/arb/app_en.arb
lib/models/protos/googleauth.pb.dart
lib/models/protos/googleauth.pbenum.dart
lib/models/protos/googleauth.pbjson.dart
lib/models/protos/googleauth.pbserver.dart
lib/ui/code_widget.dart
lib/ui/home_page.dart
lib/ui/scanner_gauth_page.dart
lib/ui/settings/data/import/google_auth_import.dart
lib/ui/settings/data/import/import_service.dart
lib/ui/settings/data/import/raivo_plain_text_import.dart
lib/ui/settings/data/import_page.dart
protos/googleauth.proto
pubspec.lock
pubspec.yaml

Google auth import

---

lib/l10n/arb/app_en.arb
lib/ui/settings/faq.dart
lib/ui/settings/support_section_widget.dart
pubspec.yaml

Add faq for auth

---

lib/l10n/arb/app_en.arb
lib/ui/code_widget.dart
lib/ui/home/home_empty_state.dart
lib/ui/settings/data/data_section_widget.dart
lib/ui/settings/data/import_page.dart
pubspec.yaml

- Updated copy
- Updated Empty Home page:

Update copies and hook for import & faq on Empty home page

---

lib/onboarding/view/setup_enter_secret_key_page.dart
lib/ui/code_widget.dart
lib/utils/totp_util.dart
test/models/code_test.dart

Fix bug in editing code with username in non-ascii format

---

.github/workflows/ci.yml
lib/services/update_service.dart
lib/ui/settings/data/import/encrypted_ente_import.dart
lib/ui/settings/data/import/google_auth_import.dart
lib/ui/settings/data/import/import_service.dart
lib/ui/settings/data/import/import_success.dart
lib/ui/settings/data/import/plain_text_import.dart
lib/ui/settings/data/import/raivo_plain_text_import.dart

* Fix update check for Github Channel
* Route to home page post import

Fix update check for Github Channel

---

lib/core/configuration.dart
lib/l10n/arb/app_en.arb
lib/onboarding/view/view_qr_page.dart
lib/services/user_service.dart
lib/ui/account/logout_dialog.dart
lib/ui/settings/data/export_widget.dart

Minor imprvements & fixes

---

lib/ui/account/request_pwd_verification_page.dart
lib/ui/settings/security_section_widget.dart
pubspec.yaml

- Only request for password if SRP setup is not done.
Tested locally
https://github.com/ente-io/auth/assets/254676/e19c6084-4230-4012-b493-b6f9d70736a2

Show disable email verification for all users

---

lib/l10n/arb/app_en.arb
lib/ui/settings/data/import/aegis_import.dart
lib/ui/settings/data/import/google_auth_import.dart
lib/ui/settings/data/import/import_service.dart
lib/ui/settings/data/import_page.dart
pubspec.yaml

Tested locally and verified that import for both encrypted and normal Aegis vault is working as expected.

Aegis import + bump version

---

lib/app/view/app_theme_extension.dart
lib/ente_theme_data.dart
lib/models/protos/googleauth.pb.dart
lib/onboarding/view/onboarding_page.dart
lib/services/user_service.dart
lib/ui/account/delete_account_page.dart
lib/ui/account/email_entry_page.dart
lib/ui/account/login_page.dart
lib/ui/account/ott_verification_page.dart
lib/ui/account/password_entry_page.dart
lib/ui/account/recovery_key_page.dart
lib/ui/account/recovery_page.dart
lib/ui/account/sessions_page.dart
lib/ui/code_widget.dart
lib/ui/common/bottom_shadow.dart
lib/ui/common/dynamic_fab.dart
lib/ui/common/report_bug.dart
lib/ui/home/coach_mark_widget.dart
lib/ui/home/home_empty_state.dart
lib/ui/home_page.dart
lib/ui/settings/app_update_dialog.dart
lib/ui/settings/app_version_widget.dart
lib/ui/settings/data/import/google_auth_import.dart
lib/ui/settings/data/import/plain_text_import.dart
lib/ui/settings/data/import_page.dart
lib/ui/settings/settings_section_title.dart
lib/ui/settings/settings_text_item.dart
lib/utils/date_time_util.dart
lib/utils/dialog_util.dart
lib/utils/email_util.dart

dart fix --apply

---

lib/store/code_store.dart
pubspec.yaml

Fix: Avoid duplicate imports during offline to offline switch

---

lib/events/icons_changed_event.dart
lib/services/preference_service.dart
lib/ui/code_widget.dart
lib/ui/home_page.dart
lib/ui/utils/icon_utils.dart
pubspec.lock
pubspec.yaml

Fixes #235.
Couldn't find a place within Settings to add the toggle to choose between small and large icons, so have added an "easter egg" – tapping the icon will be the toggle for now 🤓
https://github.com/ente-io/auth/assets/1161789/b6419666-9240-48cd-a67e-32eec48fba33

Large icons

---

lib/l10n/arb/app_en.arb
lib/ui/code_widget.dart

Copy next code to clipboard on tap

---

lib/ui/code_widget.dart

Split the code and add a space between to improve readability.

Format 6-digit codes

---

lib/l10n/arb/app_en.arb
lib/services/preference_service.dart
lib/ui/code_widget.dart
lib/ui/settings/general_section_widget.dart
pubspec.yaml

Support for masking codes

---

lib/l10n/arb/app_en.arb
lib/onboarding/view/setup_enter_secret_key_page.dart

(During entry edit) Require confirmation during Save if Secret Key is updated #194

Require confirmation during Save if Secret Key

---

lib/theme/colors.dart
lib/ui/code_widget.dart
lib/ui/utils/icon_utils.dart

Show placeholder icons when icon is missing

---

lib/ui/settings/support_section_widget.dart
lib/utils/email_util.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

Export logs prompts to save file

Fix log export for android

---

assets/custom-icons/_data/custom-icons.json
lib/ui/utils/icon_utils.dart

Fixes #343 by introducing `altNames`.

Support multiple names for the same service

---

lib/l10n/arb/app_en.arb
lib/services/local_authentication_service.dart
lib/ui/tools/lock_screen.dart
lib/utils/auth_util.dart
pubspec.lock
pubspec.yaml

Potential fix for iPad redundant auth request while switching apps. Will push a build and wait for community to verify the fix and any potential regression.

Lock screen fixes

---

ios/Podfile.lock
lib/ui/tools/lock_screen.dart
pubspec.yaml

Tested internally on Simulator and via Test flight.

Fix lockscreen issue on iPad + Bump version:2.0.20

---

lib/core/errors.dart
lib/l10n/arb/app_en.arb
lib/services/user_service.dart
lib/ui/account/login_pwd_verification_page.dart
lib/utils/crypto_util.dart
pubspec.yaml

Add fix for loginViaSRP

---

lib/l10n/arb/app_en.arb
lib/ui/settings/general_section_widget.dart

Show hint that double tapping on hidden code makes it visible

---

ios/Podfile.lock
lib/ui/home/home_empty_state.dart
pubspec.yaml

Fixes https://github.com/ente-io/auth/issues/399

Make screen scrollable

---

migration-guides/authy.md

Adds info on Bitwarden import support

Update Authy guide

---

assets/custom-icons/_data/custom-icons.json
assets/custom-icons/icons/Notesnook.svg

add the svg icon for notesnook

add icon for notesnook

---

lib/ui/settings/data/export_widget.dart
pubspec.yaml

Fixes https://github.com/ente-io/auth/issues/380
Also, increase wait time before deleting file to 30s to give user more time to select folder to save file on disk.

Export fixes

---

lib/onboarding/view/onboarding_page.dart
lib/ui/account/password_reentry_page.dart
lib/ui/common/dynamic_fab.dart
lib/ui/home/coach_mark_widget.dart
lib/ui/home/home_empty_state.dart
lib/ui/settings/data/import/import_service.dart

In a number of screens, there were issues with the UI when system font size is increased and even hindering basic usability in some cases. This includes, 
- Text getting clipped
- Buttons not visible/clickable
- Alignment issues
All obvious issues that I came across when testing has been fixed in this PR.

Make UI adapt to bigger font sizes

---

.gitmodules
desktop/README.md
web/README.md

Add README notices about the in-progress migration to this repository

---

.github/ISSUE_TEMPLATE/config.yml

Fixes https://github.com/ente-io/ente/issues/512

Fix links in CONTRIBUTING.md

---

server/cmd/museum/main.go
server/pkg/controller/collection.go
server/pkg/controller/collection_cast.go

[server] Remove custom metrics for collection diff

---

.github/workflows/auth-crowdin.yml
.github/workflows/mobile-crowdin.yml
.github/workflows/web-crowdin.yml

Pass the config option to try to get it to pick the right yml
Tested the web action

Fix crowdin actions

---

server/pkg/controller/file.go

[server] Remove entry from object_keys before marking del as completed

---

server/cmd/museum/main.go
server/ente/admin.go
server/pkg/api/admin.go
server/pkg/repo/queue.go

[server] Add API to re-queue item for processing

---

CONTRIBUTING.md

This came up in https://github.com/ente-io/ente/issues/678
Tested by opening the URL manually.

Ask for the project which requires new translations

---

cli/README.md

I will also update the old CLI repository's README to point to this repository.

[cli] Update the link to the CLI downloads in README

---

auth/lib/ui/settings/account_section_widget.dart
auth/lib/ui/settings/security_section_widget.dart
mobile/lib/ui/settings/account_section_widget.dart
mobile/lib/ui/settings/security_section_widget.dart

[mobile] Move recovery option under account section

---

auth/assets/custom-icons/_data/custom-icons.json

[auth] Fix custom-icons.json

---

CONTRIBUTING.md

Mention GitHub Discussion labels

---

web/apps/photos/src/components/PhotoFrame.tsx
web/apps/photos/src/components/PhotoList/index.tsx
web/apps/photos/src/pages/gallery/index.tsx
web/apps/photos/src/types/gallery/index.ts
web/apps/photos/src/utils/photoFrame/index.ts
web/packages/shared/time/format.ts

fixes https://github.com/ente-io/ente/issues/535
This PR will add checkbox to all select files on a day, this will also handle manual selection of files and select all checkbox on a day.

Added selectAll checkbox to select all files on a day

---

mobile/lib/core/configuration.dart
mobile/lib/l10n/intl_pt.arb
mobile/lib/ui/account/login_page.dart
mobile/lib/ui/account/password_entry_page.dart
mobile/lib/ui/account/password_reentry_page.dart
mobile/pubspec.yaml

[photos] Fixed arb + Bump version 0.8.65+585

---

auth/ios/Podfile.lock
auth/lib/ui/passkey_page.dart
auth/pubspec.lock
auth/pubspec.yaml
mobile/lib/ui/account/passkey_page.dart

[passkey] Fixed base64 decode + bump version

---

auth/analysis_options.yaml

[auth] Add linter rule for missing await

---

cli/README.md
cli/docs/release.md

- Improve CLI installation documentation, as requested in https://github.com/ente-io/ente/discussions/709.
- Document BuildKit requirement, as requested in https://github.com/ente-io/ente/issues/712.

[cli] Improve docs

---

.github/workflows/auth-crowdin.yml
.github/workflows/docs-deploy.yml
.github/workflows/mobile-crowdin.yml
.github/workflows/web-crowdin.yml
.github/workflows/web-nightly.yml

- Fix the branch name for the docs deployment
- Add web-nightly deployments
- Tweak the cron specification in existing workflows

[web] Add nightly deployments of web projects

---

CONTRIBUTING.md
SUPPORT.md
docs/README.md
web/docs/deploy.md

These changes were all made in previous PRs, this PR just ties up the loose ends and updates the documentation etc.

[web] Finalize deployment process

---

docs/docs/photos/troubleshooting/sharing-logs.md

[docs] Update sharing-logs.md

---

docs/docs/.vitepress/config.ts
docs/docs/.vitepress/sidebar.ts
docs/docs/self-hosting/troubleshooting/yarn.md

[docs] Fix build error and add a Yarn troubleshooting page

---

docs/docs/.vitepress/sidebar.ts
docs/docs/self-hosting/faq/otp.md

[docs] Add a note about how to get the OTT on self hosted instance

---

mobile/CHANGELOG.md
mobile/ios/Podfile.lock
mobile/ios/Runner.xcodeproj/project.pbxproj
mobile/lib/core/constants.dart
mobile/lib/generated/intl/messages_de.dart
mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/intl/messages_es.dart
mobile/lib/generated/intl/messages_fr.dart
mobile/lib/generated/intl/messages_it.dart
mobile/lib/generated/intl/messages_nl.dart
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_de.arb
mobile/lib/l10n/intl_en.arb
mobile/lib/l10n/intl_es.arb
mobile/lib/l10n/intl_fr.arb
mobile/lib/l10n/intl_it.arb
mobile/lib/l10n/intl_nl.arb
mobile/lib/l10n/intl_pt.arb
mobile/lib/l10n/intl_zh.arb
mobile/lib/services/update_service.dart
mobile/lib/ui/notification/update/change_log_page.dart
mobile/lib/ui/viewer/search/search_widget.dart
mobile/pubspec.yaml

- Updated change log.
- Some final changes.
- Bumped up to `v0.8.66`
https://github.com/ente-io/ente/assets/77285023/10e0d1a3-cdfc-4431-be6c-1eb8718d35db
https://github.com/ente-io/ente/assets/77285023/fed1e917-da2e-4001-b167-25fa72a1ff8c

[mob][photos] Update version and change log

---

.github/workflows/docs-verify-build.yml

Tested by opening this PR and verifying that the verify build workflow succeeded. Say verify one more time, I dare you...

[docs] Add a workflow to do a preflight verification of build on each PR

---

server/cmd/museum/main.go
server/pkg/controller/lock/lock.go
server/pkg/controller/object.go
server/pkg/repo/tasklock.go

[server] Release previous locks taken by host on statup

---

server/cmd/museum/main.go
server/pkg/controller/collection.go

[server] Reduce diff logs and minor refactor

---

docs/docs/photos/faq/index.md

[docs] Copy Auth FAQ from mobile app

---

docs/docs/.vitepress/sidebar.ts
docs/docs/auth/faq/index.md
docs/docs/photos/faq/index.md

[docs] Fix the location for auth faq

---

mobile/lib/generated/intl/messages_cs.dart
mobile/lib/generated/intl/messages_de.dart
mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/intl/messages_es.dart
mobile/lib/generated/intl/messages_fr.dart
mobile/lib/generated/intl/messages_it.dart
mobile/lib/generated/intl/messages_ko.dart
mobile/lib/generated/intl/messages_nl.dart
mobile/lib/generated/intl/messages_no.dart
mobile/lib/generated/intl/messages_pl.dart
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_en.arb
mobile/lib/ui/viewer/gallery/gallery_app_bar_widget.dart
mobile/lib/ui/viewer/gallery/uncategorized_page.dart

Verified that
✅  Sorting works as expected
✅ Clean Uncat description dialog shows up
✅ Error dialog comes up if clean operation fails

[mob][photos] FIx sorting for uncategorized section

---

server/ente/passkey.go
server/pkg/repo/two_factor_recovery/repository.go

[server] Change param type from uuid to string

---

mobile/.gitignore
web/apps/accounts/src/pages/passkeys/flow/index.tsx
web/apps/auth/src/pages/passkeys/finish/index.tsx
web/apps/photos/src/components/Sidebar/UtilitySection.tsx

[passkey][web] Restrict to internal user & fix minor bugs

---

server/ente/billing.go
server/pkg/controller/billing.go

✅  Basic monkey testing for free plan user.

[server] Refactor /user/plans

---

mobile/lib/ui/viewer/file/zoomable_image.dart
mobile/lib/ui/viewer/gallery/component/gallery_file_widget.dart

Sometimes, when opening an image from gallery, the hero animation fails to happen. This PR fixes this issue.
https://github.com/ente-io/ente/assets/77285023/2ee40ec8-58d0-4ca1-82fb-1be96581137b

[mobile][photos] Fix missing hero animation

---

server/cmd/museum/main.go
server/ente/admin.go
server/pkg/api/admin.go
server/pkg/controller/user/userauth.go

[server] Add admin API to change email address

---

auth/migration-guides/authy.md

Authy migration guide rewrite to make things much clearer and easier to follow.
N/A

[auth] Authy guide rewrite

---

cli/docs/release.md
mobile/docs/release.md

Related: https://github.com/ente-io/ente/discussions/1087#discussioncomment-8775807

[meta] Document the tag format, and call out the need to keep tag == title

---

desktop/docs/release.md
infra/copycat-db/README.md
infra/services/README.md
infra/services/prometheus/README.md
infra/services/prometheus/node-exporter.service
infra/services/prometheus/prometheus.service
infra/services/prometheus/prometheus.yml
infra/services/promtail/README.md
infra/services/promtail/promtail.service
infra/services/promtail/promtail.yaml

- Import the existing DesktopDistribute notes
- Define services
- Add prometheus and promtail definitions

[infra] Add more details about services

---

mobile/lib/services/machine_learning/machine_learning_controller.dart
mobile/lib/services/machine_learning/semantic_search/frameworks/ml_framework.dart
mobile/lib/services/remote_assets_service.dart

- Increase the interaction timeout to 15s
- Make sure that models aren't downloaded over mobile data, and that it resumes initialization when network conditions are favorable

[mobile] Enhance ML

---

server/cmd/museum/main.go
server/pkg/middleware/rate_limit.go

[server] Rate limit

---

docs/docs/photos/features/family-plans.md

[docs] Update family-plans.md

---

server/cmd/museum/main.go
server/pkg/controller/discord/discord.go
server/pkg/middleware/rate_limit.go

[server] Update alert copy & frequency

---

infra/services/nginx/README.md
server/scripts/deploy/README.md
server/scripts/deploy/museum.nginx.conf
server/scripts/deploy/museum.nginx.service

Tweaks and fixes as we go towards a real deployment

[server] Deploy behind nginx

---

infra/services/nginx/nginx.service
server/scripts/deploy/museum.nginx.service

Noticed during the recent deployment.

[server] Fix the dependency on nginx

---

infra/services/README.md

[infra] Mention that logging to stdout is a good default for services

---

.github/workflows/docs-deploy.yml

Fix what I accidentally broke in https://github.com/ente-io/ente/pull/1149

[meta] Fix the docs deployment workflow

---

.github/workflows/auth-release.yml
auth/linux/packaging/appimage/make_config.yaml

Auth desktop linux build fix + Playstore aab shouldn't be created if nightly or beta

[FIX] Libffi error for appimage

---

mobile/CHANGELOG.md
mobile/lib/services/update_service.dart
mobile/lib/ui/notification/update/change_log_page.dart

[mobile][photos] Update change log for v0.8.72 release

---

mobile/lib/utils/share_util.dart

[mobile][photos] fix: Image switcharoo bug when sharing from signal

---

.github/workflows/auth-release.yml
auth/pubspec.lock

fix: macos sha256 sum generation

---

web/apps/payments/package.json
web/yarn.lock

This was accidentally an ancient version of axios when importing from the older repo - update it to what the rest of the code uses (via the shared package).

[web] Fix nightly build

---

docs/docs/auth/migration-guides/authy/index.md

Changed "ente" to "Ente" as the first letter is meant to be a capital one now:

[docs] Change capitalization

---

cli/internal/crypto/crypto.go
cli/main.go
cli/pkg/mapper/photo.go

[cli] Improve logging for decryption error

---

server/ente/userentity/entity.go

[server] Add person EntityType

---

auth/pubspec.yaml

Bump auth to 2.0.50 build number

---

web/apps/cast/src/components/LargeType.tsx
web/apps/cast/src/components/Theatre/PhotoAuditorium.tsx
web/apps/cast/src/pages/slideshow.tsx
web/apps/photos/src/components/Collections/CollectionOptions/AlbumCastDialog.tsx
web/package.json
web/packages/shared/components/SingleInputForm.tsx

- Use 3001 for sidecars
- Use the placeholder as the placeholder, not as the label
- Change slideshow time from 5s => 10s
- Remove the 123456 below the actual code
- Make the code copyable without inserting spaces in between

[web] Various minor fixes and improvements to cast

---

mobile/lib/services/home_widget_service.dart
mobile/pubspec.lock
mobile/pubspec.yaml

- Switched to pub.dev version of home_widget
- Replaced count home widget with getInstalledWidgets().

[FIX] home widget count function and package source

---

.github/workflows/auth-release.yml
auth/linux/packaging/appimage/make_config.yaml

[FIX] libffi7 missing error in auth appimage

---

cli/internal/api/file_type.go
cli/pkg/mapper/photo.go
cli/pkg/remote_sync.go

[cli] Fix handling of delete file with stale colleciton entry

---

server/pkg/controller/collection.go

[server] Gracefully handle stale collection entry

---

mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/services/ignored_files_service.dart
mobile/lib/services/local_sync_service.dart

[mob]Ignore souceFileMissing error for iOS

---

mobile/lib/core/errors.dart
mobile/lib/services/remote_sync_service.dart
mobile/lib/services/sync_service.dart
mobile/lib/utils/file_uploader.dart
mobile/pubspec.lock
mobile/pubspec.yaml

Tested with and without granting `ACCESS_MEDIA_LOCATION`.

[mobile][photos] Do not upload files if ACCESS_MEDIA_LOCATION is not granted

---

mobile/lib/ui/viewer/file/detail_page.dart
mobile/lib/ui/viewer/file/zoomable_image.dart

Before
https://github.com/ente-io/ente/assets/77285023/75304321-1fa4-4d61-9ad1-cc87ade62f92
After
https://github.com/ente-io/ente/assets/77285023/55b204b2-773c-42db-a03c-c9879f33548b

[mobile][photos] Fix colours in loading screen on light theme when viewing photos

---

web/apps/photos/public/locales/en-US/translation.json
web/apps/photos/src/components/Collections/CollectionOptions/AlbumCastDialog.tsx
web/packages/shared/components/DialogBoxV2/types.ts

[web] Make the cast link clickable

---

web/apps/photos/src/components/Sidebar/Preferences/LanguageSelector.tsx
web/packages/ui/i18n.ts

The translation percentage of Russian in crowdin is now 100%, it's time to enable it as an option in the UI.
A big thank you to the translators ❤️

[web] Enable Russian

---

server/pkg/repo/authenticator/entity.go

When client tries to send update request with same data, the actual db update doesn't happen. This was resulting in 5xx error.

[server] Fix handling of redundant auth update

---

server/pkg/controller/embedding/controller.go

Also use different semaphore than existing diff API

[server] Increase embedding fetch limit

---

web/apps/staff/package.json
web/apps/staff/src/App.tsx
web/apps/staff/src/services/support-service.ts
web/packages/utils/package.json
web/yarn.lock

- Add schema validation of the response
- Add an example fetch

[web] Add an example fetch to staff

---

server/configurations/local.yaml
server/pkg/controller/mailing_lists.go
server/pkg/external/listmonk/api.go

Add listmonk mailing list subscribe and unsubscribe
Tested getSubscriberID, unsubscribe, and subscribe using a locally running listmonk server with different parameters.

Listmonk mailing list control 

---

infra/services/listmonk/listmonk.service

[infra] Fix the listmonk upgrade invocation

---

auth/linux/packaging/rpm/make_config.yaml

[FIX] RPM build

---

.github/workflows/auth-release.yml
auth/linux/packaging/appimage/make_config.yaml

[FIX] Compile of AppImage

---

.github/workflows/auth-release.yml
auth/linux/packaging/appimage/make_config.yaml

Fix build and unable to locate libtiff.so.5

[FIX] Appimage build

---

.github/workflows/auth-release.yml

UpdateDb command has localpaths instead of database-root, this fixes that.

[FIX] updatedb command

---

server/migrations/83_fix_ott_index.down.sql
server/migrations/83_fix_ott_index.up.sql
server/pkg/controller/user/userauth.go
server/pkg/repo/userauth.go

✅  Wrong attempt tracking is working fine
✅ Same ott can be issued for different app types
✅ For same app type, unique ott is issued

[Server] Fix unique ott constraint for multiple apps

---

mobile/lib/ui/payment/stripe_subscription_page.dart

Verified that free plan is highlighted for new sign ups

[mob] Fix active plan highlight

---

auth/linux/packaging/appimage/make_config.yaml
auth/pubspec.yaml

[fix] Appimage include libffi too as it's not included by default

---

web/apps/photos/src/constants/mlConfig.ts
web/apps/photos/src/services/machineLearning/blazeFaceDetectionService.ts
web/apps/photos/src/services/machineLearning/faceService.ts
web/apps/photos/src/services/machineLearning/laplacianBlurDetectionService.ts
web/apps/photos/src/services/machineLearning/machineLearningFactory.ts
web/apps/photos/src/services/machineLearning/machineLearningService.ts
web/apps/photos/src/services/machineLearning/mlWorkManager.ts
web/apps/photos/src/services/machineLearning/mobileFaceNetEmbeddingService.ts
web/apps/photos/src/services/machineLearning/yoloFaceDetectionService.ts
web/apps/photos/src/services/searchService.ts
web/apps/photos/src/types/machineLearning/archface.ts
web/apps/photos/src/types/machineLearning/data/clip.ts
web/apps/photos/src/types/machineLearning/data/face.ts
web/apps/photos/src/types/machineLearning/data/fileML.ts
web/apps/photos/src/types/machineLearning/index.ts
web/apps/photos/src/utils/image/index.ts
web/apps/photos/src/utils/machineLearning/faceAlign.ts
web/apps/photos/src/utils/machineLearning/faceDetection.ts
web/apps/photos/src/utils/machineLearning/index.ts
web/packages/eslint-config/index.js

Laurens has made the relevant changes to get ONNX-YOLO face detection working in a manner where the generated embeddings are the same as what get generated by the corresponding ML stack in the mobile client.
This PR cherry picks his ML related changes from the branch he was working in, but leaves out the surrounding scaffolding (We cannot merge that branch directly because it relies on wasm that we don't need and don't want to commit to main).
At this point this functionality is correct but not usable - the next step will be to tie this to the ONNX runtime that we already have on the Node.js layer of our desktop app.
**Tests**
- yarn dev + smoke test
- yarn build + smoke test
- yarn lint

[web] Import ONNX-YOLO face changes from the web_face branch

---

server/pkg/controller/storagebonus/referral_cron.go
server/pkg/controller/user/srp.go
server/pkg/utils/handler/handler.go

[server] Reduce noise from error logs

---

mobile/ios/Podfile.lock
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/services/machine_learning/semantic_search/embedding_store.dart
mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart
mobile/lib/services/search_service.dart

[mob] Minor fixes for semantic search

---

desktop/src/main.ts
web/apps/photos/src/components/ml/PeopleList.tsx
web/apps/photos/src/services/download/clients/photos.ts
web/apps/photos/src/services/download/clients/publicAlbums.ts
web/apps/photos/src/services/download/index.ts
web/apps/photos/src/services/machineLearning/faceService.ts
web/apps/photos/src/services/machineLearning/peopleService.ts
web/apps/photos/src/types/machineLearning/index.ts
web/apps/photos/src/utils/file/index.ts
web/apps/photos/src/utils/machineLearning/faceCrop.ts
web/apps/photos/src/utils/machineLearning/index.ts
web/apps/photos/src/utils/storage/mlIDbStorage.ts
web/docs/dependencies.md
web/docs/storage.md
web/packages/accounts/services/user.ts
web/packages/next/blob-cache.ts
web/packages/next/cache.ts
web/packages/shared/error/index.ts
web/packages/shared/storage/cache.ts

See the extensive documentation in `blob-cache.ts` for the why and the how. Done basic sanity testing for normal flows, the beta ML flows still need to be tested.

[desktop] Add an OPFS based cache

---

mobile/lib/services/update_service.dart
mobile/lib/ui/notification/update/change_log_page.dart
mobile/pubspec.yaml

[mob][photos] Prepare for release v0.8.79

---

server/cmd/museum/main.go
server/configurations/local.yaml
server/pkg/controller/public_collection.go
server/pkg/repo/collection.go
server/pkg/repo/public_collection.go

Ran locally with the config in local.yaml and verified that it's modified as well when I had put localhost:3002 in the museum.yaml config

[server] Pick base publicHost url from config

---

mobile/lib/generated/intl/messages_zh.dart
mobile/lib/models/location/location.freezed.dart
mobile/lib/models/location/location.g.dart
mobile/lib/models/location_tag/location_tag.freezed.dart
mobile/lib/models/location_tag/location_tag.g.dart
mobile/pubspec.yaml

[mob][photos] Upgrade freeze and generated files

---

mobile/lib/ui/tabs/home_widget.dart
mobile/pubspec.yaml

[mob][photos] Bump up to v0.8.81

---

desktop/src/main/fs.ts
desktop/src/main/ipc.ts
desktop/src/main/stream.ts
desktop/src/preload.ts
web/apps/photos/src/services/export/index.ts
web/apps/photos/src/utils/file/index.ts
web/apps/photos/src/utils/native-stream.ts
web/packages/next/types/ipc.ts

The data is getting streamed, but not correctly in some cases. So the mechanics are in place, need to figure out the readable stream chunks etc.

[desktop] Streaming IPC - Part 2/x

---

mobile/lib/generated/intl/messages_cs.dart
mobile/lib/generated/intl/messages_de.dart
mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/intl/messages_es.dart
mobile/lib/generated/intl/messages_fr.dart
mobile/lib/generated/intl/messages_it.dart
mobile/lib/generated/intl/messages_ko.dart
mobile/lib/generated/intl/messages_nl.dart
mobile/lib/generated/intl/messages_no.dart
mobile/lib/generated/intl/messages_pl.dart
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_cs.arb
mobile/lib/l10n/intl_de.arb
mobile/lib/l10n/intl_en.arb
mobile/lib/l10n/intl_es.arb
mobile/lib/l10n/intl_fr.arb
mobile/lib/l10n/intl_it.arb
mobile/lib/l10n/intl_ko.arb
mobile/lib/l10n/intl_nl.arb
mobile/lib/l10n/intl_no.arb
mobile/lib/l10n/intl_pl.arb
mobile/lib/l10n/intl_pt.arb
mobile/lib/l10n/intl_zh.arb
mobile/lib/ui/viewer/search/search_widget.dart

[mob][photos] Search field fixes

---

desktop/src/main/services/imageProcessor.ts

"resources" needs to be "build"

[desktop] Fix the imagemagick path when running in dev build

---

web/apps/photos/src/services/machineLearning/faceService.ts
web/apps/photos/src/services/machineLearning/laplacianBlurDetectionService.ts
web/apps/photos/src/types/machineLearning/index.ts

Improve blur detection that better handles noise in background of faces
Manually verified the blur detection scores are identical to those on mobile

[desktop] Better blur detection service

---

mobile/lib/db/files_db.dart

[mob][photos] Migrate from sqflite

---

mobile/lib/ui/account/recovery_page.dart
mobile/lib/ui/common/linear_progress_dialog.dart
mobile/lib/ui/common/progress_dialog.dart
mobile/lib/ui/payment/payment_web_page.dart
mobile/lib/ui/settings/app_update_dialog.dart
mobile/lib/ui/tabs/home_widget.dart
mobile/lib/ui/tools/app_lock.dart
mobile/lib/ui/tools/editor/image_editor_page.dart

[Documentation followed for the migration](https://docs.flutter.dev/release/breaking-changes/android-predictive-back)

[mob][photos] Migrate use of WillPopScope to PopScope

---

server/pkg/controller/file.go

During the testing of copyFile functionality, I ran into issues where files were created without all attributes (esp File EncryptedKey & Nonce for thumbnail and file decryption).
This change
Tested regular file upload, unable to test update as Photos app on simulator is not showing save option. I don't expect it to break.

[server] Improvate req validation on file createOrUpdate

---

.github/workflows/mobile-internal-release.yml
.github/workflows/mobile-release.yml
mobile/README.md

Build was failing with this error
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':connectivity_plus:compileReleaseJavaWithJavac'.
> error: invalid source release: 17
```

[mob][photos] Fix build failing in release workflow

---

mobile/lib/core/constants.dart
mobile/lib/services/collections_service.dart
mobile/pubspec.yaml

[mob][photos] Bump version : 0.8.84+604

---

mobile/lib/ui/viewer/file_details/favorite_widget.dart

https://github.com/ente-io/ente/assets/254676/94f15baf-d350-4738-879e-ad163a1e4b45

[mob][photos] Increase loading iconSize + reduce padding

---

mobile/lib/utils/file_uploader.dart

[mob][photos] Restrict multipart upload to debug builds

---

web/apps/cast/src/pages/index.tsx

[cast] Add additional console logs for debuging remote device

---

web/apps/cast/src/pages/index.tsx

[web] Cast: add additional logs

---

web/apps/cast/src/pages/index.tsx

[web] Deploy cast

---

web/apps/cast/src/pages/index.tsx
web/apps/cast/src/utils/useCastReceiver.tsx

[web][cast] Minor fixes

---

server/pkg/controller/file.go

[server] Fix validation for fileUpdate

---

server/pkg/controller/file.go

Even collectionID is missing.
```dart
final request = {
"id": file.uploadedFileID,
"file": {
"objectKey": fileObjectKey,
"decryptionHeader": fileDecryptionHeader,
"size": fileSize,
},
"thumbnail": {
"objectKey": thumbnailObjectKey,
"decryptionHeader": thumbnailDecryptionHeader,
"size": thumbnailSize,
},
"metadata": {
"encryptedData": encryptedMetadata,
"decryptionHeader": metadataDecryptionHeader,
},
};
```

[server] Another fix in file update req validation

---

server/pkg/controller/file.go

Tested file create and file update locally

[server] Fix another validation issue

---

mobile/lib/ui/viewer/file_details/face_widget.dart
mobile/lib/ui/viewer/people/cropped_face_image_view.dart

[mob][photos] Fix issues with face thumbnail

---

server/cmd/museum/main.go
server/ente/remotestore.go
server/pkg/api/admin.go
server/pkg/api/remotestore.go
server/pkg/controller/remotestore/controller.go
server/pkg/repo/remotestore/repository.go

[server] Add API to get feature flags + allow admin edit

---

server/docs/docker.md

Fixed typo

---

mobile/lib/ui/common/popup_item.dart
mobile/lib/ui/viewer/gallery/gallery_app_bar_widget.dart

[mob] Add Ente popup menu widget

---

web/apps/cast/src/pages/index.tsx
web/apps/cast/src/pages/slideshow.tsx

[cast] Add logs

---

web/apps/cast/src/components/PhotoAuditorium.tsx
web/apps/cast/src/pages/slideshow.tsx

[web][cast] Add logs

---

web/apps/cast/src/components/PhotoAuditorium.tsx
web/apps/cast/src/pages/index.tsx
web/apps/cast/src/pages/slideshow.tsx

Cast logs v2

---

.github/workflows/auth-release.yml
auth/linux/packaging/rpm/make_config.yaml
auth/pubspec.lock
auth/pubspec.yaml

Try to remove missing deps error in auth desktop.

[FIX] Rpm build for Auth

---

auth/pubspec.yaml

chore: bump version for auth to 256

---

desktop/src/main/services/dir.ts
desktop/src/main/services/upload.ts
desktop/src/main/services/watch.ts
desktop/src/main/stores/upload-status.ts
desktop/src/main/stream.ts
desktop/src/main/utils/electron.ts
web/apps/photos/src/components/PhotoFrame.tsx
web/apps/photos/src/components/Upload/Uploader.tsx
web/apps/photos/src/services/exif.ts
web/apps/photos/src/services/export/index.ts
web/apps/photos/src/services/upload/uploadService.ts
web/apps/photos/src/utils/file/index.ts
web/apps/photos/src/utils/native-stream.ts
web/packages/next/types/ipc.ts

And other fixes. Getting close to a stable desktop build.

[desktop] Finalize zip handling

---

desktop/src/main/ipc.ts
desktop/src/main/services/watch.ts
desktop/src/main/stream.ts
desktop/src/preload.ts
web/apps/photos/src/components/PhotoList/index.tsx
web/apps/photos/src/components/Search/SearchBar/styledComponents.tsx
web/apps/photos/src/utils/native-stream.ts
web/packages/accounts/services/user.ts
web/packages/next/types/ipc.ts
web/packages/shared/components/Navbar/base.tsx

[desktop] More IPC enhancements and fixes

---

mobile/lib/utils/file_uploader.dart

[mob] Log n/w when mobileBackUpIsDisabled and backup is happening

---

desktop/.github/workflows/desktop-release.yml

ref_name is the (from my understanding) the shorthand we need for prefixing. Untested, will do a test build.

[desktop] Fix ref ref in action

---

web/apps/cast/src/pages/index.tsx
web/packages/shared/network/cast.ts

✅  Tested end-to-end locally, including manual pairing

[web][cast] Use deviceCode generated by server

---

server/ente/cast/entity.go
server/pkg/api/cast.go
server/pkg/controller/cast/controller.go
server/pkg/controller/storagebonus/referral.go
server/pkg/repo/cast/repo.go
server/pkg/utils/random/generate.go

[server][cast] Generate alphaNumberic codes for cast

---

desktop/.github/workflows/desktop-release.yml
desktop/docs/release.md
desktop/electron-builder.yml
desktop/package.json
desktop/yarn.lock

- **Run the electron builder in the correct path**
- **Provide repository**
- **Move to new notarization mechanism**
- **Use an Electron Builder version that supports notarytool**

[desktop] Prepare for release

---

mobile/lib/ui/cast/auto.dart
mobile/lib/ui/viewer/gallery/gallery_app_bar_widget.dart

[mobile][cast] Fix minor UI issues

---

.github/workflows/auth-crowdin.yml
.github/workflows/mobile-crowdin.yml
.github/workflows/web-crowdin.yml
.github/workflows/web-deploy-accounts.yml
.github/workflows/web-deploy-cast.yml

- Namespace Crowdin PR branches
- Allow force deploying cast and accounts (while they're still in dev)

[meta] Namespace translation branch names, and allow force deploy for WIP apps

---

web/apps/photos/src/components/PhotoList/dedupe.tsx
web/apps/photos/src/components/Sidebar/Preferences/LanguageSelector.tsx
web/apps/photos/src/pages/gallery/index.tsx
web/packages/next/i18n.ts
web/packages/next/locales/en-US/translation.json

German translation has reached almost 100% coverage, time to enable it. Thank you to all the translators in Crowdin 🙏

[web] Enable German

---

mobile/lib/ui/cast/auto.dart
mobile/lib/ui/viewer/gallery/gallery_app_bar_widget.dart
mobile/plugins/ente_cast_normal/lib/src/service.dart

[mob] Cast improvements

---

mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/pubspec.yaml

[mob] Bump version 0.8.91+611

---

mobile/ios/Runner/Info.plist
mobile/lib/ui/viewer/gallery/gallery_app_bar_widget.dart

[mob] Disable auto-cast for iOS

---

mobile/lib/models/gallery_type.dart
mobile/lib/services/collections_service.dart
mobile/lib/ui/viewer/actions/file_selection_actions_widget.dart
mobile/lib/ui/viewer/file/file_app_bar.dart
mobile/lib/ui/viewer/gallery/gallery_app_bar_widget.dart

[mob] Enable shared item action

---

.github/workflows/server-publish.yml
server/docs/publish.md

Helps with easily finding changes since last publish.

[server] Tag the source code for latest ghcr.io Docker image with museum/ghcr

---

web/apps/photos/src/components/Directory/index.tsx
web/apps/photos/src/components/PhotoViewer/styledComponents/LivePhotoBtn.tsx
web/apps/photos/src/components/WatchFolder.tsx
web/packages/accounts/pages/credentials.tsx

[web] Show email on password screen

---

server/pkg/repo/cast/repo.go

[server] always use upperCase for castCode

---

server/ente/embedding.go
server/pkg/controller/embedding/controller.go
server/pkg/repo/embedding/repository.go

[server] Avoid pulling files with no-embedding info

---

server/pkg/controller/embedding/controller.go

[server] Add timeout while fetching embedding

---

server/pkg/api/file.go
server/pkg/api/public_collection.go
server/pkg/controller/embedding/controller.go
server/pkg/controller/file.go
server/pkg/controller/file_copy/file_copy.go

[server] Fix panic in copy file + increase emb fetch timeout

---

desktop/docs/release.md
desktop/src/main/log.ts
desktop/src/main/services/dir.ts
desktop/yarn.lock
web/apps/photos/src/utils/user/index.ts

- Whitelist uid
- electron 30.0.3
- Document log paths

[desktop] RC

---

web/packages/accounts/pages/credentials.tsx

[web] Show api host on dev builds

---

server/configurations/local.yaml
server/pkg/utils/email/email.go

Ref: https://github.com/ente-io/ente/discussions/1582#discussioncomment-9404061

[server] Make sender email configurable

---

desktop/src/main/services/image.ts

Related: https://github.com/ente-io/ImageMagick

[desktop] Imagemagick related tweaks

---

server/ente/file.go
server/pkg/controller/file.go
server/pkg/repo/file.go

[server] Add option to updateMetadata without versionChange

---

mobile/lib/services/machine_learning/semantic_search/embedding_store.dart

[mob] Keep fetching embeddings till no embedding is returned

---

mobile/lib/ui/viewer/file/file_app_bar.dart
mobile/lib/ui/viewer/file_details/favorite_widget.dart

This reverts commit 0b212bf7a655b02bec11face5cf15966579f7f62.

Revert "Move padding within to increase tap-able area"

---

desktop/src/main/ipc.ts
desktop/src/main/services/app-update.ts
desktop/src/main/services/ffmpeg.ts
desktop/src/main/services/image.ts
desktop/src/main/stream.ts
desktop/src/main/utils/common.ts
desktop/src/main/utils/electron.ts
desktop/src/main/utils/temp.ts
desktop/src/preload.ts
web/apps/photos/src/services/download/index.ts
web/apps/photos/src/services/ffmpeg.ts
web/apps/photos/src/utils/native-stream.ts
web/apps/photos/src/worker/ffmpeg.worker.ts
web/packages/accounts/services/user.ts
web/packages/next/types/ipc.ts

This was the last pending TODO for getting the new build at par with how the olde one behaved.

[desktop] Fix large video conversion

---

mobile/lib/db/embeddings_db.dart
mobile/lib/db/upload_locks_db.dart
mobile/lib/events/embedding_updated_event.dart
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart
mobile/lib/ui/settings/machine_learning_settings_page.dart

In case of semantic search, the cache update was taking time due to debouncer. 
It was resulting in re-indexing of certain files. Also, the status of indexing was stale as we were relying on same event to schedule update of cache and refresh status (which relies on cache).

[mob] Minor fixes

---

desktop/docs/dependencies.md
web/docs/dependencies.md
web/package.json
web/yarn.lock

[web] Lint concurrently

---

auth/lib/onboarding/view/common/add_tag.dart
auth/lib/onboarding/view/common/edit_tag.dart

fix(auth): set maxlength limit of 100 to tags

---

auth/pubspec.yaml

[auth] Bump version: 2.0.58

---

desktop/yarn.lock

https://github.com/electron/electron/releases/tag/v30.0.6

[desktop] Update to electron 30.0.6

---

mobile/lib/services/remote_assets_service.dart
mobile/lib/ui/settings/machine_learning_settings_page.dart

Tested locally, enabled for internal users only.

[mob] Show progress for downloading of clip models

---

docs/docs/self-hosting/guides/external-s3.md

Thanks to Zul from our community Discord. These clarifications were provided by them, I just made some grammatical edits to fit the document better.

[docs] Add some more context to web + albums section of external-s3 guide

---

docs/docs/self-hosting/guides/external-s3.md
docs/package.json

Same as b3ec2481bd34270ef8d9c7d257461a0f9c5eee67

[docs] Add yarn to package.json

---

auth/ios/Podfile.lock
auth/macos/Podfile.lock

[FIX] Auth Macos build

---

auth/pubspec.yaml

[auth] Bump version to v3.0.0

---

desktop/src/main.ts

Was able to reproduce the issue in Ubuntu 24.04 LTS
Ref: https://github.com/electron/electron/issues/31485

[desktop] Add note about xdg-open bug on Ubuntu

---

auth/ios/Podfile.lock

[auth] iOS build changes

---

server/pkg/controller/embedding/delete.go

[server] Remove fallback check as dc column was added with default dc b2

---

server/pkg/controller/embedding/delete.go
server/pkg/controller/object_cleanup.go

[server] Improve log

---

auth/pubspec.yaml
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_zh.dart

[auth] Bump version

---

auth/lib/models/code.dart
auth/lib/models/code_display.dart
auth/lib/store/code_store.dart
auth/pubspec.yaml

[Auth] Fix parsing of code display when issuer/account contains special character

---

mobile/lib/db/embeddings_db.dart

[mob] Fix bug during logout

---

auth/lib/app/view/app.dart
auth/lib/ui/code_widget.dart

[FIX (Auth)] Destroy window on exit, Color scheme fix, Hide code for steam fix

---

mobile/pubspec.yaml

Bump for internal release, which I forgot in previous PR.

[mob][photos] Bump

---

mobile/pubspec.yaml

Forgot to bump version in previous PR

Dart UI isolate fix

---

mobile/lib/ui/viewer/search/search_widget.dart

Search was infinitely loading even after all search results are ready.

[mob][photos] Fix infinite loading on searching

---

web/apps/auth/package.json
web/apps/auth/src/pages/auth.tsx
web/apps/auth/src/services/code.ts
web/apps/photos/package.json
web/docs/dependencies.md
web/yarn.lock

Preparing for steam support (sibling of https://github.com/ente-io/ente/pull/1820)

[web] Auth cleanup - Part 2/x

---

web/apps/auth/src/pages/auth.tsx
web/apps/auth/src/services/code.ts
web/apps/auth/src/services/remote.ts
web/apps/photos/package.json
web/yarn.lock

[web] Auth cleanup - Part 3/3

---

mobile/lib/face/db.dart
mobile/lib/services/machine_learning/face_ml/face_clustering/face_clustering_service.dart
mobile/lib/services/machine_learning/face_ml/face_ml_result.dart
mobile/lib/services/machine_learning/face_ml/face_ml_service.dart
mobile/lib/services/machine_learning/file_ml/remote_fileml_service.dart
mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart
mobile/lib/services/search_service.dart
mobile/lib/ui/settings/debug/face_debug_section_widget.dart
mobile/lib/ui/settings/machine_learning_settings_page.dart
mobile/lib/utils/ml_util.dart
mobile/pubspec.yaml

- Fix embeddings fetch issue
- Decrypt embeddings in computer
- Change clustering sorting and remove restrictions
- Cleaned up faces status page
Tested in debug mode on pixel phone.

Face small improvements

---

web/apps/auth/src/pages/auth.tsx
web/apps/auth/src/services/code.ts

- Use HOTP counter
- Don't advance the bar for HOTPs

[web] Auth - Improve HOTP support

---

mobile/lib/ui/viewer/gallery/hooks/add_photos_sheet.dart

[mob] Use custom assetPickerTextDelegate to use en as default

---

mobile/lib/core/constants.dart
mobile/lib/ui/viewer/gallery/hooks/add_photos_sheet.dart

[mob] Increase limit to 50 for adding asset from device

---

mobile/lib/ui/viewer/people/cluster_page.dart

Wrap add person name banner inside safeArea

---

mobile/lib/services/machine_learning/face_ml/face_ml_service.dart
mobile/lib/services/machine_learning/face_ml/person/person_service.dart
mobile/lib/ui/settings/debug/face_debug_section_widget.dart

[mob][photos] Fetch remote feedback before clustering

---

.github/workflows/mobile-lint.yml
mobile/README.md
mobile/ios/Podfile.lock
mobile/pubspec.lock
mobile/pubspec.yaml

This reverts commit a41f705dada762f4c6254734823aa564f691d677.
Need to update `flutter_map` dependency to work with flutter 3.22.0.

Revert "Upgrade to flutter 3.22.0 (#1804)"

---

mobile/lib/ui/viewer/people/add_person_action_sheet.dart

[mob] Lint fix

---

.github/workflows/mobile-internal-release.yml
.github/workflows/mobile-lint.yml
.github/workflows/mobile-release.yml
mobile/README.md

[mob] Use same flutter version in all workflows

---

mobile/lib/services/machine_learning/face_ml/face_clustering/face_clustering_service.dart
mobile/lib/services/machine_learning/face_ml/face_ml_service.dart
mobile/lib/services/machine_learning/face_ml/feedback/cluster_feedback.dart
mobile/lib/ui/viewer/people/cluster_app_bar.dart

Fixed issue with breaking up clusters
Tested in debug mode on my pixel

Breakup cluster

---

mobile/lib/ui/viewer/file/file_details_widget.dart

[mob] Hide faceItemWidget from fileInfo if faceIndexing is disabled

---

mobile/lib/ui/viewer/people/cluster_page.dart
mobile/lib/ui/viewer/people/people_app_bar.dart
mobile/lib/ui/viewer/people/person_clusters_page.dart
mobile/pubspec.yaml

Last fixes

---

mobile/lib/utils/thumbnail_util.dart

[mob] Log file details on decryption Error

---

mobile/lib/generated/intl/messages_cs.dart
mobile/lib/generated/intl/messages_de.dart
mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/intl/messages_es.dart
mobile/lib/generated/intl/messages_fr.dart
mobile/lib/generated/intl/messages_it.dart
mobile/lib/generated/intl/messages_ko.dart
mobile/lib/generated/intl/messages_nl.dart
mobile/lib/generated/intl/messages_no.dart
mobile/lib/generated/intl/messages_pl.dart
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_en.arb
mobile/lib/services/machine_learning/face_ml/face_ml_service.dart
mobile/lib/ui/settings/machine_learning_settings_page.dart
mobile/lib/ui/viewer/people/add_person_action_sheet.dart
mobile/lib/ui/viewer/people/person_row_item.dart
mobile/pubspec.yaml

- Some UI alignment changes
- More error logging

More tiny faces

---

desktop/.github/workflows/desktop-release.yml
desktop/docs/release.md

[desktop] Nightly builds

---

mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/l10n.dart
mobile/lib/services/machine_learning/face_ml/face_ml_service.dart
mobile/lib/ui/settings/machine_learning_settings_page.dart
mobile/pubspec.yaml

- Decreased clustering bucket size
- Show on UI when clustering is running

Final beta face

---

cli/internal/crypto/crypto.go
cli/internal/crypto/crypto_libsodium.go
cli/main.go
cli/pkg/authenticator/decrypt.go

[cli] Fix bug in decrypting exported data from Ente Auth

---

mobile/lib/core/configuration.dart
mobile/lib/generated/intl/messages_de.dart
mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/intl/messages_es.dart
mobile/lib/generated/intl/messages_fr.dart
mobile/lib/generated/intl/messages_it.dart
mobile/lib/generated/intl/messages_nl.dart
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_en.arb
mobile/lib/main.dart
mobile/lib/ui/home/landing_page_widget.dart

[mob] Gracefully handle the case when app is stuck due to secureStore exception

---

mobile/pubspec.yaml

[photos] bump version 0.8.128+648

---

desktop/tsconfig.json
desktop/yarn.lock

- Shorten tsconfig include
- Update @typescript-eslint/

[desktop] Minor tweaks

---

auth/lib/ui/settings/data/import/aegis_import.dart
auth/lib/ui/settings/data/import/bitwarden_import.dart
auth/lib/ui/settings/data/import/lastpass_import.dart
auth/lib/ui/settings/data/import/raivo_plain_text_import.dart
auth/lib/ui/settings/data/import/two_fas_import.dart
auth/pubspec.yaml

Surfacing error information on UI. 
This is to reduce the to and fro between customer and support as error logging isn't enabled by default.  Also, added missing logs at certain places.

[auth] Surface more information about importError on UI

---

auth/lib/ui/settings/data/import/aegis_import.dart
auth/pubspec.yaml

[AegisImport] Fix Steam code import & parse groups and fav flag

---

mobile/pubspec.yaml

Bumping up version for internal release.

[mob][photos] bump up to v0.8.130

---

docs/docs/self-hosting/faq/sharing.md

Credits: Dylanger in #self-hosting on our community Discord
(https://discord.com/channels/948937918347608085/1215252276911018014/1247207784806613123)

[docs] Add an example working Dockerfile for public albums

---

mobile/lib/face/db.dart
mobile/lib/generated/intl/messages_de.dart
mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/intl/messages_es.dart
mobile/lib/generated/intl/messages_fr.dart
mobile/lib/generated/intl/messages_it.dart
mobile/lib/generated/intl/messages_nl.dart
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_de.arb
mobile/lib/l10n/intl_en.arb
mobile/lib/l10n/intl_es.arb
mobile/lib/l10n/intl_fr.arb
mobile/lib/l10n/intl_it.arb
mobile/lib/l10n/intl_nl.arb
mobile/lib/l10n/intl_pt.arb
mobile/lib/l10n/intl_zh.arb
mobile/lib/services/machine_learning/face_ml/face_filtering/face_filtering_constants.dart
mobile/lib/services/machine_learning/machine_learning_controller.dart
mobile/lib/ui/settings/machine_learning_settings_page.dart
mobile/lib/ui/settings/storage_card_widget.dart
mobile/lib/ui/viewer/people/add_person_action_sheet.dart
mobile/lib/ui/viewer/people/person_cluster_suggestion.dart

- Minimum cluster size of 10
- Suggestions instant undo button
- Sort names alphabetically in naming sheet
- Remove ripple effect in suggestions
- Don't pause ML in ML settings page (unless device is unhealthy)

Face improvements

---

.github/workflows/auth-lint.yml
.github/workflows/auth-release.yml
auth/pubspec.lock
auth/pubspec.yaml

This reverts commit b753c47e0139ec6857ba8e3bfbc6f058e485ecd4.

[auth] Downgrade to flutter v3.19.3

---

mobile/lib/services/machine_learning/face_ml/face_ml_service.dart
mobile/lib/services/machine_learning/machine_learning_controller.dart

- User interaction pause in iOS
- Face indexing cooldown
- Pause indexing instantly
- Increase file download limit

Face cooldown

---

mobile/pubspec.yaml

[photos] Bump version 0.8.132+652

---

auth/lib/ui/settings/data/import/bitwarden_import.dart
auth/lib/ui/settings/data/import/raivo_plain_text_import.dart
auth/pubspec.yaml

[auth] Fix handling of no username during bitwarden import

---

cli/README.md
cli/docker-compose.yml
cli/main.go

[cli] Update README

---

mobile/lib/ui/components/title_bar_title_widget.dart
mobile/lib/ui/tabs/shared/all_quick_links_page.dart
mobile/lib/ui/tabs/shared/quick_link_album_item.dart
mobile/lib/ui/tabs/shared_collections_tab.dart

https://github.com/ente-io/ente/assets/77285023/5656205b-e0c6-484b-a20b-24ed5294fd18

[photos][mob] Enhance quick links section UI/UX

---

docs/docs/auth/migration-guides/most-providers/index.md

Added detail to docs on what's able to be imported via the app
Give me a shout if anything needs updating!

Created instructions to import from most providers

---

mobile/lib/main.dart

Add more startup logs

---

server/pkg/api/file.go
server/pkg/controller/file.go
server/pkg/repo/object.go

Tested locally.
Verified that the CLI client tried to download the file from pref Wasabi bucket flow,while the web client downloaded the file from B2

[server] Prefer wasabi for downloading files via CLI

---

mobile/lib/main.dart

Revert "[mob][photos] Fix BG task not getting killed"

---

mobile/lib/services/collections_service.dart

[photos] Hide Archived collections from on Ente section

---

web/apps/accounts/src/pages/_app.tsx
web/apps/accounts/src/pages/passkeys/handoff.tsx
web/apps/accounts/src/pages/passkeys/index.tsx
web/apps/accounts/src/pages/passkeys/verify.tsx
web/apps/accounts/src/services/passkey.ts
web/apps/auth/src/pages/_app.tsx
web/apps/photos/src/pages/_app.tsx
web/packages/accounts/pages/credentials.tsx
web/packages/accounts/pages/verify.tsx
web/packages/accounts/services/logout.ts
web/packages/accounts/services/passkey.ts
web/packages/new/photos/services/feature-flags.ts
web/packages/next/http.ts
web/packages/next/local-user.ts
web/packages/shared/storage/localStorage/index.ts

[web] Cleanup passkeys manage page

---

docs/docs/self-hosting/guides/external-s3.md

This PR adds a configuration option needed if you want sharable urls to work

[docs] Add sharable URL configuration

---

cli/internal/api/client.go
cli/main.go

[cli] Fix: Retry on all 5xx errors 

---

desktop/electron-builder.yml
desktop/src/main.ts
desktop/src/preload.ts
web/apps/photos/src/pages/_app.tsx
web/packages/accounts/services/passkey.ts
web/packages/next/types/ipc.ts

[desktop] Handle passkey redirect

---

desktop/src/main.ts

Tested on an Ubuntu 24 VM, with deb it works out of the box, with AppImage I needed to install `appimaged` as recommended by https://docs.appimage.org/user-guide/run-appimages.html#integrating-appimages-into-the-desktop.

[photosd] Handle passkey deeplinks on Linux and Windows

---

auth/lib/services/user_service.dart
auth/lib/ui/passkey_page.dart
auth/macos/Runner/Info.plist

[auth] Register url scheme for macos

---

.github/workflows/auth-lint.yml
.github/workflows/auth-release.yml
auth/lib/main.dart
auth/linux/CMakeLists.txt
auth/linux/my_application.cc
auth/pubspec.lock
auth/pubspec.yaml

Black screen issue was caused by https://github.com/leanflutter/window_manager/issues/460, till then I have used a workaround from https://github.com/leanflutter/window_manager/issues/460#issuecomment-2110180143.
Also update plugins.

[Auth] Bump flutter to 3.22

---

auth/lib/store/code_display_store.dart
auth/lib/ui/home_page.dart

[Auth] Disable search suggestions and sort tags

---

server/cmd/museum/main.go
server/ente/errors.go
server/migrations/87_passkey_login_token.down.sql
server/migrations/87_passkey_login_token.up.sql
server/pkg/api/user.go
server/pkg/controller/user/jwt.go
server/pkg/repo/passkey/passkey.go
server/pkg/utils/time/time.go

[server] Reduce passkey JWT duration + API to get token via sessionID

---

auth/android/app/src/main/res/mipmap-anydpi-v26/launcher_icon.xml

Add monochrome icon support for android
not tested

[auth] Add monochrome icon support for android

---

mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_en.arb
mobile/lib/services/update_service.dart
mobile/lib/ui/notification/update/change_log_page.dart

Change log

---

auth/lib/ui/settings/data/import/two_fas_import.dart

[auth] Fix twoFas import with missing issuerName

---

auth/lib/main.dart

[auth] Fix url scheme for auth windows app

---

auth/pubspec.yaml

[auth] Bump version to v3.0.11

---

auth/lib/services/user_service.dart
auth/pubspec.yaml
mobile/lib/services/user_service.dart
mobile/pubspec.yaml

[mob][auth] Fix handling of passkey when email verification is turned on

---

mobile/lib/ui/components/text_input_widget.dart
mobile/lib/ui/settings/TEMP/lock_screen_option_confirm_password.dart

Surface error state in `TextInputWidget` if password entered is incorrect.

Error state for text input widget

---

mobile/pubspec.yaml

[photos] Bump version v0.9.0

---

mobile/ios/Runner/Info.plist

[photos] Update bundle name from ente Photos -> Ente Photos

---

.github/workflows/auth-release.yml
auth/linux/packaging/appimage/make_config.yaml
auth/linux/packaging/deb/make_config.yaml
auth/linux/packaging/rpm/make_config.yaml
auth/pubspec.lock

- Updated url to enteauth://passkey
- Support mimetype in appimage so redirection is done properly

[Auth] Passkey fix for linux

---

docs/docs/photos/troubleshooting/desktop-install/index.md

Nb: black works fine in dark mode too

[docs] Add a border to help differentiate the image from the subsequent text

---

desktop/.github/workflows/desktop-release.yml
desktop/docs/release.md

Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

[desktop] Continue iterating of the pre-release process

---

cli/config.yaml.example
cli/internal/api/login.go
cli/internal/api/login_type.go
cli/internal/promt.go
cli/main.go
cli/pkg/account.go
cli/pkg/sign_in.go
cli/utils/browser/browser.go
cli/utils/constants/constants.go

- Print help docs when no input is passed.
Tested locally

[cli] Add support for handling passkey based MFA

---

.github/workflows/auth-crowdin.yml
.github/workflows/mobile-crowdin.yml
.github/workflows/web-crowdin-push.yml
.github/workflows/web-crowdin.yml

https://github.com/crowdin/github-action/releases/tag/v2.0.0

[meta] Update to v2 of Crowdin action

---

mobile/lib/db/files_db.dart

Tested locally and verified the archived items are now hidden from memories.

[mob][fix] Hide archived items from memories

---

mobile/lib/generated/intl/messages_ru.dart
mobile/lib/ui/viewer/file_details/creation_time_item_widget.dart

Fixes https://github.com/ente-io/ente/issues/2155
Tested locally

Date picker transaltion

---

mobile/lib/generated/intl/messages_all.dart
mobile/lib/generated/intl/messages_de.dart
mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_en.arb
mobile/lib/ui/viewer/people/person_cluster_suggestion.dart

[mob] Log suggestion errors

---

server/ente/errors.go
server/pkg/controller/passkeys.go
server/pkg/repo/passkey/passkey.go

[server] Improve passkey error handling

---

web/README.md
web/apps/accounts/tsconfig.json
web/apps/cast/.eslintrc.js
web/apps/cast/src/components/FilledCircleCheck.tsx
web/apps/cast/src/components/PairingCode.tsx
web/apps/cast/src/pages/_app.tsx
web/apps/cast/src/pages/index.tsx
web/apps/cast/src/pages/slideshow.tsx
web/apps/cast/src/services/cast-data.ts
web/apps/cast/src/services/chromecast.ts
web/apps/cast/src/services/pair.ts
web/apps/cast/src/services/render.ts
web/packages/build-config/eslintrc-base.js
web/packages/build-config/eslintrc-react.js

[web] Better tsc/lint in more places

---

auth/ios/Podfile.lock
auth/lib/app/view/app.dart
auth/lib/services/user_service.dart
auth/lib/ui/account/logout_dialog.dart
auth/macos/Podfile.lock
auth/pubspec.lock
auth/pubspec.yaml

[auth] Sync on app resume

---

mobile/lib/events/people_changed_event.dart
mobile/lib/services/machine_learning/face_ml/face_ml_service.dart
mobile/lib/services/machine_learning/face_ml/feedback/cluster_feedback.dart
mobile/lib/services/machine_learning/face_ml/person/person_service.dart
mobile/lib/ui/viewer/actions/file_selection_actions_widget.dart

This fixes a bug where user feedback to remove a file from a certain person would immediately be overwritten by remote sync.

Remove feedback

---

mobile/lib/core/error-reporting/super_logging.dart
mobile/lib/main.dart
mobile/lib/services/collections_service.dart
mobile/lib/services/remote_sync_service.dart
mobile/lib/services/user_service.dart
mobile/lib/ui/viewer/gallery/gallery_app_bar_widget.dart
mobile/lib/utils/file_uploader.dart
mobile/lib/utils/file_uploader_util.dart

[mob] Reduce error severity

---

web/apps/photos/src/services/upload/uploadManager.ts

Tested on macOS with large videos, but I was unable to hit the scenario described. Will request a user who reported this issue on their Linux machine to try out a nightly build with this change and see if it helps.

[desktop] Add a memory usage high water mark during uploads

---

mobile/ios/Podfile.lock
mobile/pubspec.lock
mobile/pubspec.yaml

Upgrade onnx dependency

---

infra/workers/README.md
infra/workers/cast-albums/package.json
infra/workers/files/package.json
infra/workers/github-discord-notifier/package.json
infra/workers/health-check/package.json
infra/workers/package.json
infra/workers/public-albums/package.json
infra/workers/sentry-reporter/package.json
infra/workers/tail/package.json
infra/workers/thumbnails/package.json
infra/workers/uploader/package.json

The duplicate disk usage of individual node_modules is starting to get prohibitive.

[workers] Use yarn workspaces

---

auth/lib/l10n/arb/app_en.arb
auth/lib/services/passkey_service.dart
auth/lib/services/user_service.dart
auth/lib/ui/account/password_entry_page.dart
auth/lib/ui/account/verify_recovery_page.dart
auth/lib/ui/components/buttons/button_widget.dart
auth/lib/ui/home_page.dart
auth/lib/ui/passkey_page.dart
auth/lib/ui/settings/account_section_widget.dart
auth/lib/ui/settings/security_section_widget.dart
auth/lib/utils/dialog_util.dart
auth/pubspec.yaml

[auth] Show contact support option on error

---

mobile/pubspec.yaml

Bump version

---

web/apps/accounts/src/services/passkey.ts

Solves a problem someone was facing on our Discord:
https://discord.com/channels/948937918347608085/1215252276911018014/1253766354402545754

[accounts] Make it easier for self hosters to use passkeys

---

auth/lib/core/network.dart
auth/lib/core/win_http_client.dart
auth/pubspec.yaml

[auth] Potential fix for invalid handshake error on Windows

---

auth/lib/core/win_http_client.dart

[auth] Lint fix

---

.github/workflows/auth-release.yml
auth/linux/packaging/ente_auth.appdata.xml
auth/linux/packaging/pacman/make_config.yaml

- Pacman Build for Arch linux (Alpha)
- Add metainfo for linux
- Fix RPM build

[FEAT] Auth goodies for linux

---

auth/docs/adding-icons.md

Some contributors are submitting unoptimized/huge PNG/JPG icons encapsulated in SVG, resulting in an unnecessary increase in the size of installation packages, as well as increased memory consumption and bandwidth when users use these icons.
Icon matching instructions are based on function:
https://github.com/ente-io/ente/blob/30dd41e3cae11ed7d1eeccf8e5f99c671e3f863a/auth/lib/ui/utils/icon_utils.dart#L147

Warning about icon sizes and instructions on matching the icon to the issuer.

---

auth/linux/packaging/appimage/make_config.yaml
auth/linux/packaging/deb/make_config.yaml
auth/linux/packaging/pacman/make_config.yaml
auth/linux/packaging/rpm/make_config.yaml
auth/pubspec.yaml

- Bundle Metainfo
- Bump version

[FIX] Bundle Metainfo and Bump version

---

.github/workflows/auth-release.yml
auth/pubspec.yaml

- Only Build pacman for beta releases
- Fix dependencies
- Bump version

[FIX(auth)] Run pacman build on beta, fix deps

---

auth/lib/core/win_http_client.dart

[auth] Update logs

---

.github/workflows/auth-release.yml
auth/linux/packaging/pacman/make_config.yaml

[FIX(auth)] also move the pacman build to artifacts

---

mobile/lib/core/error-reporting/super_logging.dart
mobile/lib/db/files_db.dart
mobile/lib/services/machine_learning/face_ml/face_ml_service.dart
mobile/lib/services/machine_learning/face_ml/feedback/cluster_feedback.dart
mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart
mobile/pubspec.yaml

[photos] Fix minor errors + remove noise from sentry

---

infra/staff/package.json
infra/staff/src/App.css
infra/staff/src/App.tsx
infra/staff/src/components/Sidebar.tsx
infra/staff/src/components/UpdateSubscription.tsx
infra/staff/yarn.lock

Added options for Delete Account and Update Subscription in the dashboard, Clicking on Update Subscription option opens a popup window for taking user input

Dashboard improvement

---

mobile/lib/generated/intl/messages_de.dart
mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/intl/messages_es.dart
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_en.arb
mobile/lib/models/gallery_type.dart
mobile/lib/ui/viewer/actions/file_selection_actions_widget.dart

[mob] Fix `Send link` option position for person and unamed group

---

web/apps/photos/src/services/upload/uploadManager.ts

The previous fix did not help the user: https://discord.com/channels/948937918347608085/1253299055472410645
But I've also been unable to reproduce this on Linux too. Modifying this code to just log (so that we can better understand before adding ad-hoc workarounds).

[desktop] Add logging to help trace memory pressure issues

---

mobile/lib/events/favorites_service_init_complete_event.dart
mobile/lib/services/favorites_service.dart
mobile/lib/ui/tabs/user_collections_tab.dart

Quite possible the on ente section is built before favorites service is finished initialising which is causing this issue. Reloading after init is complete should fix this bug
Tested and working fine.

[mob][photos] Fix: Intermittent disappearance of favorite album on 'On Ente' section.

---

mobile/lib/l10n/intl_de.arb

[mob][photos] Fix german translation

---

mobile/lib/core/configuration.dart

[mob] Avoid FileUploader cache clear in case of autoLogout

---

desktop/src/main/services/ml-clip.ts

Fixed issues with the old clip preprocessing.
Not tested, but confident it's correct. Should compare embeddings between platforms after all web changes are done.

[web][photos] Correct clip preprocessing

---

desktop/src/main/services/ml-clip.ts

Ref: https://github.com/ente-io/ente/pull/2342

[desktop] Fix CI lint errors

---

web/apps/accounts/src/services/passkey.ts
web/packages/accounts/services/passkey.ts
web/packages/accounts/services/session.ts
web/packages/new/photos/components/DevSettings.tsx
web/packages/new/photos/services/feature-flags.ts
web/packages/new/photos/services/ml/embedding.ts
web/packages/new/photos/services/ml/worker.ts
web/packages/next/http.ts
web/packages/next/log.ts

Also continue processing the liveQ even if embeddings pull fails.

[desktop] Consider HTTP 4xx errors when PUT-ing embeddings as perm failures

---

desktop/src/main/services/ml-clip.ts
web/packages/new/photos/services/ml/image.ts
web/packages/utils/ensure.ts

Fix format mismatch (ref: https://github.com/ente-io/ente/pull/2342)

[desktop] Fix CLIP preprocessing

---

mobile/pubspec.yaml

bump up to v0.9.6

---

auth/assets/custom-icons/_data/custom-icons.json

[auth] Fix json

---

web/apps/accounts/src/services/passkey.ts

This restores the workaround I'd removed in 4d84e966b0298a92de895c4dedc3390d8fda7387.
listItem.transports = ["usb", "nfc", "ble", "internal"];
- This PR should fix the passkey verification on Safari: https://github.com/ente-io/ente/issues/2406
- Sibling PR that fixes the passkey registration: https://github.com/ente-io/ente/pull/2429

[accounts] Restore the passkey workaround for Safari

---

docs/docs/photos/faq/security-and-privacy.md
docs/docs/self-hosting/guides/custom-server/index.md

[docs] Mark the desktop custom server option as released

---

web/apps/photos/src/pages/gallery/index.tsx
web/packages/new/photos/components/WhatsNew.tsx
web/packages/new/photos/services/changelog.ts
web/packages/shared/themes/mui-theme.d.ts
web/packages/shared/themes/typography.ts

[desktop] Don't show what's new on fresh installs

---

desktop/package.json
desktop/yarn.lock

Notable:
- Electron 30.2.0
https://github.com/electron/electron/releases

[desktop] Update deps

---

desktop/src/main.ts

Ref: https://github.com/electron/electron/issues/22048

[desktop] Graceful shutdown in dev mode

---

desktop/CHANGELOG.md
web/apps/photos/src/components/Sidebar/Preferences.tsx
web/packages/next/i18n.ts

A big hats off to the person who did 0-99% 🇵🇱 over the weekend!

[web] [desktop] Enable Polish translations

---

mobile/lib/generated/intl/messages_pl.dart
mobile/lib/models/ffmpeg/ffprobe_props.dart
mobile/lib/ui/viewer/file/file_details_widget.dart
mobile/lib/ui/viewer/file/file_widget.dart
mobile/lib/ui/viewer/file/video_exif_dialog.dart
mobile/lib/utils/exif_util.dart
mobile/lib/utils/ffprobe_util.dart
mobile/lib/utils/file_uploader_util.dart
mobile/pubspec.yaml

[mob] Use video probe data for getting location during upload

---

auth/lib/ui/settings/data/import_page.dart

fix(auth/import): remove cross button from import page

---

mobile/lib/l10n/intl_pl.arb
mobile/lib/l10n/l10n.dart
mobile/lib/ui/settings/language_picker.dart

[mob] Enable polish language

---

mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_en.arb
mobile/lib/ui/viewer/file/video_exif_dialog.dart
mobile/lib/ui/viewer/file_details/video_exif_item.dart

[mob] Minor UX improvement

---

mobile/lib/ui/viewer/file/file_bottom_bar.dart
mobile/pubspec.yaml

[mob] Panorama state fix

---

mobile/lib/ui/viewer/file/file_bottom_bar.dart
mobile/pubspec.yaml

[mob] Disable panorama for external users

---

web/packages/new/photos/services/ml/embedding.ts

Just in case someone goes out of their way to build from source, enable the WIP dev flag and upload WIP embeddings.

[desktop] Change name of model to disallow even WIP uploads

---

mobile/pubspec.yaml

[mob] bump version: 0.9.14+914

---

server/cmd/museum/main.go
server/ente/embedding.go
server/pkg/api/embedding.go
server/pkg/controller/embedding/controller.go
server/pkg/repo/embedding/repository.go

Planning to consume this API on mobile to fetch already indexed files 
Tested locally

[server] Add API to return indexed files for given model

---

server/pkg/repo/embedding/repository.go

[server] Use regular go context in repo

---

docs/docs/photos/troubleshooting/thumbnails.md
web/apps/photos/src/services/upload/uploadService.ts

Ref:
- https://github.com/ente-io/ente/issues/2189#issuecomment-2184095189
- https://discord.com/channels/948937918347608085/1254116633237127198

[docs] Document the Google Takeout Intel macOS video thumbnail scenario

---

mobile/lib/services/machine_learning/file_ml/remote_fileml_service.dart
mobile/lib/utils/gzip.dart

[mob] Simplify APIs for compress -> encrypt  & vice versa

---

desktop/src/main.ts

It seems that Backblaze returns `null` as the ACAO response if the scheme is not http(s), even if we have set allowedOrigins to "*". The desktop app has a custom scheme, "ente://app", which is thus causing B2 to return null.
curl -v -X OPTIONS -H 'Origin: http://example.org' -H 'Access-Control-Request-Method: PUT' 'https://xxx.s3.eu-central-003.backblazeb2.com/yyy'
curl -v -X OPTIONS -H 'Origin: ente://example.org' -H 'Access-Control-Request-Method: PUT' 'https://xxx.s3.eu-central-003.backblazeb2.com/yyy'
Ref: https://github.com/ente-io/ente/discussions/2461#discussioncomment-10125881

[desktop] Fix desktop app direct uploads when self-hosting

---

desktop/src/main.ts

Updates 79fcf18f628b934fdfd1cbc6cd356545566cd85b

[desktop] Further clarify the comment

---

server/pkg/controller/file.go

[server] Temporarily disable fetch from Wasabi

---

server/ente/userentity/entity.go
server/pkg/controller/file.go

[server] Make linter happy and new entityType: person_v2

---

web/packages/new/photos/services/ml/worker.ts

Continuation of https://github.com/ente-io/ente/pull/2574.

[web] Minor tweak for the indexer

---

docs/docs/photos/faq/subscription.md

Update pricing faq

---

server/pkg/controller/family/family.go

[server] Fix typo

---

server/pkg/api/collection.go
server/pkg/middleware/access_token.go

[server] Change default link expiry to never

---

server/cmd/museum/main.go
server/ente/admin.go
server/pkg/api/admin.go
server/pkg/api/collection.go
server/pkg/controller/storagebonus/referral.go
server/pkg/middleware/access_token.go
server/pkg/repo/storagebonus/referral_codes.go
server/pkg/utils/random/generate.go

[server] Add API to update referral code

---

server/pkg/utils/config/config.go

For https://github.com/ente-io/ente/discussions/2603

allow setting extra parameter for dsn

---

server/configurations/local.yaml

Ref: https://github.com/ente-io/ente/pull/2607

[server] Mention extra in docs

---

web/apps/cast/src/types/file/index.ts
web/apps/cast/src/types/magicMetadata/index.ts
web/apps/photos/src/components/Collections/CollectionOptions/index.tsx
web/apps/photos/src/services/collectionService.ts
web/apps/photos/src/services/fileService.ts
web/apps/photos/src/types/collection/index.ts
web/apps/photos/src/utils/collection/index.ts
web/apps/photos/src/utils/file/index.ts
web/apps/photos/src/utils/magicMetadata/index.ts
web/packages/media/file-metadata.ts
web/packages/media/file-type.ts
web/packages/new/photos/types/file.ts
web/packages/new/photos/types/magicMetadata.ts

This is mostly prep, no (major) changes to the functional codepaths yet.

[web] Magic metadata related refactoring

---

auth/android/app/src/main/play/listings/en-US/full_description.txt
auth/fastlane/metadata/android/en-US/full_description.txt
auth/lib/core/constants.dart
auth/lib/l10n/arb/app_en.arb
auth/lib/ui/account/login_pwd_verification_page.dart
auth/lib/ui/account/password_reentry_page.dart
auth/lib/ui/code_error_widget.dart
auth/lib/ui/common/report_bug.dart
auth/lib/ui/settings/data/import/aegis_import.dart
auth/lib/ui/settings/data/import/bitwarden_import.dart
auth/lib/ui/settings/data/import/encrypted_ente_import.dart
auth/lib/ui/settings/data/import/lastpass_import.dart
auth/lib/ui/settings/data/import/plain_text_import.dart
auth/lib/ui/settings/data/import/raivo_plain_text_import.dart
auth/lib/ui/settings/data/import/two_fas_import.dart
auth/lib/ui/settings/support_section_widget.dart
auth/lib/ui/two_factor_recovery_page.dart
auth/lib/utils/dialog_util.dart
auth/lib/utils/email_util.dart
auth/linux/packaging/deb/make_config.yaml
auth/linux/packaging/ente_auth.appdata.xml
auth/linux/packaging/pacman/make_config.yaml
auth/linux/packaging/rpm/make_config.yaml

[auth] redirect support issues to github discussion

---

docs/docs/auth/migration-guides/authy/index.md

Link separate by hyphen for scrolling through intended section title.

docs: section links Method

---

web/apps/auth/public/_headers
web/apps/photos/public/_headers
web/packages/base/components/Head.tsx

Ref: https://web.dev/articles/referrer-best-practices

[web] Fix referrer policy

---

web/docs/dependencies.md
web/packages/base/id-worker.ts
web/packages/base/id.ts
web/packages/base/package.json
web/packages/new/photos/services/ml/cluster-new.ts
web/packages/new/photos/services/ml/db.ts
web/packages/new/photos/services/ml/index.ts
web/yarn.lock

- No functional changes
- Also add nanoid dep

[desktop] Cluster - Initial steps

---

server/pkg/controller/filedata/replicate.go
server/pkg/repo/filedata/repository.go

[server] Minor fixes

---

server/configurations/local.yaml
server/pkg/repo/object_cleanup.go

[server] Fix multi part get url

---

auth/assets/custom-icons/_data/custom-icons.json

Fix Booking.com and Blockchain.com icons loading issue

[Auth] fix Booking and Blockchain icons

---

server/pkg/controller/filedata/replicate.go
server/pkg/repo/object_copies.go

Fix query bug

---

auth/lib/utils/lock_screen_settings.dart
auth/pubspec.yaml

[auth] don't use privacy screen for desktop

---

web/apps/cast/src/services/render.ts
web/apps/photos/src/components/PhotoViewer/FileInfo/index.tsx
web/apps/photos/src/components/pages/gallery/Avatar.tsx
web/packages/media/file-metadata.ts
web/packages/new/photos/services/exif-update.ts
web/packages/new/photos/types/file.ts
web/packages/new/photos/utils/file.ts

Also, gracefully handle a missing modification time and public magic metadata.

[web] Remove the potentially confusing modification time from UI

---

server/pkg/middleware/request_logger.go

[server] Skip logging large payloads on successful requests

---

web/apps/photos/src/components/Collections/AllCollections/index.tsx
web/apps/photos/src/components/Collections/CollectionSelector/index.tsx

Fixes bug introduced in 1c0261bc5ce452fafd7a3004f9be596bc0fae8d8

[web] Fix width of all albums dialog

---

mobile/lib/main.dart
mobile/lib/ui/home/home_bottom_nav_bar.dart
mobile/lib/ui/viewer/file/detail_page.dart
mobile/lib/ui/viewer/file/file_bottom_bar.dart
mobile/lib/ui/viewer/file/video_widget_native.dart
mobile/lib/ui/viewer/search/search_widget.dart

- Snapping when tapping to remove controls + app and bottom bar from a photo or video is no more. 
- System navigation bar has been change to be transparent.
- On iOS, nothing changes visually. 
https://github.com/user-attachments/assets/4665ec52-31d8-4cab-8ca1-d830579c0f60
https://github.com/user-attachments/assets/95adf062-260a-4b23-810f-550c83c2e562
https://github.com/user-attachments/assets/75307e63-df21-490b-ab6f-ef7c4de66c06
https://github.com/user-attachments/assets/83f89387-7fc2-41c3-a55a-3b2d62ef5bfb

[mob][photos] Fullscreen UX improvements

---

server/pkg/middleware/auth.go

[server] Send 5xx if query to validate token fails

---

mobile/android/app/build.gradle

No behavioural changes added in API level 34 
https://developer.android.com/reference/android/os/Build.VERSION_CODES#VANILLA_ICE_CREAM
https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd#.fo6h6k65r
Looks safe to update without testing.

[mob][photos] Update android target SDK

---

cli/internal/promt.go

[cli] Fix temp file deletion on windows

---

server/ente/base/id.go
server/ente/userentity/entity.go
server/go.mod
server/go.sum
server/migrations/90_use_string_id_entity.down.sql
server/migrations/90_use_string_id_entity.up.sql
server/pkg/api/userentity.go
server/pkg/controller/userentity/controller.go
server/pkg/repo/userentity/data.go

Tested locally that new location tag were getting created, and we are able to delete or edit existing tag.

[server] Switch to nano_id for entity_data

---

server/ente/remotestore.go
server/pkg/controller/remotestore/controller.go

[server] Enable multi-part upload flag for mobile

---

web/apps/photos/src/services/logout.ts
web/packages/accounts/services/logout.ts

Helps in tracing event sequences in logs.

[web] Log during logout

---

web/apps/photos/src/services/searchService.ts
web/packages/new/photos/services/ml/cluster-new.ts
web/packages/new/photos/services/ml/db.ts
web/packages/new/photos/services/ml/index.ts
web/packages/new/photos/services/ml/worker.ts
web/packages/new/photos/services/search.ts
web/packages/new/photos/services/user-entity.ts

https://github.com/ente-io/ente/pull/2718

[desktop] person => cgroup

---

auth/lib/core/configuration.dart
auth/pubspec.yaml

[auth] Improve recovery input validation

---

README.md
auth/lib/ui/settings/social_section_widget.dart
mobile/lib/ui/settings/social_section_widget.dart

Changed the links in the social section and readme to Fosstodon instead of mstdn

Updated Mastodon links

---

web/apps/photos/src/components/Sidebar/Preferences.tsx
web/apps/photos/src/components/WatchFolder.tsx
web/apps/photos/src/services/searchService.ts
web/packages/new/photos/services/ml/db.ts
web/packages/new/photos/services/ml/index.ts
web/packages/new/photos/services/ml/worker.ts

- **Disable all clustering traces**
- **Fix variable capturing**
- **Show the delete options for long folder names too**
- **Show ML option to public beta**
- **Rename DBs**

[desktop] Prep for release

---

mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/intl/messages_es.dart
mobile/lib/generated/intl/messages_fr.dart
mobile/lib/generated/intl/messages_it.dart
mobile/lib/generated/intl/messages_nl.dart
mobile/lib/generated/intl/messages_pl.dart
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_ru.dart
mobile/lib/generated/intl/messages_tr.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_en.arb
mobile/lib/l10n/intl_es.arb
mobile/lib/l10n/intl_fr.arb
mobile/lib/l10n/intl_it.arb
mobile/lib/l10n/intl_nl.arb
mobile/lib/l10n/intl_pl.arb
mobile/lib/l10n/intl_pt.arb
mobile/lib/l10n/intl_ru.arb
mobile/lib/l10n/intl_tr.arb
mobile/lib/l10n/intl_zh.arb
mobile/lib/services/update_service.dart
mobile/lib/ui/notification/update/change_log_page.dart

[mob] Change log

---

server/pkg/middleware/request_logger.go

[server] Fix skip log check

---

server/ente/errors.go
server/pkg/repo/passkey/passkey.go

[server] Fix statusCode for expired sessions

---

mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart

[mob] Defer clip cache referesh untill next query

---

desktop/package.json

Completes the accidentally leftover package.json update in b202ac0b5e865cde5b4ce8f6a2777f725d903bcc

photosd-v1.7.3

---

.github/workflows/auth-lint.yml
.github/workflows/auth-release.yml

Update auth github workflows to use flutter 3.24.0

---

server/cmd/museum/main.go
server/ente/storagebonus/referral.go
server/pkg/api/admin.go
server/pkg/api/storage_bonus.go
server/pkg/controller/storagebonus/referral.go
server/pkg/repo/storagebonus/referral_codes.go
server/pkg/repo/storagebonus/referral_codes_test.go

Referal api

---

mobile/lib/gateways/storage_bonus_gw.dart
mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_en.arb
mobile/lib/ui/growth/referral_code_widget.dart
mobile/lib/ui/growth/referral_screen.dart

Add option to claim a custom referral code

---

mobile/lib/db/ml/db.dart
mobile/lib/services/machine_learning/ml_service.dart
mobile/lib/utils/image_ml_util.dart
mobile/pubspec.lock
mobile/pubspec.yaml

- Converts heic files to jpg on Android if heic decoding for ML fails

Heic decode

---

mobile/lib/ui/settings/machine_learning_settings_page.dart

[mob] Disable global ml flag

---

mobile/pubspec.yaml

[mob] Bump version v0.9.24

---

mobile/lib/models/ml/face/person.dart

[mob][photos] Fix person cover photo

---

auth/lib/locale.dart
auth/lib/ui/settings/language_picker.dart

[auth][l10n] Added Ukrainian translation

---

mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_en.arb
mobile/lib/ui/growth/referral_code_widget.dart
mobile/lib/ui/growth/referral_screen.dart

Prompt family members to contact admin to change referral code

---

mobile/ios/Podfile.lock
mobile/lib/services/filedata/model/response.dart
mobile/lib/services/machine_learning/face_ml/face_detection/face_detection_service.dart
mobile/lib/services/machine_learning/face_ml/face_embedding/face_embedding_service.dart
mobile/lib/services/machine_learning/ml_service.dart
mobile/lib/services/machine_learning/semantic_search/clip/clip_image_encoder.dart
mobile/lib/services/machine_learning/semantic_search/clip/clip_text_encoder.dart
mobile/pubspec.lock
mobile/pubspec.yaml

[mob] Release tensors to avoid OOM error

---

mobile/android/app/build.gradle

[mob] Fix android build

---

mobile/android/app/build.gradle
mobile/pubspec.lock
mobile/pubspec.yaml

[mob] Revert to custom onnxruntime fork

---

server/pkg/utils/email/email.go

[server] Return 400 on invalid RCPT address

---

mobile/lib/utils/image_ml_util.dart

[mob][photos] Use bilinear interpolation for clip

---

server/pkg/utils/email/email.go

[server] Handle invalid domain err

---

mobile/lib/models/gallery_type.dart
mobile/lib/services/machine_learning/face_ml/face_clustering/face_clustering_service.dart

[mob] Fix remove from cluster & provide option to delete files from cluster view

---

auth/lib/models/code.dart
auth/lib/services/user_service.dart
auth/lib/ui/settings/data/import/aegis_import.dart
auth/lib/ui/settings/data/import/two_fas_import.dart

[auth] Fix import errors

---

server/cmd/museum/main.go
server/ente/admin.go
server/pkg/api/admin.go
server/pkg/controller/user/userauth.go
server/pkg/utils/email/email.go

[server] Added APIs for ops

---

server/pkg/controller/filedata/controller.go

[server] Log slow files data put requests

---

server/pkg/controller/file.go

This fixes the 5xx alert for file/info endpoint due to panic
Verified that lint works fine locally
PS: This endpoint is used by mobile to backfill file size information, which is primarily used for dedupe and sort by size feature,.

[server] Handle case where fileInfo is missing

---

server/configurations/local.yaml
server/pkg/middleware/auth.go
server/pkg/repo/userauth.go

[server] Treat firstUser as admin if admins config is empty

---

docs/docs/self-hosting/faq/index.md
docs/docs/self-hosting/guides/admin.md

https://github.com/ente-io/ente/pull/2869/

[docs] Document first user as admin

---

web/yarn.lock

Leftover bit of https://github.com/ente-io/ente/pull/2849

[web] Update yarn.lock

---

mobile/lib/services/machine_learning/face_ml/face_clustering/face_clustering_service.dart

[mob][photos] Type error

---

mobile/lib/generated/intl/messages_cs.dart
mobile/lib/generated/intl/messages_de.dart
mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/intl/messages_es.dart
mobile/lib/generated/intl/messages_fr.dart
mobile/lib/generated/intl/messages_it.dart
mobile/lib/generated/intl/messages_ko.dart
mobile/lib/generated/intl/messages_nl.dart
mobile/lib/generated/intl/messages_no.dart
mobile/lib/generated/intl/messages_pl.dart
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_ru.dart
mobile/lib/generated/intl/messages_tr.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_cs.arb
mobile/lib/l10n/intl_de.arb
mobile/lib/l10n/intl_en.arb
mobile/lib/l10n/intl_es.arb
mobile/lib/l10n/intl_fr.arb
mobile/lib/l10n/intl_it.arb
mobile/lib/l10n/intl_ko.arb
mobile/lib/l10n/intl_nl.arb
mobile/lib/l10n/intl_no.arb
mobile/lib/l10n/intl_pl.arb
mobile/lib/l10n/intl_pt.arb
mobile/lib/l10n/intl_ru.arb
mobile/lib/l10n/intl_tr.arb
mobile/lib/l10n/intl_zh.arb
mobile/lib/ui/settings/security_section_widget.dart

[mob][photos] Request authentication to view passkeys

---

web/apps/photos/src/components/PhotoViewer/ImageEditorOverlay/TransformMenu.tsx

This PR changes the rotation of the vertical mirror icon to be rotated by 90deg
It's German but should show the fix

[web][photos] Fix vertical mirror icon

---

desktop/docs/dependencies.md

Fixes https://github.com/ente-io/ente/issues/2884

[desktop] Fix link in dependencies docs

---

server/go.mod
server/pkg/controller/storagebonus/referral.go

Checks if the code contains profanity

Update referral.go to check for profanity in code

---

server/pkg/repo/passkey/passkey.go

[server] Treat invalid attestation resp as badRequest

---

auth/ios/Podfile.lock
auth/lib/onboarding/view/common/tag_chip.dart
auth/lib/ui/account/recovery_key_page.dart
auth/lib/ui/code_widget.dart
auth/lib/ui/home/speed_dial_label_widget.dart
auth/lib/ui/home_page.dart
auth/macos/Flutter/GeneratedPluginRegistrant.swift
auth/pubspec.lock
auth/pubspec.yaml

On max scaling none of the codes were visible, this PR fixes that. Along with that It also makes tags and Speed Dial's text at constant scale to avoid overflow.

[auth] fix scaling of text in code widget, etc

---

server/go.mod
server/go.sum

[server] Fix go-away version

---

server/go.mod

[server] Fix go mod

---

auth/assets/custom-icons/_data/custom-icons.json
auth/assets/custom-icons/icons/bethesda.svg

[auth] Add Bethesda Softworks icon

---

mobile/lib/generated/intl/messages_de.dart
mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/intl/messages_es.dart
mobile/lib/generated/intl/messages_fr.dart
mobile/lib/generated/intl/messages_it.dart
mobile/lib/generated/intl/messages_nl.dart
mobile/lib/generated/intl/messages_pl.dart
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_ru.dart
mobile/lib/generated/intl/messages_tr.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/main.dart
mobile/lib/services/notification_service.dart
mobile/lib/ui/tabs/home_widget.dart
mobile/pubspec.yaml

[mob] Notification fixes

---

server/pkg/controller/filedata/controller.go

[server] Upload filedata in async manner

---

mobile/lib/services/machine_learning/semantic_search/clip/clip_image_encoder.dart
mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart
mobile/pubspec.lock
mobile/pubspec.yaml

Solve onnx build issue Android

---

mobile/lib/services/machine_learning/ml_service.dart
mobile/lib/utils/image_ml_util.dart

[mob][photos] Log format of decoding error

---

docs/docs/photos/faq/general.md

Not sure if this distinction is relevant anymore, but if needed can retain it too (just saw it when modifying something else).

[docs] Remove stale question about magic search

---

mobile/pubspec.yaml

[mob] Update version v0.9.30

---

desktop/.github/workflows/desktop-release.yml

Fix for https://github.com/ente-io/ente/pull/2965

[desktop] Fix action

---

server/pkg/controller/replication3.go

[server] Log slow replication upload

---

server/cmd/museum/main.go
server/pkg/api/user.go
server/pkg/controller/user/user_details.go

[server] Remove unused endpoint

---

server/cmd/museum/main.go
server/ente/admin.go
server/ente/storagebonus/storge_bonus.go
server/pkg/api/admin.go
server/pkg/controller/offer/offer.go
server/pkg/repo/storagebonus/bf_addon.go

[server] Allow adding bonus storage 

---

server/cmd/museum/main.go
server/ente/cache/user_data_cache.go
server/pkg/controller/user/user_details.go
server/pkg/controller/usercache/controller.go
server/pkg/controller/usercache/count.go
server/pkg/repo/trash.go

This does not handle the case where the server might get multiple request for same user to get the count, and the file count is not cached yet.

[server] Cache count improvement

---

server/pkg/repo/trash.go

[server] Handle case when no entry exists in trash

---

mobile/lib/services/machine_learning/ml_service.dart
mobile/lib/utils/ml_util.dart
mobile/lib/utils/thumbnail_util.dart

More logging regarding download/obtaining file for ML indexing

ML file download logs

---

mobile/crowdin.yml

[mob]Remove dst from crowdin template

---

mobile/crowdin.yml

[mob] Skip exporting untranslated strings for store listing

---

mobile/lib/services/user_service.dart

[mob] Fix lint

---

.github/workflows/mobile-crowdin-sync.yml
mobile/crowdin.yml

[mob] Upgrade crowdin config

---

mobile/crowdin.yml

[mob] Skip untranslated strings

---

mobile/.gitignore
mobile/docs/dev.md
mobile/lib/services/user_service.dart

Nothing worth mentioning really.

Tiny cleanup

---

server/ente/admin.go
server/pkg/controller/filedata/delete.go

[sever] Minor server changes

---

server/ente/admin.go

[server] Minor copy change

---

docs/docs/.vitepress/sidebar.ts
docs/docs/photos/faq/subscription.md
docs/docs/self-hosting/faq/backup.md
docs/docs/self-hosting/guides/admin.md

e.g. https://github.com/ente-io/ente/discussions/3009

[docs] Add a intro to backup FAQ since this question keeps coming up

---

docs/docs/photos/migration/from-google-photos/index.md
docs/docs/self-hosting/faq/backup.md

This is how it looks. It is getting a bit too long, so not 100% satisfied with this.

[docs] Tweaks to the Google import steps

---

.github/workflows/web-lint.yml
desktop/CHANGELOG.md

Also tweak the github action again.

[desktop] Add CHANGELOG entry for Intel macOS fix

---

mobile/lib/ui/collections/album/vertical_list.dart

[mob][photos] fix: creating a new album from hidden section is not hidden by default

---

server/ente/errors.go
server/pkg/api/user.go
server/pkg/controller/user/user_details.go

[server] Gracefully handle deleted users

---

mobile/ios/Podfile.lock
mobile/ios/Runner/AppDelegate.swift
mobile/lib/audio_session_handler.dart
mobile/lib/main.dart

Tested, everything works fine. 
If an audio is playing in the background from a different app and once a video starts playing on ente, the background audio is paused.

[mob][photos] Fix: audio not playing on iOS when in silent mode

---

mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/l10n.dart
mobile/pubspec.yaml

[mob] Bump version v0.9.31

---

docs/docs/.vitepress/sidebar.ts
docs/docs/auth/troubleshooting/windows-login.md

[docs] Add troubleshooting guide for auth

---

desktop/CHANGELOG.md

https://github.com/ente-io/ente/pull/2865

Live photo changelog

---

auth/lib/ui/code_timer_progress.dart
auth/lib/ui/code_widget.dart

See commits
Related to https://github.com/ente-io/ente/issues/3031
Tested locally for happy cases

[auth] Performance improvement to reduce CPU utlization

---

web/apps/photos/src/pages/cluster-debug.tsx
web/packages/new/photos/services/ml/cluster.ts

- Prefer existing clusters when adding
- Add min threshold

[desktop] Clustering WIP - Part x/x

---

mobile/lib/generated/intl/messages_all.dart
mobile/lib/generated/intl/messages_da.dart
mobile/lib/generated/intl/messages_de.dart
mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/intl/messages_es.dart
mobile/lib/generated/intl/messages_fa.dart
mobile/lib/generated/intl/messages_fr.dart
mobile/lib/generated/intl/messages_he.dart
mobile/lib/generated/intl/messages_hi.dart
mobile/lib/generated/intl/messages_id.dart
mobile/lib/generated/intl/messages_it.dart
mobile/lib/generated/intl/messages_nl.dart
mobile/lib/generated/intl/messages_no.dart
mobile/lib/generated/intl/messages_pl.dart
mobile/lib/generated/intl/messages_pt.dart
mobile/lib/generated/intl/messages_ru.dart
mobile/lib/generated/intl/messages_sv.dart
mobile/lib/generated/intl/messages_ta.dart
mobile/lib/generated/intl/messages_th.dart
mobile/lib/generated/intl/messages_tr.dart
mobile/lib/generated/intl/messages_zh.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_en.arb
mobile/lib/l10n/intl_he.arb
mobile/lib/l10n/intl_no.arb
mobile/lib/l10n/intl_sv.arb
mobile/lib/services/remote_sync_service.dart
mobile/lib/ui/home/status_bar_widget.dart
mobile/lib/ui/settings/backup/backup_section_widget.dart

[mob] Minor UX changes for backup status

---

mobile/lib/main.dart
mobile/lib/ui/home/grant_permissions_widget.dart
mobile/lib/ui/home/loading_photos_widget.dart
mobile/lib/utils/email_util.dart

If stuck in some screens like the "Grant permission" and "Loading local photos" screen, there is no way to send logs. 
Now, if a scale gesture is detected in any of these screens, logs can be sent.

[mob][photos] Trigger send logs on scale gesture

---

mobile/lib/generated/intl/messages_zh.dart
mobile/pubspec.yaml

[mob] Bump version v0.9.33

---

server/pkg/repo/authenticator/key.go

Tested locally
Lint also works fine locally.

[server] Gracefully handle auth key exist err

---

auth/android/app/build.gradle

[auth] bump target sdk version

---

mobile/lib/core/error-reporting/isolate_logging.dart
mobile/lib/core/error-reporting/super_logging.dart
mobile/lib/models/base/id.dart
mobile/lib/services/isolate_functions.dart
mobile/lib/services/isolate_service.dart
mobile/lib/services/machine_learning/face_ml/face_clustering/face_clustering_service.dart
mobile/lib/services/machine_learning/face_ml/face_detection/face_detection_postprocessing.dart
mobile/lib/services/machine_learning/face_ml/face_detection/face_detection_service.dart
mobile/lib/services/machine_learning/face_ml/face_embedding/face_embedding_service.dart
mobile/lib/services/machine_learning/face_ml/face_filtering/blur_detection_service.dart
mobile/lib/services/machine_learning/face_ml/face_recognition_service.dart
mobile/lib/services/machine_learning/ml_computer.dart
mobile/lib/services/machine_learning/ml_indexing_isolate.dart
mobile/lib/services/machine_learning/ml_model.dart
mobile/lib/services/machine_learning/ml_service.dart
mobile/lib/services/machine_learning/semantic_search/clip/clip_image_encoder.dart
mobile/lib/services/machine_learning/semantic_search/clip/clip_text_encoder.dart
mobile/lib/services/machine_learning/semantic_search/clip/clip_text_tokenizer.dart
mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart
mobile/lib/ui/settings/ml/ml_user_dev_screen.dart
mobile/lib/utils/image_ml_util.dart
mobile/lib/utils/ml_util.dart
mobile/plugins/onnx_dart/android/src/main/kotlin/io/ente/photos/onnx_dart/OnnxDartPlugin.kt

- Regular logging now shows in user logs
- Cleaned up logging around ML indexing
- Refactored all isolates services into single interface
- Try converting to jpg on all failed decoding for ML on Android
Tested in debug mode on my pixel 8 phone.

Ml logging

---

mobile/lib/services/machine_learning/face_ml/person/person_service.dart
mobile/pubspec.yaml

[mob] Gracefully handle dup mapping

---

mobile/lib/utils/ml_util.dart

Log ML index status, so in future issues we won't have to ask the user.

[mob][photos] Log index status of user

---

desktop/package.json
desktop/src/main/stores/watch.ts
desktop/yarn.lock

Routine updates now that the latest release has been released.

[desktop] Update dependencies

---

auth/macos/Podfile.lock

[auth](macos) update podfile lock

---

mobile/lib/db/upload_locks_db.dart
mobile/lib/module/upload/model/multipart.dart
mobile/lib/module/upload/service/multipart.dart
mobile/lib/utils/file_uploader.dart
mobile/pubspec.lock
mobile/pubspec.yaml

[mob] Upgrade uuid pkg & refactor upload

---

mobile/lib/db/files_db.dart

[mob] Ensure file is not uploaded before deleting localFile

---

mobile/lib/core/error-reporting/super_logging.dart

[mob][photos] Log with .log instead of .txt

---

docs/docs/auth/migration-guides/import.md

[docs] update import.md

---

web/apps/photos/src/services/upload/date.ts
web/apps/photos/tests/upload.test.ts

Prep for adding a new format case.

[web] Cleanup the date parsing code

---

web/apps/photos/src/services/upload/date.ts

Ref: https://github.com/ente-io/ente/discussions/2446#discussioncomment-10580240

[web] Handle the newer signal screenshot filename format

---

mobile/lib/ui/home/grant_permissions_widget.dart
mobile/pubspec.yaml

[mob] Add additional logs & error handling on permission grant screen

---

docs/docs/auth/migration-guides/import.md

Fix typo in docs

---

web/packages/new/photos/services/ml/clip.ts
web/packages/new/photos/services/ml/face.ts
web/packages/new/photos/services/ml/image.ts

Adds antialias to clip image preprocessing
Only tested the mobile implementation which follows exactly the same logic. So review carefully.

[desktop][photos] Use antialias with clip image

---

desktop/CHANGELOG.md
web/apps/photos/src/components/Upload/Uploader.tsx

Ref: https://github.com/ente-io/ente/discussions/2707#discussioncomment-10589669

[web] Directly import into the selected album on drag and drop

---

docs/docs/photos/troubleshooting/thumbnails.md

1.7.4 has been released a week ago with this fixed

[docs] Remove fixed ffmpeg workaround

---

mobile/lib/core/configuration.dart
mobile/lib/main.dart
mobile/lib/ui/tools/lock_screen.dart
mobile/lib/ui/viewer/actions/file_selection_actions_widget.dart
mobile/lib/ui/viewer/file/detail_page.dart
mobile/lib/ui/viewer/file/file_app_bar.dart
mobile/lib/utils/local_settings.dart

This PR introduces a security enhancement that requires authentication when the app is reopened after being closed while in guest view.

[mob][photos] Require Authentication on App Reopen from Guest View

---

mobile/lib/services/magic_cache_service.dart

[mob][photos] Discovery tweaks

---

web/docs/dependencies.md
web/package.json
web/yarn.lock

Ref: https://github.com/JedWatson/react-select/issues/5658

[web] Add workaround for dup emotion used by react-select

---

mobile/lib/generated/intl/messages_en.dart
mobile/lib/generated/l10n.dart
mobile/lib/l10n/intl_en.arb
mobile/lib/ui/home/loading_photos_widget.dart

[mob] Enable local import progress for iOS

---

mobile/pubspec.yaml

[mob] Bump version v0.9.37

---

mobile/lib/l10n/l10n.dart
mobile/lib/ui/settings/language_picker.dart

[mob] Enable l10n for ja

---

auth/lib/onboarding/view/setup_enter_secret_key_page.dart

[auth] Fix duplicate tags entry

---

web/apps/photos/src/pages/gallery.tsx

[web] Continue display of trashed items if mobile search is active

---

web/packages/new/photos/components/PeopleList.tsx
web/packages/new/photos/components/SearchBar.tsx
web/packages/new/photos/services/ml/index.ts
web/packages/new/photos/services/search/types.ts
web/packages/new/photos/services/search/worker.ts

Resuming on the cgroup changes.

[web] Cluster groups - Prep

---

auth/lib/models/code.dart

[auth] Fix: uriEncdoe issuer name

---

server/pkg/controller/billing.go
server/pkg/controller/collection.go
server/pkg/middleware/access_token.go
server/pkg/repo/billing.go

[server] Fix sharing validation

---

web/apps/auth/src/pages/share.tsx

[auth][web] Display shared codes

---

.github/workflows/auth-internal-release.yml

[auth] Add workflow for internal release

---

web/apps/photos/src/components/Upload/UploadTypeSelector.tsx
web/apps/photos/src/components/UserNameInputDialog.tsx
web/apps/photos/src/utils/ui/index.tsx
web/packages/new/photos/components/DevSettings.tsx
web/packages/new/photos/components/FocusVisibleButton.tsx
web/packages/new/photos/components/WhatsNew.tsx
web/packages/shared/components/DialogBox/index.tsx
web/packages/shared/components/DialogBox/types.ts

Fixes https://github.com/ente-io/ente/issues/3227

[web] Autofocus on the delete button on the confirmation dialog

---

web/apps/auth/src/pages/share.tsx

[auth] Minor improvements to the sharing page

---

cli/pkg/remote_to_disk_file.go

Fix exporting of live photos with cli

---

server/pkg/repo/userentity/data.go

[server] Gracefully handle duplicate update req

---

server/pkg/api/public_collection.go

[server] Return 4xx for bad request

---

server/configurations/local.yaml

https://github.com/ente-io/ente/pull/3251

[server] Document the optionality of SMTP auth

---

mobile/lib/models/backup/backup_item_status.dart

[mob] Fix sort order for backup status

---

.github/workflows/auth-internal-release.yml
.github/workflows/auth-lint.yml
.github/workflows/auth-release.yml
.github/workflows/mobile-internal-release.yml
.github/workflows/mobile-lint.yml
.github/workflows/mobile-release.yml
mobile/README.md

[mob][auth] Upgrade flutter v3.24.3

---

auth/lib/onboarding/view/setup_enter_secret_key_page.dart
auth/lib/ui/components/code_selection_actions_widget.dart
auth/lib/ui/share/code_share.dart
auth/pubspec.yaml

[auth] Reduce code sharing duration + minor fixes

---

web/apps/photos/src/services/collectionService.ts
web/apps/photos/src/services/export/index.ts
web/apps/photos/src/services/export/migration.ts
web/apps/photos/src/utils/collection.ts
web/apps/photos/tests/upload.test.ts

Matches the behaviour on mobile.

[web] Show empty albums also

---

server/pkg/controller/storagebonus/referral.go

[server] Remove timelimit for applying referral code
