ente-io/ente

pubspec.lock, pubspec.yaml
Upgrade `file_picker` to fix the issue on Android 13 where the import dialog was not popping up due to permission issues.
This PR also upgrades `flutter_sodium` to use ffi 2.0.0+, as it was causing conflicts while resolving dependencies.
Fixes https://github.com/ente-io/auth/issues/4.
=> Upgrade dependencies

lib/ui/settings/security_section_widget.dart
Not all ROMs may block capturing of screenshots once FLAG_SECURE is set, so update the copy to reflect the same
Fixes #18.
=> Update warning dialog when "Hide from recents" is enabled

lib/ui/tools/app_lock.dart
The crash was happening in the `context.l10n` line in the change_email_dialog.dart. This was because the root MaterialApp created by AppLock wasn't being passed the AppLocalizations object.
Tested:
- Was able to reproduce the crash on iOS simulator (null check assertion)
- After the change, the crash doesn't happen
=> Fix the crash on opening change email dialog

lib/app/view/app.dart
Smoke tested by running the app on iOS simulator
=> Use `AppLocalizations.localizationsDelegates` in other MaterialApp

lib/ui/components/menu_item_widget.dart, lib/ui/settings/theme_switch_widget.dart
Before this, the checkmark aligned to the dropdown indicators. This increases the spacing (to match that of the leading text) to indicate that the checkmark is part of the content.
Modified Figma also.
Before / After
=> Increase trailing margin for the theme picker selection checkmark

ios/Runner/Info.plist
We've submitted the BIS self classification report for the auth app alongwith the photos app. More details: https://github.com/ente-io/photos-app/issues/427
=> Enable the BIS self classification flag

.github/workflows/ci.yml
- Forked the action to upload to Play store (ente-io/upload-google-play)
- Added an extra step in the ci.yaml to build an AAB
- Added an extra step in the ci.yaml to use the upload-google-play action to publish to the play store
Currently it pushes to the internal track, can configure it to push to production too
Tested it here (by running the action after disabling the Github release): https://github.com/ente-io/auth/actions/runs/4031138163
=> Upload to Google Play from GitHub action

lib/utils/auth_util.dart, pubspec.yaml
- intl package has been updated from 1.17.0 to 1.18.0
- local_auth package has been updated from 1.1.5 to 2.1.3 
- Code related to the local_auth package has been updated
With the recent update of the `local_auth` package to version 2.1.3, the `androidAuthStrings` property has been deprecated. Instead, a new property called `authMessages` has been introduced, which expects an Iterable of type AuthMessages as input.
To utilize the `AndroidAuthMessages` class, we need to import platform-specific extensions. [Link](https://github.com/flutter/flutter/issues/102164)
**This pull request addresses the following error.**
```
Resolving dependencies... (18.3s)
Because local_auth >=1.1.0 <2.1.3 depends on intl ^0.17.0 and ente_auth depends on intl ^0.18.0, local_auth
>=1.1.0 <2.1.3 is forbidden.
So, …
```
=> Resolve package version conflict and fix error

lib/onboarding/view/setup_enter_secret_key_page.dart
Issue #193. Obscure the textfield for the secret key
=> Obscure secret key during edit  #193

lib/ui/utils/icon_utils.dart
I sometimes put extra information between parentheses in the title, and I noticed icons weren't loading for these items. So it would load for "Discord" but not "Discord (old account)". 
This is because the title string was only split on dots, so parentheses were included in searched for icons and then prevented the icons from being found. This simple change should fix that.
=> Update _getProviderTitle to also split on parentheses

lib/core/configuration.dart, lib/core/logging/tunneled_transport.dart, lib/l10n/arb/app_en.arb, lib/locale.dart, lib/onboarding/view/view_qr_page.dart, lib/services/preference_service.dart, lib/ui/account/email_entry_page.dart, lib/ui/account/login_page.dart, lib/ui/account/login_pwd_verification_page.dart, lib/ui/account/ott_verification_page.dart, lib/ui/account/password_reentry_page.dart, lib/ui/account/recovery_key_page.dart, lib/ui/account/verify_recovery_page.dart, lib/ui/code_widget.dart, lib/ui/common/dynamic_fab.dart, lib/ui/common/progress_dialog.dart, lib/ui/components/buttons/button_widget.dart, lib/ui/components/captioned_text_widget.dart, lib/ui/components/dialog_widget.dart, lib/ui/components/title_bar_widget.dart, lib/ui/home/coach_mark_widget.dart, lib/ui/scanner_gauth_page.dart, lib/ui/scanner_page.dart, lib/ui/settings/faq.dart, lib/ui/settings/general_section_widget.dart, lib/utils/device_info.dart, lib/utils/email_util.dart
I've implemented #264, and it works as expected. However, on iOS, I'm unable to activate the feature because Apple doesn't allow programmatically exiting an app (See  [StackOverflow Discussion](https://stackoverflow.com/questions/355168/proper-way-to-exit-iphone-application))
PS: I also fixed some require_trailing_commas violations.
- [ X ] ✨ New feature (non-breaking change which adds functionality)
=> feature/264 - Add clipboard minimize

assets/custom-icons/_data/custom-icons.json
Added slugs to a few items where the title contained a space. The icons are currently not showing for those items in the app, adding the slug will probably fix it.
=> Add missing slugs to titles with space

lib/ui/code_widget.dart
Related #294
This method checks for `LocalAuthentication().isDeviceSupported();` before actually triggering device auth.
=> Fix edit/del when device authentication is not supported

lib/l10n/arb/app_en.arb, lib/ui/settings/data/import/bitwarden_import.dart, lib/ui/settings/data/import/import_service.dart, lib/ui/settings/data/import_page.dart
Added: Import from bitwarden functionality
Closes #222
=> Bitwarden import

lib/ui/utils/icon_utils.dart
Fall-back to theme's icon-color when the icon-color is too light or dark. Fixes #403
Logic
1. If RGB values are almost equal (`#000000`, `#0F0F11`,  `#212121`, `#27272A`, `#464949`, `#FFFFFF`)
2. Compute its luminance/brightness (cache this value as it is an expensive task)
3. If its too bright or dark, return theme's icon-color
I've manually set the threshold values for brightness in light-theme to be `0.7` and in dark-theme to be `0.05`
https://github.com/ente-io/auth/assets/53324291/aa1e8413-631d-4039-8c08-f8c4d1856fdb
=> Fix: dark icon hard to see

lib/ui/settings/data/import/bitwarden_import.dart
There are two issues with Bitwarden imports ATM:
1. TOTP secrets in Bitwarden are sometimes saved in a format of `otpauth://[...]` and sometimes in a format of secret only. Ente auth assumes that only the second one is used, which is not true and causes an exception. To make both methods work as excepted, in the code, I'm checking which format is used and create `Code` object accordingly.
2. Sometimes items in Bitwarden exports are not accounts, but rather notes. In that case, the `item` variable in the `_processBitwardenExportFile` method does not contain the `login` attribute, which causes an exception. I've added a check to make sure that the item we're parsing is indeed an account.
It is my first time making something in Dart, so please don't be too harsh about my code :)
=> fix: bitwarden imports

analysis_options.yaml, ios/Podfile.lock, lib/main.dart, pubspec.yaml
Fixes this monstrosity.
On iOS, the colors could still be inverted if the user has opted for a theme different from the system theme, since `LaunchImage` is dynamically provided by iOS
=> Fix privacy screen colors

lib/l10n/arb/app_en.arb, lib/ui/settings/data/import/import_service.dart, lib/ui/settings/data/import/lastpass_import.dart, lib/ui/settings/data/import_page.dart
Added LastPass Authenticator import and tested it on iOS with my import.json file.
=> Add Lastpass Authenticator import

server/README.md
The link to RUNNING.md in /server/README.md was wrong, just fixed it.
N/A
=> docs: Fixed url to RUNNING.md in /server/README.md

auth/docs/localization.md, auth/lib/core/constants.dart, auth/lib/ui/settings/about_section_widget.dart, auth/lib/ui/settings/support_section_widget.dart, desktop/src/utils/menu.ts, mobile/lib/core/constants.dart, mobile/lib/ui/settings/about_section_widget.dart, mobile/lib/ui/settings/support_section_widget.dart, web/apps/auth/src/components/AuthFooter.tsx, web/apps/cast/src/constants/urls.ts, web/packages/shared/constants/urls.ts
The links within the apps still point to the old repositories. This PR updates them to point here instead.
> Thanks to @iAnonymous3000 and @s38b35M5 for pointing this out! 
Meanwhile I've set up redirects from the old repositories. Have done it for
=> Update links to GitHub from within the apps

cli/cmd/authenticator.go, cli/cmd/root.go, cli/pkg/authenticator/decrypt.go
Add a command to decrypt the export from Ente Authenticator. Use the following syntax:
```
./bin/ente auth decrypt in.txt out.txt
```
Planning to deprecate existing cli util [decrypt](https://github.com/ente-io/ente/tree/main/auth/migration-guides/decrypt) once ente cli is released.
Releated https://github.com/ente-io/ente/discussions/669
Tested locally.
=> [cli] Add option to decrypt encrypted export file of Authenticator

.github/workflows/auth-lint.yml, .github/workflows/mobile-lint.yml, .github/workflows/web-lint.yml
Ref:
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
- https://stackoverflow.com/questions/77667104/how-to-make-github-action-trigger-on-push-paths-and-push-tags
- https://github.com/orgs/community/discussions/26273
=> Stop unnecessary lint workflows from running on pushing tags

web/apps/photos/.env.development, web/apps/photos/.env.localhost, web/apps/photos/src/services/userService.ts
This simplifies use cases like https://github.com/ente-io/ente/discussions/685#discussioncomment-8682588. There is one less thing for folks to do if they want to run locally or self-host.
Starting a local museum, then connecting to it from the web app
NEXT_PUBLIC_ENTE_ENDPOINT=http://localhost:8080 yarn dev
And uploading a photo.
=> [web] Disable the Cloudflare upload proxy when connecting to a custom endpoint

cli/README.md
@ua741 We still need to provide at least the major version, and we'll need to remember to update these links when the major version changes.
Ref:
- https://docs.github.com/en/repositories/releasing-projects-on-github/searching-a-repositorys-releases
=> [cli] Use the tag: qualifier to better filter the releases

.github/workflows/auth-lint.yml
Purposely opening this PR against a known bad state to verify that the check catches this issue. And it worked.
Have now rebased the PR of main, to also check that the verification succeeds in a known good state.
=> [auth] Verify that the custom icon JSON is valid as part of lint checks

web/apps/photos/src/components/PhotoFrame.tsx, web/apps/photos/src/components/PhotoList/index.tsx, web/apps/photos/src/pages/gallery/index.tsx, web/apps/photos/src/utils/photoFrame/index.ts, web/packages/shared/time/format.ts
This select-all checkbox was added in https://github.com/ente-io/ente/pull/674. These are some changes to how it looks /cc @vishnukvmd 
- Move the checkbox to the left
- Reduce the size of the checkbox
The diff is bigger than it needs to be because I also had to fix some formatting issues (the prettier rules had changed since work had started on that PR).
Running locally
=> [web] UI tweaks to the select all checkbox

server/cmd/museum/main.go, server/pkg/controller/object.go
- Taking lock at host level to avoid redundant downstream request when multiple host pick same items.
Tested locally.
=> [server] Update freq for removing compliance hold

auth/lib/core/configuration.dart, auth/lib/core/network.dart, auth/lib/events/endpoint_updated_event.dart, auth/lib/gateway/authenticator.dart, auth/lib/l10n/arb/app_en.arb, auth/lib/onboarding/view/onboarding_page.dart, auth/lib/services/authenticator_service.dart, auth/lib/store/user_store.dart, auth/lib/ui/settings/developer_settings_page.dart, auth/lib/ui/settings/developer_settings_widget.dart, auth/lib/ui/settings_page.dart, auth/macos/Runner.xcodeproj/project.pbxproj, auth/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Users can now tap on the onboarding screen **7 times** to bring up a page where they can configure the endpoint the app should be connecting to.
=> [Auth] Allow for configuring a custom server

web/README.md, web/docs/new.md
People often run into issues with `yarn install` because they're using a newer yarn. The situation is generally bad - we don't want to update to Yarn v4 yet because it is marked experimental and is not the default yarn that gets installed by node currently. We could add a `packageManager` field to our package.json, but this will only fail the build with a better (hopefully) error message, and will necessitate the user to `corepack_enable`.
I'm not sure what's the best approach right now to make the initial setup be seamless (I think we're using the approach that works for the maximum of all the alternatives, but I'm not sure). At least, let me add a note about it.
Ref:
* https://github.com/yarnpkg/berry/issues/5912
=> [web] Document the need for yarn classic

.github/workflows/docs-deploy.yml, docs/docs/auth/index.md, docs/docs/de/auth/index.md, docs/docs/photos/troubleshooting/files-not-uploading.md, web/docs/deploy-new.md
Add a GitHub workflow to deploy docs. If this works, will start using this same approach for the other web apps in our repo.
=> [docs] Deploy docs

web/apps/photos/src/components/PhotoList/index.tsx
The issue here was that since the checkbox property would get initialized to an undefined value, React would consider it to be uncontrolled. But later on we'd try to set a value, which'd cause React to complain.
Ref:
- Material-UI: A component is changing the uncontrolled checked state of SwitchBase to be controlled
https://stackoverflow.com/questions/69259429/material-ui-a-component-is-changing-the-uncontrolled-checked-state-of-switchbas
=> [web] Fix a warning about MUI component switch state on using the select all checkbox

server/cmd/museum/main.go, server/pkg/controller/file.go, server/pkg/controller/object.go
Speed up object deletion & slow down metadata scrubbing to reduce noisy errors because of pending deletion.
=> Tweak speed for crons

web/apps/photos/src/components/PhotoList/index.tsx
This flow probably got broken when the select-all-for-a-day functionality got added in https://github.com/ente-io/ente/pull/674 (haven't dug into this, I'm just guessing since that's where this all got touched).
Thank you to @Bramas on our Discord for pointing this out, and also providing the fix: https://github.com/ente-io/ente/compare/main...Bramas:ente:fix-error-on-shared-album
Tested by
---------
Run normal web app on one terminal
NEXT_PUBLIC_ENTE_ENDPOINT=http://localhost:8080 NEXT_PUBLIC_ENTE_ALBUMS_ENDPOINT=http://localhost:3002 yarn dev
Run the albums listener on another port (need to do this since we're running on localhost, and need to bind to a different origin):
NEXT_PUBLIC_ENTE_ENDPOINT=http://localhost:8080 NEXT_PUBLIC_ENTE_ALBUMS_ENDPOINT=http://localhost:3002 yarn …
=> [web] Fix shared albums

server/cmd/museum/main.go, server/pkg/api/collection.go, server/pkg/controller/collection.go, server/pkg/controller/data_cleanup/controller.go, server/pkg/controller/trash.go, server/pkg/repo/collection.go, server/pkg/repo/queue.go
✅ Verified that no API call was made to  DELETE `/collections/v2`
✅ Verified that there's no pending entry in the queue for `TrashCollectionQueue`
✅ Trashed a collections with both `Keep Files` and `Delete Files` option.
=> [server] Remove dead code for Collection Trash V2

.github/workflows/web-preview.yml, web/docs/deploy.md
Preview deployments can be made by manually triggering the "Preview (web)" workflow. You can select the app you want to build (accounts/auth/cast/photos) and the branch to take the code from. The deployment will be available at https://preview.ente.sh.
=> [web] Support preview deployments

.gitattributes
On our Discord @Degos ran into an issue where their uploads to the self hosted docker compose cluster were failing. On debugging, it was found that the line-endings in `server/scripts/compose/minio-provision.sh` were set to CRLF, causing the script to fail when run inside Docker. The minIO buckets never got provisioned, and so the uploads would fail with
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
To fix this, we add a new .gitattributes that enforces the LF for the scripts that run inside Docker. To (perhaps too preemptively) guard against similar issues in other scenarios, turn this on for all shell scripts.
Refs:
- https://stackoverflow.com/questions/29603737/bash-seamlessly-run-scripts-with-crlf-line-endings
- …
=> [server] Fix uploads on self-hosted Docker when running on Windows

docs/docs/self-hosting/guides/index.md
I wrote a small guide to run the server and the web app using docker compose (locally or on a server), with an external S3 storage (which I assume will be a common use-case).
It requires #1065 , or at least this line change: https://github.com/ente-io/ente/pull/1065/files#diff-5a9426639947f5afb92612a4583a5b7d496f9cb6a791db9c29f28ff298282aebR16
=> add guide for self-hosting server + webapp with external S3 storage

docs/docs/self-hosting/guides/external-s3.md, web/packages/next/next.config.base.js, web/packages/shared/logging/web.ts
This was found useful by @Bramas when building a Dockerfile of the web app itself. See https://github.com/ente-io/ente/pull/1065.
Now, the GIT_SHA environment variable can just be undefined if we're not in a git repository, and the code using it deals with that case explicitly.
**Tested by**
Temporarily inverted the isDevBuild flag, then
1. Ran the build normally and verified that the SHA continued to appear in the logs.
2. Ran the build after copying to a standalone folder without an associated git repository and verified that the SHA was skipped without causing the build to fail.
=> [web] Allow running the build outside of a git repository

mobile/lib/ui/viewer/gallery/component/gallery_file_widget.dart
Stack has `clipBehaviour = Clip.hardEdge` by default. This is necessary if content inside the stack is overflowing it's boundary and it has to be clipped. Clipping is expensive so it's worth removing it when it makes sense.
In this case of `GalleryFileWidget`, content doesn't overflow the Stack's boundary so the clip operation can be removed by setting `clipBehaviour = Clip.none`.
=> [photos][mobile] Performance improvement

web/apps/photos/.env.development, web/apps/photos/tests/upload.test.ts
The current approach wasn't working. Not sure what caused it to stop working,
but anyway that was an hacky import, as evidenced by the ungainly warning
webpack would print on `yarn dev`. So instead of taking the path, we just take
the JSON contents directly, sidestepping all that.
**Tested by**
Rerunning the upload tests
=> [web] Fix the upload tests

auth/.gitignore, mobile/.gitignore
The intent had always been to have the individual project gitignores be self contained. In my previous PR (https://github.com/ente-io/ente/pull/516) I'd for some reason not followed this: correcting my mistake now. .vscode is gitignored both at the top level and at the individual project levels (as it was originally).
=> [meta] Reintroduce .vscode in the mobile gitignores

.github/workflows/auth-crowdin.yml, .github/workflows/mobile-crowdin.yml, .github/workflows/web-crowdin.yml, .github/workflows/web-nightly.yml
Every day is too much noise - we really only need this
- When a string gets changed in the source translation, in which case this workflow gets triggered automatically anyway.
- Before we do a new release (this doesn't automatically happen, but the workflow can be triggered manually if needed).
For now, reduce the frequency of the daily job to pull new translations from Crowdin: now it'll only happen on Tuesdays and Fridays (just an arbitrary choice).
=> [meta] Reduce the frequency of the sync translations cron

web/apps/photos/src/components/PhotoList/index.tsx
For now, this at least makes it less obtrusive. Once I have cleaned up the state handling around selection (to better integrate this with the rest of the selection state so that there are no discrepancies), can revisit the UI - e.g. show it only on hover, or reduce the size of the checkbox / give it a rounded look etc to make it look even less obstrusive.
=> [web] Show select-all-for-day checkmark only when there is a selection

web/apps/photos/src/components/PhotoViewer/index.tsx
Fixes: Info button is not working when videos are playing in full screen mode.
**Tested by**
Wasn't working before, but it works now. Still doesn't work with the keybinding,
have left a note about that in the code.
=> [web] Exit fullscreen if needed when pressing the info button

docs/docs/auth/migration-guides/authy/index.md
This fixes note boxes having incorrect titles, like this one:
=> [docs] Note boxes fix

docs/docs/self-hosting/guides/external-s3.md
Someone got confused about this missing instruction in Discord. Have added the submodule step, and also called out that it might be a good idea to also refer to the project READMEs in case this guide in the future drifts out of sync.
=> [docs] Mention submodules in the community external S3 guide

server/configurations/local.yaml, server/pkg/utils/s3config/s3config.go
- Disable the example.org domains in the default self-hosted configuration (saner default)
- Add a new flag to support S3 path style URLs without disabling SSL (needed for folks who want to run minio as their production S3, without disabling SSL)
**Tested by**
Running a local cluster with the following `museum.yaml` and verifying that the path style URLs are kicking in.
```
s3:
use_path_style_urls: true
```
=> [server] Enhancements for self hosters

web/apps/photos/public/locales/en-US/translation.json
Obtained these strings from https://github.com/ente-io/accounts-web/blob/33faadf83ea6c39732ffd185fc4716b006612684/apps/accounts/public/locales/en/translation.json#L632
I didn't have a way of exhaustively ensuring that all strings are covered, but I've tried to manually verify.
Once this is merged and translation files synced with Crowdin, I'll do another PR to update the `local/**/translation.json` files within apps/accounts.
=> [web] Add passkeys related translations

web/yarn.lock
This seems to have been overwritten in a recent PR, perhaps because of a different yarn version being used.
=> [web] Update yarn.lock

.github/workflows/auth-crowdin.yml, .github/workflows/auth-lint.yml, .github/workflows/docs-deploy.yml, .github/workflows/docs-verify-build.yml, .github/workflows/mobile-crowdin.yml, .github/workflows/mobile-lint.yml, .github/workflows/server-lint.yml, .github/workflows/web-crowdin.yml, .github/workflows/web-lint.yml
When we merge main into a deploy/* branch (e.g. https://github.com/ente-io/ente/pull/1147), all changes get pulled in not just the one related to that deployment, and this causes almost all of the path based workflows to run again unnecessarily. Exclude the various "deploy/**" branches to stop these unnecessary workflows from being triggered.
=> [meta] Omit unnecessary reruns of workflows when deploying

infra/workers/github-discord-notifier/src/index.ts, infra/workers/github-discord-notifier/wrangler.toml
**Tested by**
Deployed, and redelivered a few recent messages to see that they're falling back to the fallback.
=> [workers] Fallback to plain text Discord message as a 429 workaround

.github/workflows/auth-crowdin.yml, .github/workflows/mobile-crowdin.yml, .github/workflows/web-crowdin.yml
Don't upload existing translation when syncing with Crowdin. This way, we let the existing translations be invalidated when we change the source string (this was not happening previously since we also upload the (older) translations when
we upload the changed source strings).
**Tested by**
Doing this on a different test branch, changing a source string, manually running the workflow against that branch, and verifying that the strings are getting reset in the PR that Crowdin' action opens.
=> [crowdin] Invalidate existing translations when source strings change

desktop/docs/dependencies.md, desktop/package.json, desktop/yarn.lock, web/packages/next/next.config.base.js
This is my first time in ente! I modified two commands to allow the build scripts for web and desktop to work in a Windows environment.
- Before running the command to get the git SHA in `next.config.js`, I checked the platform of the current OS and changed it so that we could run a command that would work on Windows.
- `NUL` is same as `/dev/null` in Windows, and `cd .` is always return nothing with 0 status code.
- Added a new package called [`shx`](https://[github.com/shelljs/shx](https://github.com/shelljs/shx)) to the development dependencies to support `rm` and `ln`, which are commands not supported by Windows when running the Desktop build command.
#1191 
I've tested the web build and desktop build in a Windows environment. I don't have a Mac, so I'd love for someone to test it on …
=> [web/desktop] Support windows environment on command

web/apps/photos/src/pages/index.tsx, web/packages/accounts/pages/credentials.tsx
Fix an infinite loop of navigation under the following conditions: key is valid
but token is not present.
Fix is to match the condition used in both gallery
if (!key || !token) {
and the root page.
They seemed to have diverged in commit c3304571a907f0d88b664f2d614f2cd443a600fa.
Was able to reproduce this when launching the desktop app such that the key was
picked up (possibly from a prior installation) from the secure keychain, but the
token was not found. I feel this is also a fix for a similar navigation loop
recently reported by QA but unreproducible so far.
=> [web][photos] Fix infinite loop on half-logins

desktop/src/utils/menu.ts, mobile/lib/ui/growth/referral_screen.dart, mobile/lib/ui/settings/account_section_widget.dart, server/mail-templates/mobile_app_first_upload.html, server/mail-templates/subscription_ended.html, server/mail-templates/successful_referral.html, server/mail-templates/web_app_first_upload.html
On desktop, now there Help menu will have an "Ente Help" option instead of "FAQ".
The only place remaining after this is the sidebar on mobile (`support_section_widget.dart`), but I wasn't sure of what string to use (and how to add it to the localized strings for mobile) so I've left it unchanged.
=> Update ente.io/faq => help.ente.io where possible

.github/workflows/server-publish.yml, docs/docs/self-hosting/index.md, server/README.md, server/RUNNING.md, server/docs/docker.md, server/docs/publish.md
Part 2 (and final part) of https://github.com/ente-io/ente/pull/1218.
Completes https://github.com/ente-io/ente/discussions/673. The images are accessible at `ghcr.io/ente-io/server`, e.g.
```sh
docker pull ghcr.io/ente-io/server
```
=> [server] Publish docker image - Part 2/2

mobile/lib/models/subscription.dart, mobile/lib/ui/payment/stripe_subscription_page.dart, server/pkg/controller/stripe.go, web/apps/photos/src/components/Sidebar/SubscriptionStatus/index.tsx, web/apps/photos/src/components/Sidebar/userDetailsSection.tsx, web/apps/photos/src/utils/billing/index.ts
When a customer whose Stripe subscription is past due (within the 30 day window after expiry time and has not been cancelled) clicks on the subscription modal, take them to the payment portal to complete the subscription.
=> [mobile][web] Redirect to payment portal if subscription is past due

infra/workers/github-discord-notifier/src/index.ts
Discord still hasn't fixed the issue on their end, and having a top level link whenever a new comment is added is getting cumbersome, so add a handler for the common comments case too.
Tested and deployed.
=> [meta] Add a special case for comments in the notifier workaround

auth/lib/app/view/app.dart, auth/lib/main.dart, auth/lib/ui/code_widget.dart, auth/macos/Podfile.lock
- Don't hide but close app on exit
- Hide window option
- Fix translation of labels of context menu
=> [FIX] Auth Desk

web/apps/photos/src/components/PhotoViewer/FileInfo/MapBox.tsx
Open the link in a new tab. This prevents the desktop app from getting into a state where the user cannot navigate back.
Tested on the web app and desktop app.
=> [desktop] Prevent the desktop app from getting stuck on viewing openstreetmap info

server/README.md, server/RUNNING.md
From our Discord, someone commented
> if minio's cautions about Single-Node, Single-Drive are to be taken seriously:
>
> "SNSD deployments use a zero-parity erasure coded backend that provides no
added reliability or availability beyond what the underlying storage volume
implements. These deployments are best suited for local testing and
evaluation, or for small-scale data workloads that do not have availability or
performance requirements."
MinIO was never meant as a production replacement, it was only to make it easy
for people to get started. So add a notice in the docs re this.
=> [server] Add a notice that minio is only for getting started

infra/services/nginx/README.md, server/scripts/deploy/README.md, server/scripts/deploy/museum.nginx.conf
- Use keepalives
- Update deprecated http2 syntax
- Document how to check config
Refs:
- https://www.nginx.com/blog/avoiding-top-10-nginx-configuration-mistakes/#no-keepalives
- https://github.com/nginxinc/kubernetes-ingress/issues/4237
- https://stackoverflow.com/questions/65944578/how-to-get-nginx-running-in-docker-to-reload-nginx-conf-configuration
=> [server] nginx configuration improvements

mobile/ios/Podfile.lock, mobile/lib/core/configuration.dart, mobile/lib/core/network/ente_interceptor.dart, mobile/lib/core/network/network.dart, mobile/lib/events/endpoint_updated_event.dart, mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/l10n.dart, mobile/lib/l10n/intl_en.arb, mobile/lib/main.dart, mobile/lib/ui/home/landing_page_widget.dart, mobile/lib/ui/settings/developer_settings_page.dart, mobile/lib/ui/settings/developer_settings_widget.dart, mobile/lib/ui/settings_page.dart
Users can now tap on the onboarding screen 7 times to bring up a page where they can configure the endpoint the app should be connecting to.
=> [Photos] Allow for configuring a custom server

.github/workflows/server-publish.yml
Untested yet, will test alongside the next publish
Requested in https://github.com/ente-io/ente/discussions/1305
=> [server] Build ARM images when publishing to ghcr.io

mobile/lib/generated/intl/messages_cs.dart, mobile/lib/generated/intl/messages_de.dart, mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/intl/messages_es.dart, mobile/lib/generated/intl/messages_fr.dart, mobile/lib/generated/intl/messages_it.dart, mobile/lib/generated/intl/messages_ko.dart, mobile/lib/generated/intl/messages_nl.dart, mobile/lib/generated/intl/messages_no.dart, mobile/lib/generated/intl/messages_pl.dart, mobile/lib/generated/intl/messages_pt.dart, mobile/lib/generated/intl/messages_zh.dart, mobile/lib/generated/l10n.dart, mobile/lib/l10n/intl_cs.arb, mobile/lib/l10n/intl_de.arb, mobile/lib/l10n/intl_en.arb, mobile/lib/l10n/intl_es.arb, mobile/lib/l10n/intl_fr.arb, mobile/lib/l10n/intl_it.arb, mobile/lib/l10n/intl_ko.arb, mobile/lib/l10n/intl_nl.arb, mobile/lib/l10n/intl_no.arb, mobile/lib/l10n/intl_pl.arb, mobile/lib/l10n/intl_pt.arb, mobile/lib/l10n/intl_zh.arb, mobile/lib/ui/sharing/share_collection_page.dart
I thought the "Collect photos" line and the download icon in the share page looked very confusing:
So I changed the icon and copy slightly:
Just a copy change, no tests.
=> [mob] Change share page copy

server/configurations/local.yaml, server/pkg/utils/config/config.go
=> [server] Allow a configurable sslmode

web/apps/photos/package.json, web/yarn.lock
Previously this was coming from react-datepicker that was otherwise unused and thus removed.
Use the same major version as we had previously.
Ref:
https://stackoverflow.com/questions/71037974/module-not-found-error-cant-resolve-date-fns-adddays-in-c-users
=> [web] Add required transitive dependency of MUI datepicker

auth/ios/Podfile.lock, auth/lib/ui/home_page.dart, auth/linux/flutter/generated_plugin_registrant.cc, auth/linux/flutter/generated_plugins.cmake, auth/macos/Flutter/GeneratedPluginRegistrant.swift, auth/windows/flutter/generated_plugin_registrant.cc, auth/windows/flutter/generated_plugins.cmake
https://github.com/ente-io/ente/assets/254676/726e846c-97a2-444e-a9ae-813f09d3c5e1
=> [auth] Prioritise issuer match in search result order

mobile/lib/db/files_db.dart, mobile/pubspec.lock, mobile/pubspec.yaml
Using [sqlite_async](https://pub.dev/packages/sqlite_async) has increased query speed by about 5x and has removed GC logs like:
`Background concurrent copying GC freed 424845(20MB) AllocSpace objects, 183(4932KB) LOS objects, 37% free, 39MB/63MB, paused 144us,44us total 128.048ms`, which has improved performance of the app.
Tried using [sqlite3](https://pub.dev/packages/sqlite3), which reduced query speed by 10x and removed the GC log, but introduced some jank since it blocks the UI. 
Converting the fetched rows to `EnteFile` now runs on an isolate to avoid blocking the UI. 
Did manual testing to see difference in jank.
=> [mobile][photos] Use sqlite async for fetching all files for search

infra/services/nginx/nginx.service
nginx logs to stdout, which is captured by docker and put into a file at `/var/lib/docker/containers/<nginx-cont-id>/<id>-json.log`
By default, the size of this file is unbounded. Add a maximum limit of 1 GB to this.
References:
- https://docs.docker.com/config/containers/logging/local/
- https://stackoverflow.com/questions/31829587/docker-container-logs-taking-all-my-disk-space
=> [infra] Limit the maximum size of the nginx stdout logs

web/apps/photos/src/pages/gallery/index.tsx, web/apps/photos/src/services/embeddingService.ts, web/apps/photos/src/services/machineLearning/machineLearningService.ts, web/apps/photos/src/types/embedding.tsx, web/apps/photos/src/utils/embedding.ts, web/apps/photos/src/utils/machineLearning/mldataMappers.ts
This PR cherry picks Neeraj's ML related changes from the web_face_v2 branch.
Similar to https://github.com/ente-io/ente/pull/1399, this gets us one step closer to integrating ONNX-YOLO with our desktop app. But it is not currently in a usable state (The web app's functionality remains untouched).
=> [web] Import the scaffolding to sync face embeddings from web_face_v2

desktop/electron-builder.yml
Fixes https://github.com/ente-io/ente/issues/1374
A customer reported that the app fails to run on Windows ARM. The error is coming when trying to load ONNX.
ONNX runtime supports Windows ARM, e.g. see
- https://www.jsdelivr.com/package/npm/onnxruntime-node?tab=files&path=bin%2Fnapi-v3%2Fwin32
- https://github.com/microsoft/onnxruntime/issues/18078
The issue then seems to be that we're not actually building for Windows ARM. I'm not sure about this (don't have a Windows ARM machine at hand), but my theory is that since we don't ask Electron Builder to build for win arm64, it doesn't copy the corresponding ONNX binary into the generated bundle.
Other refs:
- https://www.electron.build/cli.html
=> [desktop] Build ARM64 variant of Windows

web/apps/photos/src/services/collectionService.ts, web/docs/dependencies.md, web/package.json, web/packages/build-config/eslintrc-react.js, web/packages/build-config/package.json, web/packages/eslint-config/index.js, web/packages/next/blob-cache.ts, web/packages/shared/network/HTTPService.ts, web/packages/shared/themes/components.ts, web/yarn.lock
Configuration changes taken from the vite starter (react-ts).
From the [vite docs](https://github.com/vitejs/vite-plugin-react-swc?tab=readme-ov-file#consistent-components-exports)
> For React refresh to work correctly, your file should only export React components.
>
> If an incompatible change in exports is found, the module will be invalidated. To make it easier to export simple constants alongside your component the module is only invalidated when their value changes.
While we're not currently using vite for our main apps, it would be worthwhile to write code in a way that a future migration to it is painless if needed.
About the what and the why, the Gatsby docs are illuminating:
https://www.gatsbyjs.com/docs/reference/local-development/fast-refresh/#how-it-works
Some other refs:
- …
=> [web] Add ESLint to enforce HMR how vite likes it

web/packages/shared/components/EnteLogo.tsx, web/yarn.lock
Ran ente.io locally on PC and found a CSS-alignment issue on the `http://localhost:3000/gallery` page.
The alignment issue was found when it was locally hosted and found when '/gallery' was in an empty state. 
The line - "Welcome to" followed by the image of 'ente' was not aligned.
It was fixed by adding the following line `vertical-align: middle;` to the styled component.
> Please find below images showing the off-alignment and the rectified image. 
> Thank you ! to the team for considering
=> [web] Fix CSS alignment issue on gallery page

server/pkg/controller/data_cleanup/controller.go, server/pkg/controller/user/user.go, server/pkg/repo/datacleanup/repository.go
For accounts that were recovered post deletion (within x days), we were not removing the entry from data_cleanup cron.
The data_clean up cron anyways verify that the account is indeed deleted before proceeding with deletion, so it was not causing any harm, but the cron was logging error.
=> [Server] Fix data cleanup pipeline for recovered account

docs/docs/self-hosting/faq/sharing.md, web/apps/photos/.env, web/apps/photos/src/utils/collection/index.ts
When implementing https://github.com/ente-io/ente/pull/1443 it was found that the Photos web app wasnt' using the sharedCollectionUrl prefix that is returned by the server. Instead, it was using NEXT_PUBLIC_ENTE_ALBUMS_ENDPOINT as the baseHost, while mobile client completely rely on the server for returning the correct hostUrl.
**Tested by**
Running against the modified server, and verifying that changes to apps.public-albums were being used.
=> [web] Use the public link origin provided by the server

desktop/src/main.ts, web/apps/payments/README.md, web/apps/payments/src/services/billing-service.ts
Fixes: https://github.com/ente-io/ente/issues/1440
There were two issues:
- It was a backward incompatible change to change the scheme from ente:// to next://. Revert.
- We also need to setup a top level redirect when the user presses back without making any changes to their subscription.
**Tested by**
Running payments app and desktop app locally, and verifying that
=> [desktop] Fix desktop payments redirect

web/apps/photos/src/components/Search/SearchBar/searchInput/index.tsx
Ran into error after clearing search bar of queries by hitting backspace.
>  The error is shown below
> Thank you to the team for considering 
**Error**
**Fix**
Fixed by wrapping the line-causing error around by an `if` block.
=> [web] Fix dev mode error on search input

web/apps/photos/src/components/Search/SearchBar/searchInput/index.tsx
Updates https://github.com/ente-io/ente/pull/1453 so that we also clear the existing state by calling the setFoo methods even when value is falsey.
=> [web] Clear search bar state when value is falsey

mobile/lib/db/files_db.dart, mobile/lib/services/memories_service.dart, mobile/pubspec.lock, mobile/pubspec.yaml
Using both `sqlite_async` and `sqlite3` for querying at the same time was throwing this error:
`error: SqliteException(5): while executing, database is locked, database is locked (code 5)`
So, have used `sqlite_async` everywhere.
=> [mob][photos] Use sqlite_async instead of sqlite3

mobile/lib/services/collections_service.dart, mobile/lib/utils/file_uploader.dart
On server, certain uploads are getting rejected because the upload is being made on a collection that's not owned by the user.
Still looking for the root cause where it's happening, this check during upload ensures that the client is not repeatitively trying to upload the file.
=> [mob] Discard upload to deleted or others collection

mobile/lib/face/model/box.dart, mobile/lib/ui/viewer/file_details/face_widget.dart, mobile/lib/ui/viewer/people/cropped_face_image_view.dart, mobile/lib/ui/viewer/search/result/person_face_widget.dart, mobile/lib/utils/face/face_box_crop.dart, mobile/lib/utils/face/face_util.dart, mobile/lib/utils/image_util.dart
Have written two new methods, `generateImgFaceThumbnails()` and `generateJpgFaceThumbnails()`.
Using `generateJpgFaceThumbnails()` now since it returns `Future<List<Uint8List>>` and is easier to integrate within the code base because the return type remains the same with the older `generateFaceThumbnailsForImage()`
There is performance improvement with `generateImgFaceThumbnails()`, but it's not very significant and it requires changes in codebase to work with it's return type `Future<List<Image>>` (`Image` from the `Image` package). Can consider using it if it feels necessary in future.
If multiple faces are being generated from the same image, the image can be decoded once and passed to `generateImgFaceThumbnails()` or `generateJpgFaceThumbnails()` to avoid repeated decoding of the same …
=> [mob][photos] Generate face crops faster

web/apps/photos/src/services/download/index.ts
See: https://github.com/ente-io/ente/discussions/1449#discussioncomment-9255346
I'm not yet sure what was the case why it was not initialized, hoping to get some logs for the error when initializing the cache to see how we got to this state. But meanwhile, ensure that the code works even without the cache.
=> [web] Allow thumbnail cache to be optional

web/apps/photos/src/components/Collections/CollectionSelector/index.tsx
Search bar component for the ente-web added.
The component for web and mobile responsiveness is shown below.
> Thank you to the team for considering 
Normal screen--
Mobile screen--
=> Add search bar within the Album selection screen #564

web/apps/photos/src/components/Collections/CollectionSelector/index.tsx
This reverts commit 4ed194f397fd4fdf0daf0238f93b08171f3528e5.
@daviddeepan I had to revert your PR unfortunately.
Two main functional issues was:
- When trying to upload files, if I would search something without results, the dialog would just close instantly.
- As a user, I expect to be able to move out of the search bar with escape. However, pressing escape closes the whole dialog, causing the user's drag and dropped or selected files to be lost. This is not specifically a problem with the code added in this commit, however this UX will need to be fixed in some way before introducing the search bar.
One medium issue:
- The dialog box kept changing size when I searched. This is visually jarring.
Other minor issues:
- The input element did not match the look and feel for the rest of the …
=> [web] Revert "search-bar component added"

mobile/lib/db/files_db.dart, mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/l10n.dart, mobile/lib/l10n/intl_en.arb, mobile/lib/models/file/file.dart, mobile/lib/ui/viewer/actions/file_selection_actions_widget.dart, mobile/lib/ui/viewer/file/file_app_bar.dart, mobile/lib/utils/file_download_util.dart, mobile/pubspec.lock, mobile/pubspec.yaml
> Note: If the downloaded item was not owned by the user, but was shared with them, it will get re-uploaded into the user's own account. This is the existing behavior, so have left it untouched. Will wait for customer feedback before updating the implementation to ignore such items.
=> Add an option to download multiple items

desktop/package.json, desktop/src/main.ts, desktop/src/preload.ts, desktop/yarn.lock, web/apps/photos/src/utils/native-stream.ts
Upgrade to Electron 30 to get the streaming request fix we need.
Also add a workaround to get POSIX paths from webUtils on Windows. For the test case, see this [Fiddle](https://gist.github.com/mnvr/91eaca21b0651926565274ee80f10ad5).
=> [desktop] Electron 30

cli/README.md, docs/docs/self-hosting/guides/custom-server/index.md
- Clarify that config.yaml needs to go to CWD
- Add a notice about ente account add (I think it is the second time someone got confused about this)
Maybe we can also print a notice or the help docs when `ente` is run without any arguments (just a thought for future changes)
=> [cli] Documentation improvement

desktop/.github/workflows/desktop-release.yml, desktop/docs/release.md
Also add a convenience script to the [photos-desktop repo](https://github.com/ente-io/photos-desktop/blob/main/.github/trigger-release.sh):
```sh
#!/bin/sh
set -o errexit
version="$1"
if test -z "$version"
then
echo "usage: `basename $0` <version-including-v>"
exit 1
fi
set -o xtrace
cp ../ente/desktop/CHANGELOG.md CHANGELOG.md
cp ../ente/desktop/.github/workflows/desktop-release.yml .github/workflows/
git add CHANGELOG.md .github/workflows/desktop-release.yml
git commit -m "$version"
git push origin main
git tag "$version"
git push origin "$version"
```
=> [desktop] Run the electron builder in the correct path

mobile/lib/utils/file_uploader.dart
https://github.com/ente-io/ente/blob/a5d05decf299aa1677d88a42929d674b9c33d6d3/mobile/lib/utils/photo_manager_util.dart#L8
^passing true here should let the app have `ACCESS_MEDIA_LOCATION` permission. But looks like that isn't working for a small set of users. So, asking for permission explicitly.
=> [mob][photos] Request for ACCESS_MEDIA_LOCATION permission if not granted

mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/intl/messages_nl.dart, mobile/lib/generated/l10n.dart, mobile/lib/ui/actions/collection/collection_sharing_actions.dart
While deleting a hidden collection, if user clicks on `Keep photos`, then we were moving those photos to uncat instead of default hidden collection.
Monkey tested locally
=> [mob] Fix keepPhotos action for hidden albums

web/apps/photos/src/services/download/index.ts, web/apps/photos/src/services/upload/uploadService.ts
Fix an issue (manifesting on Firefox) where the size of an individual chunk we got back from a readable stream was a multiple of `decryptionChunkSize`. Main change in the PR is converting the `if` condition to a `while` loop, rest is refactoring unrelated to the exact issue.
=> [web] Firefox video stream decryption

desktop/src/main.ts
I am able to reproduce this on Ubuntu 24 ARM.
> The SUID sandbox helper binary was found, but is not configured correctly.
See:
- https://github.com/electron/electron/issues/17972
- https://stackoverflow.com/questions/63780918/building-electron-linux-distro-the-suid-sandbox-helper-binary-was-found-but-i
=> [desktop] Add a workaround for the SUID sandbox helper error on Linux

desktop/CHANGELOG.md, desktop/src/main.ts, docs/docs/photos/troubleshooting/desktop-install/index.md
- Revert the workaround
- Document the behaviour I observed
- (Unrelated) Add the other CHANGELOG entries in preparation for the release
=> [desktop] --no-sandbox does not prevent the SUID abort when added from JS

.github/workflows/mobile-internal-release.yml, mobile/pubspec.yaml
`Error: Changes are sent for review automatically. The query parameter changesNotSentForReview must not be set.`
=> Fix failing workflow for photos internal release 

web/apps/photos/src/services/embeddingService.ts
- Do not rely on the server sending back exactly as many entries as we requested, it may return less in case some of the embeddings cannot be fetched temporarily.
- Stop relying on the sort order - Instead of the last value, take the max from amongst all returned values.
/cc @ua741
=> [web] Embeddings diff improvements

desktop/package.json, web/package.json
Latest Node 20 (20.13.1) ships with an updated corepack which seems to insist
putting a package manager field in package.json
(https://github.com/nodejs/corepack/pull/413).
Let it have its way, hoping that this doesn't break someone's workflow
(depending on how they installed yarn without corepack or if they have a node
version that doesn't have corepack).
=> [web] Make corepack happy

desktop/src/main/services/app-update.ts
> disableWebInstaller is set to false, you should set it to true if you do not
plan on using a web installer. This will default to true in a future version.
=> [desktop] Fix warning on windows auto update

docs/docs/self-hosting/troubleshooting/yarn.md, web/README.md, web/docs/README.md, web/docs/new.md
The `npm install -g corepack` was needed on Ubuntu 24 (See https://github.com/yarnpkg/berry/discussions/5060)
=> [web] Add Ubuntu section in getting started docs

desktop/src/main.ts, desktop/src/main/log.ts
This workaround already existed in older versions (See `addAllowOriginHeader`), I had recently removed it, now putting it back.
=> [desktop] Add a CORS workaround for uploads to arbitrary testing buckets

auth/macos/Podfile.lock, auth/pubspec.yaml
=> [auth] Bump Podfile for Sentry Macos

.gitignore
About the auth dbs, discussed in chat: These files got created once when debugging auth build for linux. They were probably accidental, so removing them for now (will add back if there is a workflow when they actively get recreated).
=> [meta] Prune gitignore

web/apps/photos/src/utils/comlink/ComlinkSearchWorker.ts
During app init, two worker instances would get created in some cases and two getInstances raced because of the await. This was causing the search results to be empty until the page is reloaded (since the files array was empty in the worker that got assigned, but the files would get set to the other worker instance that lost the race).
=> [web] Fix race condition in initialization of search worker

auth/lib/models/code.dart, auth/lib/onboarding/view/setup_enter_secret_key_page.dart, auth/lib/utils/totp_util.dart
I don't think I'm the only one using website domains as issuers of TOTP codes. This change will add support for the Steam domain (steampowered.com) as an issuer.
=> Ente Auth: Add support for Steam domain (steampowered.com) as an issuer

desktop/src/main/stream.ts
Fixes the following upload:
> metadata: {title: xxx.jpeg, creationTime: 1715925330480368.8, modificationTime: 1715925330480368.8, latitude: null, longitude: null, fileType: 0, hash: ...}
Related: https://github.com/ente-io/ente/pull/1821
=> [desktop] Keep integral millisecond precision for modified time

web/apps/auth/src/pages/404.tsx, web/apps/photos/src/pages/404.tsx, web/packages/shared/next/pages/404.tsx
Steps to reproduce on Linux:
- Open an album
- Open a photo
- View > Reload
Causes a 404 page to be displayed.
=> [desktop] Allow refreshing when inside an album

docs/docs/auth/migration-guides/steam/index.md
A quick guide on how to use steamguard-cli to generate a Steam 2FA QR code for Ente Auth
Inspired by https://github.com/beemdevelopment/Aegis/wiki/Adding-Steam-to-Aegis-from-steamguard-cli, but updated to utilize the latest flags provide by the steamguard-cli
addresses this: https://github.com/ente-io/ente/discussions/1038#discussioncomment-9520070
=> Steam Authenticator migration guide

web/apps/photos/src/components/Sidebar/index.tsx, web/packages/accounts/services/passkey.ts
@ua741 Not sure if passkey code is supposed to work on web yet, but I was doing an unrelated change and noticed that clicking passkeys didn't even try to redirect to accounts. I don't have a test setup for passkeys, so don't know if these changes are 100% correct, but at least now it redirects to accounts. Can test fully when doing final integration.
- Use correct origin for passkey API requests
- Fix key length error
- Fix param name to match server
- Pass the token instead of a query param
=> [web] Passkey fixes

docs/docs/self-hosting/guides/custom-server/index.md
This PR fixes the spelling of a word, `appps` to `apps`, in the title of a section of the documentation for using a custom server.
=> [docs] Fix typo in custom server documentation

web/apps/auth/src/pages/auth.tsx, web/packages/accounts/api/user.ts
Ref: https://github.com/ente-io/ente/issues/1891
**Tested**
Locally - auth in one window, photos in another, change password in photos, auth shows dialog on page refresh.
=> [web] Invalidate sessions on auth.ente.io on password changes

auth/assets/custom-icons/_data/custom-icons.json
This PR just adds some alternative names that could be used for the services "Bloom Host" and "Techlore".
=> Add alt names for some services

desktop/.github/workflows/desktop-release.yml
Untested, will need to trigger the workflow to see if this works.
=> [desktop] Update published artifacts on the nightly pre-release

web/apps/accounts/.eslintrc.js, web/apps/cast/.eslintrc.js, web/apps/photos/.eslintrc.js, web/packages/eslint-config/.eslintrc.js, web/packages/eslint-config/index.js, web/packages/shared/.eslintrc.js
Pending on https://github.com/facebook/react/pull/28773
Note - once we go eslint 9, we won't need the `--report-unused-disable-directives` in our eslint invocation:
https://eslint.org/docs/latest/use/configure/configuration-files#reporting-unused-disable-directives
=> [web] Investigate ESLint 9 (but don't switch yet)

docs/docs/self-hosting/faq/sharing.md
More improvements suggested by Dylanger in Discord
=> [docs] Self hosting public albums

infra/staff/src/App.tsx
The dashboard now consists of 3 input fields: Server Url, token and email id, the first two gets stored in the local storage when you enter it for the first time and if we reload, the input fields automatically retrieves the values from the local storage. The three inputs help the program to generate the URL http://localhost:8080/admin/user?email=YOUR_EMAIL&token=YOUR_TOKEN and fetch data from the API
=> Dashboard improvement

desktop/CHANGELOG.md, web/apps/photos/src/services/watch.ts
This was a regression introduced in 1.7.0. On deleting a file on disk, the corresponding items are supposed to move to uncategorized.
> And if a file is deleted locally, then the corresponding Ente file will also be automatically moved to uncategorized.
>
> https://help.ente.io/photos/features/watch-folders
=> [photosd] Fix automatic move to uncategorized on watch folder deletions

mobile/lib/ui/viewer/actions/file_selection_actions_widget.dart, mobile/lib/utils/share_util.dart
1. Modified the` _createPlaceholder` function to return the image bytes instead of the image path, changed the return type to `Future<Uint8List?>`
2. Remove the call to `saveImage` on saving the image to a temporary directory
3. Modified the `shareImageAndUrl` function:
4. Replaced the usage of XFile(imagePath) with XFile.fromData(imageBytes).
5. Added metadata to the `XFile.fromData` method call, specifying the name and mimeType for better file identification during sharing.
=> [mob][photos] Modify the code to use XFile.fromData(bytes) instead of saving the image to a file for share link placeholder

server/pkg/utils/billing/billing.go
SEPA in certain instances is taking 10+ days to go through.
=> Increase grace period of Stripe subscriptions to 14 days

auth/lib/services/passkey_service.dart, auth/lib/ui/passkey_page.dart, mobile/lib/services/passkey_service.dart, mobile/lib/ui/account/passkey_page.dart
We now explicitly pass a recover URL to the accounts app, and I've added some placeholder values. This URL will be opened when the user selects the "Recover passkey" option on the authentication failure screen.
=> [mobile] Update passkeys URLs

web/apps/accounts/.eslintrc.js, web/apps/accounts/src/pages/_app.tsx, web/apps/accounts/src/pages/passkeys/index.tsx
Refs: https://legacy.reactjs.org/docs/hooks-reference.html#usestate
> React guarantees that setState function identity is stable and won't change on
rerenders. This is why it's safe to omit from the useEffect or useCallback
dependency list.
=> [web] Passkeys - Fix exhaustive-deps lints

auth/lib/ui/passkey_page.dart, mobile/lib/ui/account/passkey_page.dart
Mobile app shows it on the waiting screen instead (accounts web app shows the recover option only when the recover query param is passed to it).
(Did not verify by running on mobile)
/cc @ua741
=> [mob] Passkeys: Don't show recover option on accounts page

desktop/CHANGELOG.md, desktop/src/main/services/watch.ts
This didn't happen always, it was a race condition dependending on when the `this.eventQueue = []` in `syncWithDisk` happened.
=> [desktop] Fix duplicate file uploads when initializing a folder watch

.github/workflows/server-publish.yml
The code doesn't get tested or run and is likely not safe for 32 bits
> 941.0 pkg/utils/billing/billing.go:117:13: cannot use ente.FreePlanStorage
(untyped int constant 5368709120) as int value in struct literal (overflows)
>
> https://github.com/ente-io/ente/actions/runs/9546167833/job/26308448952
=> [server] Stop making 32 bit ARM images

web/apps/cast/tsconfig.json, web/packages/shared/crypto/internal/libsodium.ts, web/packages/utils/array.ts
The script I used for testing - 10-100x faster, and the faster the longer the arrays. Note that speed was not the primary motivator for this change, I just wanted to enable `noUncheckedIndexedAccess`
```js
//zs = [...Array(10).keys()].map(() => Uint8Array.from(Array(100000).keys()));                                                    
zs = [...Array(100).keys()].map(() => Uint8Array.from(Array(1000).keys()));
const m0 = (as) => new Uint8Array(as.reduce((acc, x) => acc.concat(...x), []));
const mergeUint8Arrays = (as) => {
const len = as.reduce((len, xs) => len + xs.length, 0);
const result = new Uint8Array(len);
as.reduce((n, xs) => (result.set(xs, n), n + xs.length), 0);
return result;
};
s = performance.now();
a = m0(zs);
e = performance.now();
console.log(e - s, "ms", a.length, "m0"); …
```
=> [web] Faster and noUncheckedIndexedAccess compliant Uint8Array merging

web/apps/photos/src/services/upload/uploadManager.ts
Make the logfile more user friendly by adding a readable upload result string instead of just a number.
Before the logfile showed only a not human understandable number for the upload result:
`"Uploaded xyz.jpg with result 3"` 
This PR adds the key from the enum UPLOAD_RESULT to make it easy for a human to understand the result:
`"Uploaded xyz.jpg with result 3 (BLOCKED)"`
=> add human readable upload result to log file output

infra/workers/cast-albums/src/index.ts, infra/workers/files/src/index.ts, infra/workers/public-albums/src/index.ts, infra/workers/thumbnails/src/index.ts, infra/workers/uploader/src/index.ts
- Allow albums.ente.io/sh
- Log on all non-200 responses from upstream
- Use an easier to grep label
=> [worker] Log on all non-200 responses from upstream +1

web/apps/photos/src/components/pages/gallery/PlanSelector/card.tsx
This fixes the issue reported by a user where they cancelled their subscription, then later on tried to upgrade, but were then redirected to the new subscription flow instead of the upgrade flow.
**Tested (on localhost):**
=> [web] Allow user to update subscriptions after cancel

mobile/lib/ui/viewer/file/thumbnail_widget.dart, mobile/lib/ui/viewer/gallery/component/gallery_file_widget.dart, mobile/lib/ui/viewer/people/cropped_face_image_view.dart, mobile/lib/ui/viewer/search/result/person_face_widget.dart
- Show video duration overlay only on galleries
- In all other places, show a centred play button -- showing the overlay on some places wasn't looking good, like memories, when opening a video etc. So have replaced the overlay with a play button, just like before. 
- Pass optional parameter to get Thumbnail without any icons stacked over it.
=> [Mob][Photos] Show video duration only on Gallery

.github/workflows/auth-crowdin-push.yml, .github/workflows/auth-crowdin-sync.yml, .github/workflows/mobile-crowdin-push.yml, .github/workflows/mobile-crowdin-sync.yml, .github/workflows/web-crowdin-push-both.yml, .github/workflows/web-crowdin-sync.yml
1. Sources uploaded anytime the {mobile,auth}/lib/l10n/arb/app_en.arb changes in main.
2. Tuesday morning: Download translations from crowdin.
Step 2 can be done manually by running the workflows, e.g.
gh workflow run auth-crowdin-push.yml
gh workflow run mobile-crowdin-push.yml
=> [meta] Split translation related workflows

auth/lib/ui/home_page.dart
Keyboard didn't pop up when search-field was focused on startup. For more information see this issue: https://github.com/ente-io/ente/issues/279
Created an build for my Android phone.
Outcome was as expected 
"Focus search on app start"  enabled did popped the keyboard out.
"Focus search on app start"  disabled did NOT popped the keyboard out and also didn't focused the search-textfield.
This is my first pull request to any open source project. So feel free to give some feedback!
=> Fix keyboard pop up when autofocus is turned on

.github/workflows/web-deploy-staging.yml
This allows us to temporarily deploy arbitrary branches to staging by pushing to a staging/web branch. Removing that branch reverts to the existing and default behaviour of deploying main.
Untested (need to deploy and trigger)
Refs:
- https://github.com/NLnetLabs/krill/commit/942f6a9fe9b43c2ddcd5adec261964359133d8e0
- https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
- https://stackoverflow.com/questions/57819539/github-actions-how-to-share-a-calculated-value-between-job-steps
=> [web] Deploy to staging from staging/web branch if it exists

.github/workflows/web-deploy-staging.yml
Fix for https://github.com/ente-io/ente/pull/2252
> Error: An error occurred trying to start process '/usr/bin/bash' with working
directory '/home/runner/work/ente/ente/web'. No such file or directory
=> [web] Fix for the staging deployment change

server/configurations/local.yaml, server/pkg/controller/replication3.go
I recently started self hosting an instance of Ente. All went well until I tried to enable replication.
This PR adds an option that allows replication to be enabled without a Cloudflare worker, useful for self hosting.
It doesn't look like there are any automated tests that I can add to, but let me know if I'm wrong. Otherwise, I tested this on my own instance and it's working as expected.
=> [server] Allow replication without Cloudflare worker

server/compose.yaml
The museum container depends on the postgres container being up and the DB being ready to accept connections. To enforce this dependency, we use the healthcheck attribute.
See: https://docs.docker.com/compose/startup-order/
The value of the healthcheck interval was set to 1s since the default (30s) caused each `docker compose up` to require at least 30 seconds on each startup, which was prohibitive. The downside is that the healthchecks continue to run beyond the startup phase too, and for small VMs, this caused a lot of unnecessary CPU usage.
Thankfully, now Docker has a new option for a different healthcheck during the start phase:
> start interval is the time between health checks during the start period. This
option requires Docker Engine version 25.0 or later.
They were added in …
=> [server] Reduce DB healthcheck interval in starter Docker compose template

mobile/lib/db/embeddings_db.dart, mobile/lib/models/embedding.dart, mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart
When a certain image format cannot be decoded, clip will store a local empty result instead of infinitely retrying.
=> Clip fix unusable formats

mobile/lib/core/error-reporting/super_logging.dart
```lib/core/error-reporting/super_logging.dart:20:8: Error: Error when reading 'lib/services/machine_learning/face_ml/face_ml_exceptions.dart': No such file or directory
import "package:photos/services/machine_learning/face_ml/face_ml_exceptions.dart";
^
lib/core/error-reporting/super_logging.dart:239:20: Error: 'CouldNotRetrieveAnyFileData' isn't a type.
if (error is CouldNotRetrieveAnyFileData ||
^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
FAILURE: Build failed with an exception.
=> [mob][photos] Fix build failing

desktop/docs/dependencies.md, desktop/package.json, desktop/src/main/services/logout.ts, desktop/src/main/services/upload.ts, desktop/src/main/services/zip.ts, desktop/src/main/stream.ts, desktop/src/main/utils/temp.ts, desktop/yarn.lock, web/packages/next/types/ipc.ts
This should _significantly_ (hours => seconds) improve the performance of the metadata parsing step during import of large Google Takeout zips, and bring them to par as if the user had drag-and-dropped the unzipped folder instead.
In my monkey tests, it seems that beyond a certain zip size (few GBs), reopening the handle to a stream zip overshadows the time taken to read the individual JSONs. This effect seems to grow very big for big zips to a point where the metadata parsing step takes hours.
But note that I'm only testing this on synthetic exemplars I've created. After merging it'll also need testing on more realistic huge takeout examples.
=> [desktop] Cache the handle to the zip files to improve metadata parsing speed

mobile/lib/ui/viewer/file/file_bottom_bar.dart
When viewing photos/videos and enabling fullscreen (with a tap on scree), the bottom bar wasn't disappearing like it used to. This PR fixes this regression.
=> [mob][photos] Fix file bottom bar not disappearing when in fullscreen

server/pkg/api/user.go
Smoke tested locally. Was also more thoroughly tested as part of https://github.com/ente-io/ente/pull/2230.
=> [server] Return key attributes in the session-validity response

desktop/src/main/stream.ts
This caused the reference counts to not be zero when we'd go to clear the cache in `clearPendingUploads`. 
Bug introduced in the nightly build, but didn't have any negative impact except printing an error in the logs because of the unhandled promise rejection.
Ref: https://github.com/nodejs/node/issues/10871#issuecomment-650150155
=> [desktop] Fix stream.end not always being emitted

desktop/src/main/ipc.ts, desktop/src/main/services/fs.ts, desktop/src/main/services/watch.ts, desktop/src/preload.ts, web/apps/photos/src/components/WatchFolder.tsx, web/apps/photos/src/services/export/index.ts, web/apps/photos/src/services/watch.ts, web/packages/next/types/ipc.ts
- Do an upfront directory listing.
- Avoid JSON parsing (the various LivePhoto functions we were callling were internally doing it), and even when we have to, don't do it twice (I tested, the JSON parsing does have a noticeable impact)
@ua741 Monkey testing shows it to be _*almost_ O(1) compared to the earlier O(n). _*almost_ is with many caveats:
- The recursive ls is still multi-second (takes ~5s for 300k files on my SSD)
- The loop is now almost instantaneous for people who don't have live photos or have already synced, but there is still one JSON parse (in the else branch) that'll run for initial exports or people with many live photos
=> [desktop] Speed up reconciliation 

desktop/src/main/services/auto-launcher.ts, desktop/yarn.lock
- Update Electron 30.0.9 => 30.1.2
- Revert to the now un-deprecated API that we were using earlier
- Upgrade lru-cache
=> [desktop] Update Electron 30.0.9 => 30.1.2

server/scripts/deploy/museum.nginx.conf
Allow HTTP request body up to 4 MB. The default is 1 MB, which is too small for face embeddings for photos with more than a couple of hundred faces.
Roughly, each face embedding is 4KB, but encrypting and base-64-ing the embedding also has a 30% addition (just from one sample I saw), so this should allow photos with ~700 faces to go through.
Ref:
- https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
=> [server] Increase HTTP request body size to prevent 413 Too Large errors

desktop/eslint.config.mjs, desktop/package.json, desktop/src/main.ts, desktop/yarn.lock
Fixes: Running `yarn lint` would complain about a too new TypeScript version.
=> [desktop] Update eslint to fix warnings introduced after update to TypeScript 5.5

web/packages/next/package.json, web/yarn.lock
Something's wrong with yarn's resolution algorithm, but let's leave that be until we migrate off classic. 11.11.4 doesn't have anything we need, so use 11.11.3 that seems to not result in dupes.
The warning was
gallery.js:16547 You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.
Ref:
- https://github.com/ente-io/ente/pull/2372
=> [web] Fix duplication emotion instances

web/apps/cast/src/services/render.ts, web/apps/photos/src/components/PhotoViewer/index.tsx, web/packages/media/formats.ts, web/packages/new/photos/utils/file.ts
- Let supporting browsers (e.g. Safari) upload them.
- Let them be indexed by converting to JPEG.
=> [web] Improve JPEG 2000 handling

cli/Dockerfile, cli/Dockerfile-x86, server/Dockerfile
With the latest Docker update (27.0.3), it now warns about the "FROM" and "AS" in the Dockerfile not matching. E.g. when building the server docker image:
> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
=> [server] [cli] Fix docker "FROM AS" case warnings

server/pkg/repo/passkey/passkey.go
Safari just doesn't recognize the Yubikey (macOS/iOS, NFC/USB, doesn't matter) if display name is set to the empty string. Safari's long description doesn't care to mention this requirement:
https://webkit.org/blog/11312/meet-face-id-and-touch-id-for-the-web/
Tested on localhost with Safari macOS. Will test on iOS post deployment.
=> [server] Add a workaround for Safari to recognize Yubikeys

cli/utils/constants/constants.go
I noticed there was a typo in the EnteAccountUrl constant for the CLI, which resulted in an incorrect URL being generated when asking the user to verify their passkey.
I didn't see tests in the project, but I did build the cli project and manually tested `cli.exe` by adding my ente account and verifying the URL that's generated is correct now.
```
Nick  ~\..\ente\cli  .\cli.exe account add
Enter app type (default: photos):
Use default app type: photos
Enter export directory: .\
Enter email address: redacted@pm.me
Enter OTP: 123456
Open this url in browser to verify passkey: https://accounts.ente.io/passkeys/verify?redacted
Press enter once you have completed the passkey verification
```
=> [cli] Fix typo with ente account url constant

auth/lib/l10n/arb/app_en.arb, auth/lib/ui/code_error_widget.dart, auth/lib/ui/home_page.dart, auth/lib/ui/tools/debug/raw_codes_viewer.dart
=> fix(auth/code): add option to view raw codes in case of parse fail

cli/pkg/secrets/secret.go
Adds a new enviroment variable `ENTE_CLI_SECRETS_PATH`, that allows specifying the path to a `secrets.txt` like the one used in the dockerized version. If no path is provided, the old behaviour is maintained.
The configuration variable and behaviour is analog to the already present `ENTE_CONFIG_PATH` variable, which allows specifying a configuration. 
This provides a solution for people running without gnome-keyring (https://github.com/ente-io/ente/issues/722 and https://github.com/ente-io/ente/issues/1328)
=> CLI: Allow setting secrets path via env var

desktop/src/preload.ts, web/apps/photos/src/components/Upload/Uploader.tsx
Trying to diagnose a customer issue where they reported that the renderer was crashing when trying to drag and drop a 1TB folder on Windows. Fixing some things that popped out in the memory allocations or the CPU time when testing with a synthetic workflow (on macOS) - these may or may not fix their issue, but these are anyway improvements and will only make things better.
=> [desktop] Attempts to improve large drag drops on Windows

server/cmd/museum/main.go
Doesn't impact Ente's production instances since this endpoint was disallowed on the load balancer, but instead of requiring the same for folks who are self hosting we modify the source to not expose /metrics on :8080 (they'll still be available on :2112).
Refs:
- https://github.com/zsais/go-gin-prometheus/blob/2199a42d96c1d40f249909ed2f27d42449c7fc94/middleware.go#L345
- https://github.com/ente-io/ente/discussions/2562
=> [server] Stop exposing /metrics for self-hosted users

web/packages/new/photos/services/ml/embedding.ts, web/packages/new/photos/services/ml/worker.ts
Speeds up the initial sync on a new client.
=> [desktop] Pull existing embeddings first before starting on indexing

mobile/lib/models/ffmpeg/ffprobe_keys.dart, mobile/lib/models/ffmpeg/ffprobe_props.dart, mobile/lib/ui/viewer/file/zoomable_image.dart
- Stopped updating image width and height in public metadata since the these could be incorrect (width and height inverted to be precise).
- Parse `rotation` metadata from video metadata when parsing video properties with `ffprobe` to get the correct video width and height considering `rotation`.
=> [mob][photos] Handle/fix issues with media dimensions

mobile/lib/models/ffmpeg/ffprobe_keys.dart, mobile/lib/models/ffmpeg/ffprobe_props.dart, mobile/lib/ui/viewer/file/file_details_widget.dart, mobile/lib/ui/viewer/file/video_exif_dialog.dart, mobile/lib/ui/viewer/file_details/video_exif_item.dart
Parse width and height of video correctly using FFProbe by 
- Considering both `coded_height` & `height` + `coded_width` + `width` keys to parse height and width of video. Came across two videos where `coded_width` and `coded_height` were both `0` where as `height` and `width` had the correct values.
- Parse `rotation` from `side_data_list` and consider `rotation` for accurate (i.e, not flipped) dimensions.  
Have made sure the correct height and width of the video is shown on the video's file info. Sometimes there could be a slight difference from what a user would expect, if the `coded_side` is different from `side` (`side` is `width` or `height`). Will be fixing this in future.
Ref: https://superuser.com/questions/1523944/whats-the-difference-between-coded-width-and-width-in-ffprobe
=> [mob][photos] Fix bug in parsing rotation metadata from video using FFProbe

auth/android/app/src/main/AndroidManifest.xml, auth/ios/Runner/Info.plist
Changed the name of the Auth mobile app to "Ente Auth" on both Android and iOS to make it consistent with the naming of Ente Photos and to also make it consistent on both platforms.
=> Change Auth mobile apps' names to "Ente Auth"

web/apps/photos/src/components/pages/gallery/PlanSelector.tsx, web/apps/photos/src/utils/billing/index.ts
This fixes an issue where a user with a cancelled _and_ expired subscription would try to purchase a plan, and would instead get redirected to the updated subscription flow in stripe (instead of the buy flow).
Smoke tested a few scenarios locally.
=> [web] Improve handling of cancelled sub updates

auth/lib/onboarding/view/onboarding_page.dart
Windows client without pin/password should also be able to use the app, without backups as they can set app lock afterwards.
=> [auth] allow without backups use for windows

server/pkg/controller/replication3.go, server/pkg/repo/object.go, server/pkg/repo/object_copies.go
Going forward, we pick a row for replication, and immediately mark replication attempt. Once that's done, we try to replicate the object, and update it's status without any transaction.
The initial locking and marking the replication attempt should ideally ensure that no other worker will pick up the row for replication for next 24hours.
=> [sever][replication] Avoid long running txn during replication

server/pkg/controller/file.go, server/pkg/controller/replication3.go, server/pkg/repo/object_copies.go
=> Add timeout for replication lock query & allow updating metadata with less keys

cli/cmd/export.go, cli/pkg/admin_actions.go, cli/pkg/model/constants.go, cli/pkg/model/export/filter.go, cli/pkg/model/filter.go, cli/pkg/model/remote.go, cli/pkg/remote_sync.go, cli/pkg/remote_to_disk_album.go, cli/pkg/remote_to_disk_file.go, cli/pkg/sync.go
Feature: Add support for selective export with filters for account, albums, and options to exclude hidden or shared files.
Flags Added:
--shared: Include shared albums in export (default: true).
--hidden: Include hidden albums in export (default: true).
--albums: Comma-separated list of album names to export.
--emails: Comma-separated list of emails of the accounts that needs to be exported
Behavior: By default, both hidden and shared albums are exported.
Tested locally
=> [cli] Add filters for Export

.github/workflows/server-lint.yml
Unrelated to the lint failures, I noticed that we were not using the go.sum file during the lint steps.
=> [server] Use the go.sum cache during CI lint

server/ente/errors.go, server/pkg/controller/authenticator/controller.go
This avoids the 5xx error for authEntity which happens when we try to create an auth entity without reporting the corresponding key
=> [server] Add auth key validation

web/packages/new/photos/services/ml/index.ts
Otherwise the code reaches the isInternalUser on logout, triggered by the search service, and at a point when it does not have the auth token anymore. Doesn't impact production builds, but doesn't hurt to make the check more robust say for people who're trying dev builds.
=> [desktop] Improve robustness of cluster disabling condition

auth/fdroid_flutter_icons.yaml
Fdroid icon for auth was white, whilst we have already moved to purple gradient. This PR adds the same adaptive background for fdroid as it is for normal build.
The below Fdroid build recipe regenerates the icons that's why it was not correct before:
https://gitlab.com/fdroid/fdroiddata/-/blob/3bbf65e8f0f056c5df9873bd683ab23f5f7de14c/metadata/io.ente.auth.yml#L58
=> fix: fdroid icon background

web/apps/photos/src/components/Notification.tsx, web/apps/photos/src/components/PhotoViewer/FileInfo/index.tsx, web/apps/photos/src/components/WatchFolder.tsx, web/packages/base/components/Typography.tsx
The overflow: "hidden" on the two parent divs is still needed, for reasons I don't fully understand, need to debug further at some point.
=> [web] Improve the handling of ellipsized labels

docs/docs/auth/migration-guides/authy/index.md
As Authy no longer supports its desktop apps, moving from Authy to Ente Auth using the methods are not possible. This PR adds this notice to the guide.
it was fun while it lasted :pensive:
=> [docs] Authy guide obsolete notice

auth/assets/custom-icons/_data/custom-icons.json
Removed extra line after "enom" and adjusted itch.io icon color to more closely match their recommended color in dark and light mode.
=> [Auth] Adjust icons

web/apps/photos/src/components/Upload/UploadButton.tsx, web/apps/photos/src/components/pages/gallery/Navbar.tsx
Two minor style fixes for the nav bar. 
1. Sidebar 3-lines IconButton had its left padding set to 0, which causes issues.
2. Upload icon on mobile had the wrong height and thus weird ripple / hover effects.
Please see the respective commit for details & the reasoning.
How those currently look:
How they look with the proposed fix:
Thanks!
=> [web][photos] Fix web navbar button sizes

web/apps/photos/src/components/Search/SearchBar/searchInput/valueContainerWithIcon.tsx
This fixes the search icon in the search box not being centered properly and also not having the muted color style.
The container is a flex-box layout which already tries to center its items. But due to the icons in MUI having a display of `inline-block`, our `Box` container also needs `display: inline-flex` to properly calculate the height. Now the box container is the same height as the icon and it gets centered correctly again.
This is the same methodology that the MUI native `IconButton` also uses
as a display value. See https://github.com/mui/material-ui/issues/33020#issuecomment-1149971549
Current web version:
Proposed fix:
This also removes the `icon` CSS class from the Box container since it does not exist anyway. And we fixed the theme color not being applied. This was otherwise …
=> [web][photos] Fix search icon layout & color

auth/assets/custom-icons/_data/custom-icons.json
Added FritzBox to custom-icons.json. It uses the same svg as myfritz, so its entry was extended insted of creating a new one
=> [auth] Added FritzBox to custom-icons.json

web/apps/photos/src/services/upload/uploadService.ts
e.g. on Intel macOS. Regression introduced in 1.7.3, specifically 862495c29e2092c778a724df33397f6e313688fc.
=> [desktop] Fix video upload when metadata extraction fails

.github/workflows/auth-lint.yml, .github/workflows/desktop-lint.yml, .github/workflows/docs-verify-build.yml, .github/workflows/infra-lint-staff.yml, .github/workflows/mobile-lint.yml, .github/workflows/server-lint.yml, .github/workflows/web-lint.yml
Currently, for PRs opened by external contributors, the various lint checks don't run (sometimes causing code that fails basic lint checks to be committed to main).
From my current understanding (I find the docs around this confusing - I'm not sure about this), we need to instead use "pull_request". Refs:
* https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
* https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
Note that even then, we will need a manual step to approve running the lints for first time contributors. Which is fine, at least we'll see the option, unlike right now where they just can't be run until the code hits main.
=> [meta] Run PRs lint checks for pull requests from external forks

desktop/.github/workflows/desktop-release.yml
Tested locally, still need to run it as a GitHub action to verify that it is working as intended.
Refs:
- https://www.npmjs.com/package/ffmpeg-static#electron--other-cross-platform-packaging-tools
- https://github.com/eugeneware/ffmpeg-static/issues/35
- https://github.com/eugeneware/ffmpeg-static/issues/136
=> [desktop] Create ffmpeg universal binaries for macOS

desktop/.github/workflows/desktop-release.yml
The previous approach worked, but we ran into some other issues
Uncaught Exception:
Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- /Applications/ente.app/Contents/Resources/app.asar/node_modules/ajv-formats/dist/limit.js
As an alternative, try to use the yarn equivalent(-ish).
=> [desktop] Fix macOS universal binaries

desktop/docs/dependencies.md, desktop/package.json, desktop/yarn.lock
I'm not sure why it started happening now. Earlier I thought it was because of this - https://github.com/ente-io/ente/pull/2969 - but that was a red-herring (I think!), instead this likely got triggered because of
https://github.com/ente-io/action-electron-builder/commit/eff78a1d33bdab4c54ede0e5cdc71e0c2cf803e2.
This change fixed the issue locally, will see if it works on CI too.
Workaround from:
https://github.com/ajv-validator/ajv/issues/2443#issuecomment-2147026958
=> [desktop] Fix broken nightly builds due to ajv

desktop/.github/workflows/desktop-release.yml
Apparently, specifying something after the @ is necessary. Without this, the action stopped working.
Updates https://github.com/ente-io/ente/pull/2976.
=> [desktop] Specify an action version

web/apps/photos/src/components/Sidebar/Preferences.tsx
This had been accidentally left enabled on web. The ML wouldn't run, just the option was being shown.
Fixes https://github.com/ente-io/ente/issues/2944
=> [web] Show ML option only on desktop

web/apps/photos/src/services/fileService.ts, web/packages/new/photos/services/files.ts
This still doesn't clear the cached React component, but now at least the thumbnail would be refreshed on the next refresh of the page.
=> [web] Clear cached thumbnails if the source file is edited

server/cmd/museum/main.go, server/ente/base/id.go
Note: if the client has already attached reqID in header, that will be used. All mobile clients currently add uuid as reqID, will change it to use `mphoto`, `mauth` as nano id prefix, similarly `cli` for CLI.
=> [server] Use nanoId as reqID

web/packages/base/locales/en-US/translation.json
Context: https://github.com/ente-io/ente/discussions/3070
=> [web] Indicate that hash comparision is also used in the detail message

web/apps/photos/src/components/Collections/CollectionSelector/AddCollectionButton.tsx, web/packages/base/locales/en-US/translation.json
Change title of the button from "New album" to "Create albums" to indicate that it can be used to preserve albums.
See: https://github.com/ente-io/ente/issues/3067
=> [web] Make it more apparent what the create albums button does

auth/lib/ui/home_page.dart
Currently, on Windows, it is required two mouse clicks in order to focus the search box. 
1. Click the search icon 
3. Click the search box
4. Type keywords 
After this fix:
1. Click the search icon
4. Type keywords 
Before:
https://github.com/user-attachments/assets/a2f26d84-6c00-4ca6-ae94-cc004dd13f8f
After
https://github.com/user-attachments/assets/0950e7e9-4b90-4e70-b82c-de3f739d77c5
- Tested on Windows 11 x64 (23H2 22631.3296).
- I added `Platform.isWindows`, as I could test on Windows only.
- Actually I saw this problem on one of my Android phone, but I am not able to build the apk to test it, should be due to my Android SDK issue.
- I don't have iOS devices
=> Request focus on the search box when clicked the search icon

auth/lib/ui/tools/app_lock.dart, auth/lib/ui/tools/lock_screen.dart, auth/lib/utils/lock_screen_settings.dart, mobile/lib/utils/lock_screen_settings.dart
Check commit message.
Since this removes a code block added to fix another bug (see #358 ), I've verified that the change in this PR doesn't resurface the old bug. From what I've observed, changing the `immediate` app lock time from 0 to 650ms stops the old bug from surfacing.
=> [mob][photos][auth] Fix lockscreen not automatically appearing on opening app on iPad

docs/docs/self-hosting/guides/configuring-s3.md, server/configurations/local.yaml, server/pkg/utils/config/config.go
Since museum.yaml is gitignored, loading it the last makes it easier to do ad-hoc configuration changes without marking the git tree dirty.
=> [server] Load museum.yaml after configuration.yaml

mobile/lib/ui/viewer/file/panorama_viewer_screen.dart
Add back button to Panorama screen which will disappear as soon as timer expires i.e. 5 seconds and reappear on screen tap.
=> [mob](panorama): add back button to viewer screen

mobile/lib/services/machine_learning/face_ml/face_detection/face_detection_service.dart, mobile/lib/services/machine_learning/face_ml/face_recognition_service.dart, mobile/lib/services/machine_learning/semantic_search/clip/clip_image_encoder.dart, mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart, mobile/lib/utils/image_ml_util.dart, mobile/lib/utils/ml_util.dart
- Stop using unnecessary ByteData and Color classes, using simple Uint8List and RGB integers instead
- Use antialias for clip image preprocessing
Tested by comparing resulting embedding to Python.
=> Mob antialias

.github/workflows/web-lint.yml
Ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-using-concurrency-and-the-default-behavior
=> [web][meta] Ignore stale lint runs on PR push

cli/pkg/secrets/key_holder.go, cli/pkg/secrets/secret.go
Related to #1510 & [#3163](https://github.com/ente-io/ente/pull/3163)
This potential fix was only possible due to amazing investigation done by @shoetten
Did basic sanity testing on local machine
=> [cli] Base64 Encode the CLI secrets

mobile/lib/ui/tools/lock_screen.dart
If lockscreen is above some screens (like an album) and user logs out, the app goes back to that screen after logging out.
Killing the app right after logging out was the easiest fix.
=> [mob][photos] Kill the app on logging out from lockscreen

docs/docs/auth/migration-guides/authy/index.md
Adds an option to export authy codes with a rooted android device. I will probably modify [the tool used](https://github.com/puddly/android-otp-extractor) so it exports to an Ente compatible json file later but this will work for any uses who need to export from authy (Likely do to them blocking rooted users now like me)
=> [docs] [auth] Add the new method to extract TOTP codes from authy

mobile/lib/ui/home/loading_photos_widget.dart
Noticed that it takes 40 seconds or more for me at times. So increasing the time to reduce number of potential unnecessary tickets.
=> [mob][photos] Increase time taken to show up send logs CTA on loading local photos screen

mobile/lib/ui/components/home_header_widget.dart, mobile/lib/ui/home/loading_photos_widget.dart, mobile/lib/ui/home/start_backup_hook_widget.dart, mobile/lib/ui/settings/backup/backup_folder_selection_page.dart, mobile/lib/ui/settings/backup/backup_section_widget.dart, mobile/lib/ui/viewer/search/tab_empty_state.dart
- Avoid/fix potential and current issues caused due to calling `dependOnInheritedWidgetOfExactType<T>()` in initState (i.e, before the widget is build).
=> [mob][photos] Fix exceptions from incorrect use of InheritedWidget

web/apps/photos/src/components/pages/gallery/PreviewCard.tsx
Using opacity: 0 to was causing the first click to be intercepted by the input element itself on mobile devices.
=> [web] Thumbnails: Handle the first click on mobile devices

auth/lib/ui/code_widget.dart
In some place isCompactMode was using local value, which was never updated and was always true. Which resulted in components such as Pin icon background to display incorrect in size.
=> [auth]: use correct value for compact mode in code widget

server/pkg/utils/email/email.go
When using a local relay server, not authentication is needed. To support this use-case authentication is only send to the server when an user and password are set in the configuration file.
See error message from https://github.com/ente-io/ente/discussions/3179
=> [server] Optional SMTP authentication

cli/pkg/cli.go
When the /tmp folder is tmpfs the size is restricted and the download failes when this tmp folder is full.
This PR introduces a enviroment variable to set the tmp download folder.
=> Add possibility to define cli download tmp path with env variable

mobile/lib/events/magic_cache_updated_event.dart, mobile/lib/models/search/search_types.dart, mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart, mobile/lib/services/magic_cache_service.dart, mobile/lib/services/search_service.dart, mobile/lib/ui/settings/debug/ml_debug_section_widget.dart, mobile/lib/ui/viewer/search/result/magic_result_screen.dart, mobile/lib/ui/viewer/search/result/search_section_all_page.dart, mobile/pubspec.yaml
=> [mob] Minor fixes for discover

web/apps/photos/src/components/PhotoFrame.tsx, web/apps/photos/src/pages/deduplicate.tsx, web/apps/photos/src/pages/gallery.tsx, web/apps/photos/src/pages/shared-albums.tsx
The duplicate images page has a image preselected but there is no checkbox available.
When unselecting this image there is no possibility to do a new selection.
This PR adds the same checkbox like on the gallery to select images on the deduplication page.
=> [web/desktop] Make images on deduplicate selectable

server/pkg/controller/family/admin.go, server/pkg/controller/family/family.go
Currently, we force the admin to remove the members themself and revoke the invite before a family account can be closed.
Going forward, this action will be automatically done. This will help in reducing support overhead.
=> [server] Remove invites & remove members during closeFamily

desktop/src/main/services/ml-worker.ts, web/packages/base/types/ipc.ts, web/packages/new/photos/services/ml/clip.ts, web/packages/new/photos/services/ml/face.ts, web/packages/new/photos/services/ml/image.ts
Switched to new clip ONNX model on web, where preprocessing is done inside ORT. This means it's more performant and more advanced image processing.
Not tested at all! I'm sure I've made a small mistake somewhere, please review and test carefully. 
The only thing properly tested is the model itself, this approach is tested and passed on mobile.
Also, there's one "TODO: manav" pending, please check.
=> Clip with preprocessing inside ONNX on web

auth/assets/custom-icons/_data/custom-icons.json
=> Add altName back to T-Mobile icon that was previously removed from json

auth/windows/packaging/exe/inno_setup.iss
Portable x64 Ente Auth works on arm64 Windows, but the installer version fails due to not supporting arm64. As per Inno Setup's documentation the 'x64' option will only allow installing on x64 Windows, changing to 'x64compatible' allows the x64 installer to work on arm64 as well.
=> [auth] fix x64 installer on arm64 Windows

web/packages/new/photos/components/mui-custom.tsx
Indeed, it seems like the default is not a hand pointer, and MUI has customized its button, so we need to replicate that behaviour if we directly use HTML buttons.
Ref:
- https://ux.stackexchange.com/questions/3788/default-cursor-on-mouse-over-of-a-button-is-not-a-hand-pointer
=> [web] Update docs after verifying the behaviour

auth/lib/ui/home_page.dart, auth/macos/Runner/AppDelegate.swift
In the current version of Ente Auth, nothing happens when the user closes the Ente Auth window on macOS and then clicks on the Ente Auth icon in the dock.
This PR changes this behaviour and brings it in-line with other macOS applications by showing the main application window when the user clicks on the dock icon.
=> [auth][macos] show hidden window when user clicks on the dock

auth/lib/l10n/arb/app_en.arb, auth/lib/ui/settings/security_section_widget.dart, auth/lib/ui/tools/lock_screen.dart, auth/lib/utils/lock_screen_settings.dart
1. Removed the logout button from the lockscreen if app in without backup state
2. Show a warning dialog when user try to set the app lock for the 1st time
=> [auth] Auth lockscreen fixes

web/apps/photos/src/components/pages/gallery/PreviewCard.tsx, web/apps/photos/src/components/pages/gallery/SelectedFileOptions.tsx, web/apps/photos/src/pages/gallery.tsx, web/apps/photos/src/services/collectionService.ts, web/apps/photos/src/utils/file/index.ts
This allows on the web app to bulk favorite multiple photos in one go, by adding a favorite button to the SelectedFileOptions.tsx component. Just like for the Android App.
This could be enhanced by having the button plain or empty depending the selection and by setting/unsetting favarite depending previous status. For now it just set as favorite whatever the status (like the Android app).
- Select at least 2 pictures in another album than hidden, favorited, trash, ...
- Click at top right of the screen the favorite icon
- the favorite icon on the previously selected thumbnails should appear
=> [web] add favorite button to SelectedFileBar to bulk favorite selection

auth/linux/my_application.cc
Currently, Flutter defaults to always using GTK
window decorations regardless of the window
manager, when running Wayland. This makes the app
look out of place on KDE Plasma and other Qt-based desktop environments.
This change checks the XDG_CURRENT_DESKTOP
environment variable to determine the running
desktop environment, and if it is GNOME continues
to use the GTK header, otherwise it uses the Qt
header.
| Before | After |
|--------|--------|
| ![before](https://github.com/user-attachments/assets/db7161fa-3d87-4c62-bc38-e74763cb2304) | ![after](https://github.com/user-attachments/assets/f6ece7d6-f2cc-4ee7-b3d2-3eda722aee67) |
=> [auth] fix: don't use GNOME header bar outside of GNOME

auth/linux/my_application.cc
This change sets the program name to the application ID, which helps various
systems like GTK and desktop environments map this running application to its
corresponding .desktop file. This ensures better integration by allowing the
application to be recognized beyond its binary name.
Notably, this is necessary on Wayland to map the running application window to
the desktop file, and therefore apply the correct icon.
This is the [same fix that is applied to new Flutter projects](https://github.com/flutter/flutter/pull/154522).
|  | Before | After |
|--------|--------|--------|
| Window | ![before-window](https://github.com/user-attachments/assets/71f3c5bb-f5e0-4d33-a9f6-344480761f53) | ![after-window](https://github.com/user-attachments/assets/b208bfd2-25c0-4583-9bce-46f5761f0886) |
| …
=> [auth] fix(linux): generic icon on Wayland sessions

mobile/lib/main.dart
Although we don't await on the result, running these method can affect app start up time because the OS may take some CPU away till it execute the next step.
=> [mob] Schedule sync after runApp

cli/cmd/authenticator.go, cli/pkg/authenticator/decrypt.go
This PR adds a new flag `--password` (with `-p` for short format) to the `auth decrypt` command.
This will allow to run the decryption in just one command, without the need for interactive user input.
Run the command with a `--password` or `-p` flag and check the encrypted file is correctly decrypted.
=> Add support for the password flag to the decrypt command

web/apps/photos/src/pages/gallery.tsx, web/packages/new/photos/components/SearchBar.tsx, web/packages/new/photos/components/gallery/reducer.ts
This finishes the overall move for the time being, preparing the ground for the people related gallery tweaks that we need to make.
=> [web] Use reducer for gallery - Fin 7/7

mobile/lib/services/machine_learning/face_ml/face_detection/detection.dart, mobile/lib/services/machine_learning/face_ml/face_detection/face_detection_postprocessing.dart, mobile/lib/services/machine_learning/face_ml/face_detection/face_detection_service.dart, mobile/lib/services/machine_learning/ml_model.dart, mobile/lib/services/machine_learning/semantic_search/clip/clip_image_encoder.dart, mobile/lib/services/remote_assets_service.dart, mobile/lib/utils/image_ml_util.dart, mobile/plugins/onnx_dart/android/src/main/kotlin/io/ente/photos/onnx_dart/OnnxDartPlugin.kt
Reverting some changes that moved preprocessing inside ONNX because it's giving memory issues.
Tested in debug mode on my pixel 8.
=> [mob][photos] Revert onnx preprocessing

auth/lib/app/view/app.dart, auth/lib/locale.dart, auth/lib/main.dart, auth/lib/onboarding/view/onboarding_page.dart, auth/lib/ui/settings/general_section_widget.dart, auth/lib/ui/tools/app_lock.dart, mobile/lib/app.dart, mobile/lib/l10n/l10n.dart, mobile/lib/main.dart, mobile/lib/ui/home/landing_page_widget.dart, mobile/lib/ui/settings/general_section_widget.dart, mobile/lib/ui/tools/app_lock.dart, mobile/lib/ui/viewer/file_details/creation_time_item_widget.dart, mobile/lib/ui/viewer/gallery/hooks/add_photos_sheet.dart
=> [mob][auth] Fix detection of default locale

server/pkg/repo/public_collection.go
For supporting app links on android, the shared album URL needs to have a '/' before the query params.
=> [server] Add '/' before query params for an album's share URL

server/cmd/museum/main.go, server/ente/filedata/filedata.go, server/pkg/api/file_data.go, server/pkg/controller/filedata/controller.go, server/pkg/repo/filedata/repository.go
Note:
This API won't really return status/diff for deleted files. The clients will primarily use this data to identify for which all files we already have preview generated or it's ML inference is done.
This doesn't simulate perfect diff behaviour as we won't maintain a tombstone entries for the deleted API.
=> [server] API to get file data status

desktop/CHANGELOG.md, desktop/package.json
Also updated 1.7.6 changelog with two entries I'd forgotten to add earlier.
=> [desktop] Start next release train

docs/docs/.vitepress/sidebar.ts, docs/docs/self-hosting/troubleshooting/keyring.md
Adding docs for setting up the ENTE_CLI_SECRET_PATH variable. This fix is for errors related to keyrings with ente-cli.
=> [docs][ente-cli]: add docs to troubleshoot keyring errors

server/pkg/api/user.go, server/pkg/controller/filedata/replicate.go, server/pkg/repo/filedata/repository.go
Added additional logs for passkey authentication failures.
=> [server] Add delay in fileData replication 

server/ente/offer.go, server/mail-templates/bf_2024.html, server/pkg/controller/offer/offer.go
=> [server] Send a notification email on BF deal purchase

web/apps/photos/src/pages/gallery.tsx, web/packages/new/photos/components/gallery/reducer.ts, web/packages/new/photos/services/files.ts, web/packages/new/photos/services/search/index.ts, web/packages/new/photos/services/search/types.ts, web/packages/new/photos/services/search/worker.ts
The uniquification would prevent albums that only contains photos that are
already present in another album from appearing in search results.
=> [web] Fix search when an album only has symlinks

infra/staff/src/components/Disable2FA.tsx
=> [staff] Fix disable 2FA

cli/main.go
Calling `GetOrCreateClISecret()` can cause issues in some unattended scenarios.
I'm creating a Brew formula for ente CLI with the following test:
```
test do
assert_match "Version #{version}", shell_output("#{bin}/ente version")
end
```
When running `brew test` for the formula, ente would fail with the following error: `2024/11/13 11:49:56 error setting password in keyring: exit status 154`
And I would see this pop-up:
=> [cli] Don't perform CLI secret initialisation unless needed

auth/lib/services/update_service.dart
This PR fix typos in the market URI that resulted in 404 page on android market.
=> [mob] Fix market URI on mobile

web/apps/photos/src/styles/global.css
Fixes https://github.com/ente-io/ente/issues/4067
=> [web] Add workaround for black grid lines when zooming onto images in Chrome

web/packages/new/photos/components/gallery/PeopleHeader.tsx, web/packages/new/photos/services/ml/cluster.ts, web/packages/new/photos/services/ml/index.ts, web/packages/new/photos/services/ml/people.ts, web/packages/new/photos/services/ml/worker.ts, web/packages/new/photos/services/user-details.ts, web/packages/new/photos/services/user-entity/index.ts, web/packages/utils/transform.ts
Sibling of https://github.com/ente-io/ente/pull/4027
=> [desktop] Support rejected faces in clusters synced with remote 

server/cmd/museum/main.go, server/ente/admin.go, server/ente/user.go, server/pkg/api/admin.go, server/pkg/controller/user/user_details.go, server/pkg/repo/authenticator/entity.go, server/pkg/repo/passkey/passkey.go, server/pkg/repo/userauth.go
=> [server] Encrich admin api response

mobile/lib/ui/tools/editor/image_editor_page.dart
Proposal to fix #2894 so that edited image keep same dimensions/resolution as original image
The issue was that `FlutterImageCompress.compressWithList` was forcing the result to be resized using the method's default values {minWidth = 1920, minHeight = 1080}.
It is now forcing the size to be the one right before the compression, after the potential alterations (flip, rotate, ..).
Tested on my Pixel 6a
Built with :
Flutter 3.24.3
JDK 17.0.2
Gradle 7.2
=> [mob][photos] Fix #2894 - Edited image resolution

server/ente/user.go, server/pkg/controller/user/userauth.go
- When both `passkeySessionID` and `twoFactorSessionID` are set in the response, the web will surface passkey based login while mobile will only surface totp based login.
- For now, I have added a new field in the response (`twoFactorSessionIDV2) for totpBased twoFactor, that will be only set when both passkey and totp based MFA are enabled.
- Once both mobile and desktop changes are out, we can remove this new field `twoFactorSessionIDV2` from the response
Corresponding mobile diff: https://github.com/ente-io/ente/pull/4210
=> [server] Create totpSession when both passkey and totp are enabled

web/packages/accounts/components/SecondFactorChoice.tsx, web/packages/accounts/components/utils/second-factor-choice.ts, web/packages/accounts/pages/credentials.tsx, web/packages/accounts/pages/verify.tsx, web/packages/accounts/services/user.ts, web/packages/base/locales/en-US/translation.json
Sibling of mobile https://github.com/ente-io/ente/pull/4210. Unlike mobile, we automatically redirect so we need to ask the user their pref beforehand.
=> [web] Ask the user their preferred 2FA choice if both are enabled

mobile/lib/ui/viewer/search/search_widget.dart, mobile/lib/ui/viewer/search_tab/search_tab.dart
Fix for the hint text ("Search") in the search bar getting misaligned more towards the top for smaller font sizes (normal for a big enough majority of people).
=> [mob][photos] Fix misaligned hint text in search bar

server/pkg/middleware/auth.go
This allows working around an issue with Viper where it doesn't properly unmarshal GetIntSlice from environment variables. Seems like this is a known issue and is quite old. I'm assuming there isn't plans to fix it on the Viper side.
https://github.com/spf13/viper/issues/339
I'll be brutally honest, I don't know how to run Go, but this seemed like a pretty quick low hanging fix.
=> Workaround for Admins list in Environment Variables by specifying singular admin

cli/cmd/setup.go, cli/pkg/cli.go
Adds a command `ente setup public-albums-url`.
=> [cli][setup] add: public-albums-url subcommand to configure albums url

server/pkg/controller/user/srp.go, server/pkg/middleware/rate_limit.go, server/pkg/repo/srp.go
This (cosmetic?) change is to reduce the brute-force attempt on password cracking.
It feels cosmetic because each create-session call requires an expensive KDF steps for different password. It's also not prone to dictionary attack because of the nonce.
Still, this change felt harmless to make, and it's hardens the security further.
Tested locally
=> [server] Limit unverifeid sessions

server/configurations/local.yaml, server/pkg/controller/user/userauth.go
As discussed in #2476, I added an option `internal.disable-registration` to allow disabling the registration of new users on selfhosted instances.
Users can still go through the registration flow, but when entering the ott they received via mail, they get an unauthorized error.
Should this be documented in any of the self-hosting documentation?
=> Add `internal.disable-registration` to config

mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/l10n.dart, mobile/lib/l10n/intl_en.arb, mobile/lib/ui/settings/advanced_settings_screen.dart, mobile/lib/ui/settings/backup/free_space_options.dart
=> [mob] Move manage device cache option from Advance to Free up space

docs/docs/self-hosting/guides/external-s3.md
When I was trying to set this up, I was getting errors from `docker compose`:
```
failed to read /var/hosts/ente/.credentials.env: line 11: unexpected character "-" in variable name "ENTE_APPS_PUBLIC-ALBUMS=https://<redacted>"
```
There was, apparently, a brief period in time when `docker compose` supported dashes in ENV var names, [but this is no longer the case](https://github.com/docker/compose/issues/12302), hence some vars need to be defined in a `museum.yml` and mounted into the instance. Maybe there is some rewriting in place that allows to redefine `museum.yml` entries with dashes in ENV vars, however I couldn't find it (and if there isn't, there probably should be, but this change should make the guide usable again at least).
=> Dashes in ENV var names not supported by docker compose

mobile/lib/ui/viewer/people/save_or_edit_person.dart
- Fixed by adding a key to the PersonGridItem, that way it gets refreshed when the person is changed
(related issue : #4311)
=> [mob][photos] Fix state issue when reloading avatar (#4311)

mobile/lib/ui/components/text_input_widget.dart
Text is clipped more towards the right end
=> [mob][photos] Fix clipping of TextInputWidget

docs/docs/auth/migration-guides/authy/index.md
Reasoning: I encountered some console errors trying to export from Authy using the first method described in the existing documentation. After a bunch of research I found that Aegis Authenticator can import from the same device and it worked like a charm, so I hope other people can use this method as well.
=> [auth][docs] Add Aegis Authenticator Authy Export instructions

auth/assets/custom-icons/_data/custom-icons.json
Debug build failing due missing [ ] in altNames in the custom-icon.json from PR  [https://github.com/ente-io/ente/pull/4348/files]()
Code Ref: https://github.com/ente-io/ente/blob/main/auth/assets/custom-icons/_data/custom-icons.json#L639
=> [auth] fix missing [ ] in altNames in custom-icons.json

auth/windows/runner/main.cpp
Pull request was made because of some user percentage has taskbar connected on top, so it overlaps auth window for WinApp at start.
After some measuring, I found that taskbar occupies:
- 50px on FHD with 125% scaling (standard values on some notebooks)
- 40px on FHD with 100% scaling
- 30px on FHD with 100% scaling and small taskbar icons
=> [auth] Fixing taskbar overlapping window panel

auth/lib/models/all_icon_data.dart, auth/lib/models/code_display.dart, auth/lib/onboarding/view/setup_enter_secret_key_page.dart, auth/lib/ui/code_widget.dart, auth/lib/ui/components/custom_icon_widget.dart, auth/lib/ui/custom_icon_page.dart, auth/lib/ui/utils/icon_utils.dart
This PR introduces a new feature allowing users to select and assign custom icons to their codes.
=> [auth] Add Support for Custom Icons 

web/apps/photos/src/services/export/index.ts, web/apps/photos/src/services/export/migration.ts, web/apps/photos/src/utils/collection.ts, web/apps/photos/src/utils/file/index.ts, web/packages/base/file-name.ts, web/packages/new/photos/utils/native-fs.ts
This fixes the issue where files would be exported twice on pressing resync if the user selected "C://" (or some other root drive) as the export destination.
=> [desktop] Fix export when selecting root folder

desktop/src/main/services/fs.ts
A customer reported a partial export_status.json being written to an external drive. Forcing a flush to attempt to reduce chances of this happening. Since this particular code path is only used for writing JSON files (export status and metadata), we unconditionally enable this for all writes.
=> [desktop] Flush file writes

docs/docs/self-hosting/guides/web-app.md
Did not move the [!IMPORTANT] section at the bottom like discussed, because I don't feel that would change the situation a lot. 
Also fixed the CMD command, the flags and serve url were wrong in the previous commit (wonder how it worked on local system, probably loaded wrong image in the compose.yaml)
=> [docs] minor fixes in web-apps hosting doc

auth/lib/ui/home_page.dart
Currently the "Ente Auth" text at the top of the mobile/desktop app is different in style to the one in the marketing images and the equivalent in the Photos app. So I just copied the style from the Photos app.
Marketing image:
Currently: (not the latest version of the app but the text part is the same except for the capitalization)
I haven't tested this.
=> [auth] Make "Ente Auth" at the top of app similar to marketing images/Photos app

server/ente/storagebonus/storge_bonus.go, server/pkg/controller/commonbilling/controller.go
Previously, we were only checking if the usage is less than newStorage + Paid Add Ons.
If the user also have referral bonus, we also need to calculate the new usable bonus based on the newStorage.
=> [server] Fix canDowngrade storage check

.github/workflows/server-publish.yml, server/docs/publish.md
Overwriting tags is clunky (besides being generally discouraged). e.g. pulling the overwritten tags locally requires `git fetch --force --tags`. So instead use the branch `server/ghcr` to point to the commit from which the latest published ghcr docker image has been built.
=> [server] Retain published image commit as branch instead of tag

server/cmd/museum/main.go
At times, Safari will fail our API responses because its CORS preflight fails. The errors are reproducible, but intermittently, and not on localhost.  We seem not to be the first ones to hit [this](https://github.com/processing/p5.js-web-editor/issues/3156).
Based on a hint from:
https://github.com/supabase/supabase/issues/20982#issuecomment-2548329565
Modify our CORS responses to use 200 instead of 204 to try and fix Safari.
=> [server] Add workaround for intermittent Safari CORS errors

.github/workflows/cli-release.yml, cli/Dockerfile, cli/Dockerfile-x86, cli/go.mod, cli/go.sum
feat: update to use go1.23
---
relates to https://github.com/Homebrew/homebrew-core/pull/201919 (homebrew side always use latest go for building the artifact)
also love a new cli release for some patches so that we can proceed with the homebrew PR
=> [cli] Switch to go v1.23

mobile/lib/ui/collections/album/vertical_list.dart
When adding/moving items to a newly created album from the vertical albums list sheet, after items are added, the app fails to navigate to the newly created album. This PR fixes this issue.
=> [mob][photos] Fix minor UX issue move/add to a newly created album

auth/lib/utils/directory_utils.dart
Fixes https://github.com/ente-io/ente/issues/4536 and https://github.com/ente-io/ente/issues/4464.
After opening the app on linux, my 1.3G cache folder remained intact.
Now the path resolves to `~/.cache/io.ente.auth` instead of `~/.cache`. [Under the hood](https://github.com/flutter/packages/blob/ca4671cc0f2d0a347db662144978f06ae9c017e8/packages/path_provider/path_provider_linux/lib/src/path_provider_linux.dart#L75-L82) it uses the app's ID and the `xdg_directories` package, so it will work when the user has `XDG_CACHE_HOME` set to something else.
=> [auth] Fix ~/.cache being deleted on linux

web/apps/photos/public/.well-known/apple-app-site-association
iOS sometimes falls back to opening Ente Photos app if Safari is disabled and AASA claims all paths even if a non-matching domain link is tapped. So making it more specific in AASA on what to open.
=> Update AASA to be more specific on what links to open

auth/assets/custom-icons/_data/custom-icons.json
Fixing the icon introduced in https://github.com/ente-io/ente/pull/4548
=> Fix Belo icon displaying as a violet square instead of the correct icon

mobile/lib/db/ml/db.dart, mobile/lib/services/machine_learning/ml_service.dart, mobile/lib/ui/viewer/file_details/face_widget.dart
Fixed bug where we showed "Face not clustered yet, please come back later" toast message even for faces which had a score too low to ever be clustered automatically.
=> [mob][fix] Enable face to person assignment for faces with low score

mobile/lib/utils/delete_file_util.dart, mobile/pubspec.yaml
On iOS, deletion fails without any error if a batch has at least one shared file. The only indicator that deletion failed is `List<String>` returned by `PhotoManager.editor.deleteWithIds` will be empty.
So if shared files are distributed pretty evenly across list of `localIDs` to be deleted, almost all batches would fail even with a batch size of 10 (which was the minimum batch size before this change). 
Recursively trying with a smaller batch size if the bigger batch size fails makes it possible to delete all non-shared local files with more system delete conformation dialogs though, but gets the work done for users blocked on this. 
```plaintext
[A, B, C, D, E]
└─ Attempt to delete; if failure:
├─ [A, B]
│  └─ Attempt to delete; if failure:
│     ├─ [A]
│     └─ [B]
└─ [C, D, E]
└─ …
```
=> [mob][photos] Use better batching when freeing up space in batches on iOS

web/apps/photos/package.json, web/docs/dependencies.md, web/packages/base/package.json, web/packages/new/package.json, web/yarn.lock
Broken in nightlies because of the recent react-dropzone update.
=> [desktop] Fix native thumbnail gen instead of using web fallback

docs/docs/self-hosting/guides/web-app.md
- Fixes link to `local.yaml`
- None
=> Fixed link in web-app self-hosting guide

server/ente/billing.go, server/pkg/middleware/rate_limit.go
I have tried to build ente server using the source and have found various bugs that in a 64bit system would not pose an issue but when ran on 32bit architecture would result in errors. After the fixes, Ente works beautifully.
I understand that Ente does not support 32bit architectures by nature and hence there would be no point in merging this PR and solving these issues but I have put this PR out there in hopes that it helps others run Ente on their own desired architecture. 
1. `billing.go` - `storage` variables are not properly typed as int64 despite them being able to hold more than the 32bit integer limit. On a 32bit system, this will lead to an integer overflow (especially with the default 5GB value). Typing them appropriately as an int64 will resolve this bug and have no impacts on …
=>  Fixes to make the source 32bit compatible

auth/assets/custom-icons/_data/custom-icons.json, auth/assets/custom-icons/icons/fastmail.svg
Add Fastmail logo for Ente Auth.
I've initially wanted to use the official logo available from https://www.fastmail.com/media-kit/ but I noticed you need SVG, so I went to https://commons.wikimedia.org/wiki/File:Fastmail_icon_2019.svg
Hexadecimal color is also from Logo guidelines (https://www.fastmail.com/assets/brand/Fastmail-Logo-Guidelines-March-2019-V1.pdf).
=> [Auth] Add Fastmail logo

web/packages/base/locales/ar-SA/translation.json, web/packages/base/locales/de-DE/translation.json, web/packages/base/locales/el-GR/translation.json, web/packages/base/locales/en-US/translation.json, web/packages/base/locales/es-ES/translation.json, web/packages/base/locales/fr-FR/translation.json, web/packages/base/locales/it-IT/translation.json, web/packages/base/locales/lt-LT/translation.json, web/packages/base/locales/nl-NL/translation.json, web/packages/base/locales/pl-PL/translation.json, web/packages/base/locales/pt-BR/translation.json, web/packages/base/locales/pt-PT/translation.json, web/packages/base/locales/ru-RU/translation.json, web/packages/base/locales/sv-SE/translation.json, web/packages/base/locales/uk-UA/translation.json, web/packages/base/locales/vi-VN/translation.json, web/packages/base/locales/zh-CN/translation.json
Crowdin apparently overrode them even when we selected the option to retain translations when changing the case and then manually fixing the case in their web UI.
=> [web] Restore translations for search

auth/lib/services/preference_service.dart, auth/pubspec.yaml
Resolves https://github.com/ente-io/ente/issues/4670 (confusion for users who upgrade or install the app on a new device)
=> [auth] Use issuerName as default sort key

auth/lib/onboarding/view/setup_enter_secret_key_page.dart
Fix #4683 
1. If the name of `issuer` is change the icon is updated accordingly
2. If the `issuer` name and the `custom icon` (from the icon picker) both are changed than the final icon is selected from the custom icon.
=> [auth] fix generic icon not updating when issuer name is changed

auth/assets/custom-icons/_data/custom-icons.json
Fix enom logo "slug"
Enom logo wasn't working
tested this edit on the desktop version and worked.
=> [auth] Fix logo for Enom

web/packages/new/photos/components/SearchBar.tsx
When the search bar was empty, previously we would show people suggestions. This
was accidentally circumvented; fix it.
=> [desktop] Fix regression causing people suggestions not to appear in empty state

cli/pkg/model/remote.go
The CLI sorts deleted photos to the bottom of the sync queue. 
When an album is synced, a photo is removed from the album and later re-added to the album (same name) and doing another sync the new file is added first and a new name is generated since the original filename is (still) taken. Afterwards the initial photo is deleted and the filename would be available.
This leads to having a file, e.g. IMG_0001_1.JPG instead of the original filename IMG_0001.JPG despite the initial filename is no longer on disk and could have been used.
This PR changes the sort order so that deleted files are first removed and afterwards new files are created. In this case all files where the filename is now available, but were taken, are named like they were uploaded.
=> [cli] sync deleted files before syncing new/updates files

desktop/.gitignore, desktop/docs/dependencies.md, desktop/electron-builder.yml, desktop/eslint.config.mjs, desktop/scripts/beforeBuild.js, desktop/scripts/magick.js, desktop/src/main/services/image.ts
- CI builds both arch binaries in one go, so the singular yarn install hook is not enough
- Without the extension windows doesn't run it
=> [desktop] IM 7 - Handle CI rebuilds, and add windows extension

desktop/package.json, desktop/yarn.lock
In particular,
* Electron 34 is needed to fix the Flatpak file picker issue -
"Fixed file chooser dialogs for flaptak applications. #44681"
https://github.com/electron/electron/pull/44681
* Electron builder 26 is needed for the FPM app armour profiles
https://github.com/electron-userland/electron-builder/issues/8635#issuecomment-2462586534
=> [desktop] Depedencies upgrade

desktop/package.json
Since the eb update, the CI job fails with errors like
unable to copy, file is symlinked outside the package  source=out/404.html realPathFile=/Users/runner/work/photos-desktop/photos-desktop/web/apps/photos/out/404.html
Error: Cannot copy file (xxx.js) symlinked to file (xxx.js) outside the package as that violates asar security integrity
at writeFileOrProcessSymlink (/Users/runner/work/photos-desktop/photos-desktop/desktop/node_modules/app-builder-lib/src/asar/asarUtil.ts:126:15)
=> [desktop] Update build for latest electron builder

desktop/build/io.ente.photos.appdata.xml, desktop/scripts/beforeBuild.js
...because of returning false from our build hook.
Also update the MetaInfo to avoid duplicating.
=> [desktop] Fix incomplete build being generated

desktop/electron-builder.yml
CI failures since updating Electron building (and Electron):
• packaging       platform=darwin arch=arm64 electron=34.0.0 appOutDir=dist/mac-universal-arm64-temp
• packaging       platform=darwin arch=universal electron=34.0.0 appOutDir=dist/mac-universal
⨯ pattern is too long  failedTask=build stackTrace=TypeError: pattern is too long
=> [desktop] Attempt to fix macOS universal build after electron builder update

web/apps/photos/src/components/Collections/AlbumCastDialog.tsx, web/packages/base/components/utils/theme.ts
This was causing an exception when opening screens with the <Link>
=> [web] Fix link default prop for the (WIP) light mode

server/pkg/repo/passkey/passkey.go
e.g.
--- at /etc/ente/pkg/api/user.go:352 (UserHandler.FinishPasskeyAuthenticationCeremony) ---
--- at /etc/ente/pkg/repo/passkey/passkey.go:395 (Repository.FinishAuthentication) ---
Caused by: Error validating the assertion signature: \u003cnil\u003e
Modifying the pk app to pass null as the signature, and observing that client gets back a 401 (previously 500).
=> [server] Report a client error instead of 5xx on invalid pk signature

auth/android/app/src/main/play/listings/en-US/full-description.txt, auth/fastlane/metadata/android/en-US/full_description.txt
Solves #4881, removing line breaks that break the text flow on F-Droid.
No code changes made.
=> Remove extra line breaks in Auth app descriptions

auth/assets/custom-icons/_data/custom-icons.json
I moved World Cube Association entry to the proper alphabetical place and added the "slug" line because icon is showing blank and I think that could be the reason.
If there's other common issues with blank SVG icons I would love to check it, because I've not touch the icon code and is showing in red for closing `</g>` but is showing fine in the viewer.
Sorry about this.
Regards
=> [auth] Update custom-icons.json

mobile/lib/ui/viewer/actions/file_selection_actions_widget.dart, mobile/lib/ui/viewer/file_details/face_widget.dart, mobile/lib/ui/viewer/people/people_page.dart, mobile/lib/ui/viewer/people/save_or_edit_person.dart, mobile/lib/ui/viewer/search/result/person_face_widget.dart
=> Person issue logs

auth/lib/ui/tools/lock_screen.dart
1. Logout button was hidden when user first opt for **Use without backup** and then **Log in** due the `hasOptedForOfflineMode` been set to true if we follow the above way , fixed by checking `isLoggedIn`
=> [auth] Fix logout button not showing on lockscreen

mobile/lib/services/filedata/model/file_data.dart, mobile/lib/utils/ml_util.dart
This will ensure that MLData that was already fetched is saved in the DB before running the ML pipeline on files that requires indexing.
=> [mob] Store remote ml data before scheduling processing

web/apps/photos/src/services/upload/takeout.ts, web/apps/photos/tests/upload.test.ts
In recent Google Takeout archives, the metadata JSON files are named
"${original_filename}.supplemental-metadata.json" instead of
"${original_filename}.json", as before.
I refactored the previous code so that `getMetadataJSONMapKeyForJSON()`
only removes the ".json" suffix from the metadata filename and does not
make any other changes. All of the filename munging is now done to the
name of the media file. That was the only way I could make the process
deterministic. As far as I can figure out, there's no deterministic way
of deriving the media filename from the metadata filename -- it's only
deterministic going from the media filename to the metadata filename.
These new names are still subject to the 46-character clipping limit,
with some specific rules about how the filename is clipped: …
=> Add support for Takeout's new .supplemental-metadata.json files

infra/staff/src/components/UpdateSubscription.tsx
/cc @vishnukvmd mentioned that the json Response does not include attributes data (like customerID, StripeAccountCountry) and it is skipped in the jsonResponse while updating the storage.
=> [staff] populate attributes from userDataResponse when UpdateStorage returns data

web/packages/new/photos/components/Tiles.tsx
When no thumbnail is shown, e.g. for empty uncat
=> [web] Tweak large tile gradient to work better in light mode

.github/workflows/auth-internal-release.yml, .github/workflows/mobile-internal-release.yml
=> [mob] Notify internal Discord when internal release is available on PlayStore

web/apps/auth/src/pages/_app.tsx, web/apps/photos/src/pages/_app.tsx, web/packages/shared/storage/localStorage/index.ts
From one customer's logs (Windows):
[rndr] [error] Unhandled promise rejection: Error: The user's token was present in local storage but not in IndexedDB
And thereafter the app started behaving erratically. Restarting fixed it. This
sequence happened during an app update.
This sequence is not reproducible, but adding as a extra precaution adding a
circuit breaker to prevent execution if IndexedDB is not readable.
=> [desktop] Add IndexedDB circuit breaker

server/cmd/museum/main.go, server/ente/errors.go, server/ente/family.go, server/pkg/api/family.go, server/pkg/controller/family/admin.go, server/pkg/controller/family/family.go, server/pkg/repo/family.go
Tested in followin cases 
1. various statuses "REJECTED", "REVOKED" and "SELF" etc
2. user not part of any family & admin user
3. storage limit check on bulk upload
4. reduce storage check 
5. set storage bigger than anything available in the world
6. admin shouldn't be able to set his own storage.
=> [server] API for modifying family member storage limit

server/pkg/controller/offer/offer.go, server/pkg/utils/billing/billing.go
From discord discussion
the pr makes changes to the error strings which are thrown when configuration reltaed to payment and billing isn't found. The error messages are changed so to not scare self hosters while we are aware of it on the production instance.
=> [server] Soft error msgs when billing/payment data(config) is not found

mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart, mobile/lib/services/magic_cache_service.dart
- For 14k files, this reduced the overall time to calculate discovery section from **1600ms** to **250ms**
- This should also reduce the memory overhead as we have reduce the number of times we are passing vector to different isolate.
=> [mob][perf] Improve computation for discover sections by batching lookup

mobile/lib/ui/tabs/home_widget.dart
This dialog. It was coming up when redirecting back to the app after passkey verification.
=> [mob][photos] Ensure that the shared data received through the intent is a photo or video before showing a dialog specific to shared photo/video.

web/Dockerfile
Sibling of https://github.com/ente-io/ente/pull/5364.
**Tested by**
```sh
docker build -t web-test .
docker run -it --rm -p 3000:3000 -p 3090:3002 -e ENTE_API_ORIGIN=http://localhost:8090 -e ENTE_ALBUMS_ORIGIN=http://localhost:3090 web-test
docker run -it --rm -p 3000:3000 -p 3002:3002 web-test 
```
=> [web] Make the endpoints configurable without rebuilding the image

web/Dockerfile
Workaround for the image build failing no the arm64 runners (it works fine on the amd64 runner): https://github.com/ente-io/ente/actions/runs/13962703146/job/39086814540
=> [web] Increase yarn install timeout

web/Dockerfile
try_files $uri/ matches the passkeys/ folder in accounts app, causing nginx to
try loading (e.g.)  http://localhost:3001/passkeys/?xxx instead of
http://localhost:3001/passkeys?xxx
The way Next is currently generating the static renders, we anyways don't need
the slug/index.html lookup, the only index.html we have is at the root, rest of
them are of the form slug.html.
=> [web] Dockerfile accounts fix

mobile/lib/services/location_service.dart
Previous condition didn't handle the case when the cities were not loaded when discovery section was getting computed.
=> [mob] Fix discovery section reload condition

mobile/lib/services/ignored_files_service.dart
Handle the case where some files were incorrectly ignored for upload because device reused deleted file name.
=> [mob] Improve ignored file identifier for android

server/quickstart.sh
Tested on macOS, Ubuntu (docker), Alpine (docker)
=> [server] Quickstart: don't rely on the -w flag for base64

.github/workflows/codeql.yml
Necessary to get GitHub to resync the status until the next time it runs
=> [meta] Allow running CodeQL manually

cli/pkg/admin_actions.go
Corrected "expirty" typo in ente admin update-subscription --no-limit False success workflow.
Fixed typo "expirty" to "expiry" in file limit success flow.
=> Correct typo in cli

desktop/src/main.ts, desktop/src/main/menu.ts, desktop/src/main/services/store.ts
Based on customer feedback. The dock icon will hide when the window is closed by using the "x" without quitting the app. 
The menu bar icon remains as it is, and so does the existing preferences (whose value is also retained if it were set explicitly).
=> [desktop] [macOS] Hide dock icon on Window close

server/pkg/repo/family.go
Users can create a family, leave it and then join another.
In the `families` table, there will be one entry for each such family they have been a part of (against their `admin_id`).
This PR removes this constraint for only a single row to be affected, so users who have historically been associated with more than one family can have a fresh start.
=> [server] Relax criteria for closing families

server/pkg/utils/config/config.go, server/scripts/deploy/museum.nginx.service
**Tested by**
Modifying the compose.yaml to provide an environment variable:
```diff
environment:
ENTE_CREDENTIALS_FILE: /credentials.yaml
+       ENTE_HTTP_USE_TLS: 1
```
then observing that museum is honoring it 
```
...
[GIN-debug] Listening and serving HTTPS on :443
```
=> [server] Update service definition for recent env var lookup changes

desktop/src/main.ts
Reverts ente-io/ente#5526. Like macOS, the double click interferes with the click event that shows the context menu on Linux too.
=> Revert "[desktop] Show/hide the window on tray icon double click on Linux/Win"

mobile/lib/services/magic_cache_service.dart, mobile/lib/services/memories_cache_service.dart, mobile/pubspec.lock
Fix incorrect cache reading for incorrect utf8 encoding for memories and magic cache.
=> [mob][photos] Caching fix

.github/workflows/desktop-lint.yml, .github/workflows/docs-deploy.yml, .github/workflows/docs-verify-build.yml, .github/workflows/infra-deploy-staff.yml, .github/workflows/infra-lint-staff.yml, .github/workflows/web-deploy-one.yml, .github/workflows/web-deploy-preview.yml, .github/workflows/web-deploy-staging.yml, .github/workflows/web-deploy.yml, .github/workflows/web-lint.yml, desktop/.github/workflows/desktop-release.yml, web/Dockerfile, web/apps/photos/package.json, web/docs/new.md, web/yarn.lock
Contributors do not necessarily need to update to node 22, I tested that the dev server works with node 20 also.
That said, if someone wishes to update - here is the dance I needed to do on macOS. Garnish to taste and OS.
```sh
brew uninstall node@20
brew install node@22
brew link node@22
corepack disable
corepack enable
```
=> [web] Node 20 => 22

docs/docs/photos/features/family-plans.md
The FAQ item mentions that it is not possible to set a storage quota for a family member, but this is possible since v1
=> Remove outdated FAQ item in family-plans.md

mobile/lib/core/constants.dart, mobile/lib/ui/tools/deduplicate_page.dart, mobile/lib/ui/viewer/file/thumbnail_widget.dart, mobile/lib/ui/viewer/gallery/component/gallery_file_widget.dart, mobile/lib/utils/standalone/task_queue.dart, mobile/pubspec.lock
Use a task queue to manage local thumbnail requests with cancellation, priority and timeout functionality.
This significantly improves the browsing experience of galleries with a large number of local thumbnails. Previously, scrolling down deep into a device folder would cause the thumbnails to take a long time to load. Now, the loading speed has improved considerably.
A `maxQueueSize` of 200 for `smallLocalThumbnailQueue` should be appropriate, as the maximum number of mounted `Thumbnailwidget`s is 186 when using a gallery grid size of 6 on a decently sized phone screen (the screen length is the relevant factor here). With a grid size of 6, the maximum number of mounted ThumbnailWidgets should be around 186 ± 12 for most phone screens.    
Note: Thumbnails for HEIC images on android …
=> [mob][photos] Use queue for more efficient fetching of local thumbnails

mobile/lib/l10n/intl_en.arb
- Replaces `zero` with `=0` to avoid syntax errors.
- Replaces `one` with `=1` in the context of a single item for better compatibility with non-English languages.
- Fixes grammar.
=> [mob] ICU syntax fix

mobile/lib/services/memory_home_widget_service.dart
Previously we were caching all the memories without a working limit, this PR fixes that.
=> [mob] fix: only cache at max 50 files for memory widget

docs/docs/auth/migration-guides/authy/index.md
This pull request adds mention of the Authy-iOS-MiTM method to Ente's documentation on migrating from Authy. Currently, the only working method to import Authy tokens into Ente is to use a rooted Android device, which is not ideal due to most people not having rooted Android devices. The Authy-iOS-MiTM method (that I made) only requires an iOS device with Authy and a computer with Python and mitmproxy, making it significantly more accessible to people looking to migrate their Authy tokens. By mentioning my method in Ente's Authy import docs, it would help more people discover it and would hopefully make some people's lives easier since they wouldn't have to manually re-register 2FA on every website. Let me know if you have any questions.
N/A, this pull request does not modify any code
=> [docs] Update Authy import docs to mention Authy-iOS-MiTM

server/Dockerfile
Suggested twice:
- https://github.com/ente-io/ente/pull/3952
- https://github.com/ente-io/ente/issues/5631
Fixes: https://github.com/ente-io/ente/issues/5631
**Tested by**
Theory: On a clean alpine container, ran `apk add libsodium` then visually glanced using
`docker container diff` that the .so is the only relevant file.
Practice: Recreated the local Docker compose using this updated file and
verified that server runs and can upload files etc.
=> [server] Copy only libsodium lib to Docker image

auth/assets/custom-icons/icons/bingx.svg
the bingx icon added in #5186 was displayed as black.
i fixed the source using [this code](https://github.com/Bl4ckspell7/svg-css-to-inline-styling)
|  | old | fixed |
|-------|-------|------|
| light |![Screenshot From 2025-04-16 14-14-13](https://github.com/user-attachments/assets/ce0d1226-c82a-4e1b-a0d0-4a34839e8dce)|![Screenshot From 2025-04-16 14-19-36](https://github.com/user-attachments/assets/c8955cbd-7917-49dc-9c1f-24764da37765)|
| dark |![Screenshot From 2025-04-16 14-07-42](https://github.com/user-attachments/assets/dfeec407-6a32-40c4-a57f-fbf728406238)|![Screenshot From 2025-04-16 14-09-55](https://github.com/user-attachments/assets/3742dd50-deb2-474d-920f-f34d707983d6)|
=> [auth] fix bingx icon

mobile/lib/models/ffmpeg/ffprobe_props.dart, mobile/lib/ui/common/linear_progress_dialog.dart, mobile/lib/ui/tools/editor/video_crop_page.dart, mobile/lib/ui/tools/editor/video_editor_page.dart, mobile/lib/ui/tools/editor/video_rotate_page.dart, mobile/lib/ui/tools/editor/video_trim_page.dart
- #### Better UX on exporting an edited video
If a video is large enough (even an 8s 4k video), the export process can take a while. Previously, we were only showing a 'Saving edits...' message in a dialog, which gave users no indication of how much time it would take and some even thought the app was stuck. I’ve resolved this by adding a linear progress indicator to show the progress.
https://github.com/user-attachments/assets/b078337f-0e29-4738-a8b6-f8f94474a4c8
- #### Fix video previewing in a flipped state upon opening video editor (Bug exists only android).
=> [mob][photos] Video editor improvements

desktop/src/main/services/ffmpeg.ts, desktop/src/main/stream.ts, web/packages/gallery/services/video.ts, web/packages/gallery/utils/native-stream.ts
Four cases:
H.264, <= 10 MB             - Skip
H.264, <= 4000 kb/s bitrate - Don't re-encode video stream
<= 2000 kb/s bitrate        - Don't apply the scale+fps filter
!BT.709                     - Apply tonemap (zscale+tonemap+zscale)
Example invocation:
ffmpeg -i in.mov -vf 'scale=-2:720,fps=30,zscale=transfer=linear,tonemap=tonemap=hable:desat=0,zscale=primaries=709:transfer=709:matrix=709,format=yuv420p' -c:v libx264 -c:a aac -f hls -hls_key_info_file out.m3u8.info -hls_list_size 0 -hls_flags single_file out.m3u8
=> [desktop] HLS gen - WIP - Part x/x

mobile/lib/ui/home/loading_photos_widget.dart
```
FlutterError (A ValueNotifier<bool> was used after being disposed.
Once you have called dispose() on a ValueNotifier<bool>, it can no longer be used.)
[sentry.platformError] #0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:183:9)
1  ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:190:6)
change_notifier.dart:190
2    ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:416:27)
change_notifier.dart:416
3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:559:5)
change_notifier.dart:559
4      _LoadingPhotosWidgetState.initState.<anonymous closure> (package:photos/ui/home/loading_photos_widget.dart:42:25)
```
=> [mob] Fix: Add missing check for widget mount

.github/workflows/auth-release.yml
=> [workflow] revert to ubuntu 22.04 runner for auth-release

server/quickstart.sh
When docker is present but docker compose is not present, the `docker compose` invocation would fail. We want the early exit (`set -e`), so instead do a fallback to set dcv to an empty string so that it later fails in the `test -z dcv` case below and prints the intended error message.
=> [quickstart] Gracefully handle case when docker compose is not present

web/apps/photos/src/styles/photoswipe.css
`text-align: right` causes the ellipsizing to sometimes work, sometimes not, depending on the exact contents of the line (tested in current Chrome). Tweak the design to work with the normal text align to try and ensure the elision is always ellipsized.
=> [web] Ensure ellipsizing of caption

web/packages/gallery/components/viewer/photoswipe.ts
Fixes: https://github.com/ente-io/ente/discussions/5802
=> [web] Ensure copy as PNG option is reset when we get the original

.github/workflows/auth-release.yml
After last change the checksum name also need to changed to suffice the new files and the unified ubuntu workflow. Here I am modifying the checksum so that there are two different versions, one for linux related binaries and another for the solo apk file.
=> [workflow](auth-release) separate checksum as *-linux & *-apk

web/apps/photos/src/utils/file/index.ts
Tested on Safari (obv) and Chrome.
=> [web] Add workaround for Safari live photo download

mobile/lib/l10n/l10n.dart, mobile/lib/ui/common/date_input.dart, mobile/lib/ui/settings/language_picker.dart, mobile/lib/ui/viewer/date/edit_date_sheet.dart
- For language only match, instead of returning supported locale which many times doesn't have country code, we are now falling back to system locale. So for en_GB, the auto-detected locale will be `en_GB` instead of just `en`.
Fixes https://github.com/ente-io/ente/issues/5120
- Verified that the app was translated in Spanish with `es_US`.
- Verified that date-formatting is as per device locale (at least on birthday date picker & edit time dialog)
=> [mob] Fix date-formatting as per device locale

desktop/src/main/services/ffmpeg-worker.ts
Otherwise video conversion fails with
[Parsed_zscale_2 @ 0x12de1b040] code 3074: no path between colorspaces
Some sample video stream lines of videos where it failed:
- `Stream #0:0[0x1](und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 640x480 [SAR 1:1 DAR 4:3], 2204 kb/s, 30 fps, 30 tbr, 30 tbn (default)`
- `Stream #0:1[0x1e0]: Video: mpeg1video, yuv420p(tv), 640x480 [SAR 1:1 DAR 4:3], 104857 kb/s, 25 fps, 25 tbr, 90k tbn`
- `Stream #0:0: Video: mjpeg (Baseline) (MJPG / 0x47504A4D), yuvj422p(pc, bt470bg/unknown/unknown), 640x480, 15379 kb/s, 30 fps, 30 tbr, 30 tbn`
- `Stream #0:0[0x1](eng): Video: h263 (s263 / 0x33363273), yuv420p, 176x144 [SAR 12:11 DAR 4:3], 96 kb/s, 15.27 fps, 15.42 tbr, 15750 tbn (default)`
=> [desktop] Use a tighter HDR check

mobile/lib/states/all_sections_examples_state.dart, mobile/lib/ui/tabs/shared_collections_tab.dart
- Defer the initial load until the Shared Collection tab is in view to avoid unnecessary work at app startup.
- Remove the computation previously done for the Search tab sections that was intended for the Contacts section, as it is no longer present.
=> [mob][photos] Contacts section performance improvements

mobile/lib/utils/file_uploader.dart
The value of this variable was incorrectly set to `false` (as as initial value).
=> [mob] Fix: Clean up origin file for hard upload failures

mobile/lib/ui/viewer/file/video_widget_native.dart
Bug: When filePath was not null due to preview playlist, we kept playing the preview video, and where not showing any progress indicator for video download.
Tested locally on physical device.
=> [mob] Fix: Switch to original video playback for android

desktop/src/main/services/ffmpeg-worker.ts
`$` eol should match both `\r\n` (windows) and `\n` (rest)
=> [desktop] Fix HLS regex for Windows

mobile/android/app/src/main/AndroidManifest.xml, mobile/android/app/src/main/res/xml/data_extraction_rules.xml
As it breaks ente photos anyway because of KeyStore AFAICT 
Tries to fix #6027
=> [mob] Explicitly exclude app data during D2D backup/transfer

mobile/lib/utils/file_uploader.dart
- If user has two different local files which are exact duplicate, we upload them two different files. This to ensure any modification in the local asset via third party gallery only update one of the asset on Ente.
- As we use special localID for shared files (filePath-randomUUID), if the user shares same file to ente multiple times, we treat them as two different local asset. This result in duplicate uploads.
**Change**
- For files that are shared to Ente, avoid re-uploading if there's any file that belongs to the user with same hash, even if they have different local identifier.
**Unhandled edge case**
- If the shared files are not uploaded, and picked up parallely for upload, we will end up uploading duplicates. I don't see the need to handle this case.
=> [mob] Fix: Treat sandbox file as unique file during upload

auth/assets/custom-icons/_data/custom-icons.json, auth/assets/custom-icons/icons/girad.svg
Add GIRAD custom icon, as requested here: https://github.com/ente-io/ente/issues/6075
=> [auth] Add GIRAD icon 

server/cmd/museum/main.go, server/ente/billing.go, server/mail-templates/customer_hello.html, server/migrations/99_add_upgraded_at.down.sql, server/migrations/99_add_upgraded_at.up.sql, server/pkg/controller/billing.go, server/pkg/controller/email/email_notification.go, server/pkg/controller/stripe.go, server/pkg/repo/billing.go, server/pkg/repo/user.go, server/pkg/utils/time/time.go
Update the `subscriptions` table to store the time at which subscriptions were upgraded (`upgraded_at`).
Reach out to customers who upgraded 7 days ago to make sure all is well.
Store this information within `notification_history` so they are not contacted again (in case of admin interventions).
> Note: We will not be back-filling data for existing subscriptions.
=> [server] Check in with paid customers

mobile/lib/ui/collections/album/new_row_item.dart
There is an annoyingly flashing dialog when creating exiting a newly created album. The solution is to close the new-album-dialog before entering the album so that it is not visible anymore when leaving the album again.
The dialog is closed after the album is created and before routing to the album. An alternative is to close it directly when tapping on the Create button, but then the dialog disappears and it might take a while until the album is opened which feels worse.
Old (note how the dialog is still open when leaving the album):
https://github.com/user-attachments/assets/e57d27af-2339-4ba7-a5d8-be052aede99c
New (note how there is no dialog when leaving the album):
https://github.com/user-attachments/assets/874164a3-9550-4fc3-9144-342b5888dbb7
I don't know how to add tests for this.
=> [photos][mob] Fix: Close input dialog after album creation

mobile/lib/ui/collections/collection_action_sheet.dart, mobile/lib/ui/viewer/search/search_widget.dart
Previously, when searching for e.g. `test ` would not find an album called `test`. That's because the trailing whitespace is not ignored. On mobile this can be especially annoying because sometimes auto-completion automatically inserts whitespace after a word.
This patch trims whitespace of the search query in two places:
* When searching for an album name when moving photos to an album.
* When using the global search.
=> [photos][mob] Trim whitespace from search query

mobile/lib/generated/intl/messages_sr.dart, mobile/lib/module/upload/service/multipart.dart, mobile/lib/ui/viewer/people/link_email_screen.dart, mobile/lib/ui/viewer/people/person_selection_action_widgets.dart
While linking contact to a person, we were not gracefully handling the error where email id is already mapped to another person. And when such person doesn't have any face attached, they don't have any way to unlink the email from that person entity.
=> [mob] Fix: Handle already linked email err

mobile/lib/ui/collections/album/new_row_item.dart
Previously, newly created albums could easily end with trailing whitespace, especially when using auto-completion that automatically adds the next space character. It's not super bad obviously, but I found it slightly annoying. I can't think of any good reason for why an album name should ever start or end with whitespace.
=> [photos][mob] Trim whitespace from new album name

mobile/lib/ui/tabs/home_widget.dart
Previously, back navigation would always go to the home screen, even when albums are currently selected. This is unexpected because typically back navigation first deselect everything if anything is selected.
This patch implements this expected behavior for albums on the second tab. If at least one album is selected, all will be deselected when going-back. Only when everything is deselect, the app transitions to the first tab like before.
=> [photos][mob] Deselect albums with back navigation in second tab

mobile/lib/ui/tabs/home_widget.dart
Opening public link within the app opens the collection twice, adding logs to investigate the root cause.
=> [mob] Log event source for public link handling

mobile/lib/services/video_preview_service.dart, mobile/lib/ui/viewer/people/person_face_widget.dart
During testing, i noticed a log saying the ML lock is denied because stream is getting generated. I hadn't enabled video streaming on that device.
=> Fix: Do not request compute lock if streaming is disabled

desktop/src/main/services/ml-worker.ts, web/apps/photos/src/components/FileList.tsx, web/apps/photos/src/components/FileListWithViewer.tsx, web/apps/photos/src/components/Sidebar.tsx, web/apps/photos/src/pages/gallery.tsx, web/apps/photos/src/pages/shared-albums.tsx, web/apps/photos/src/types/gallery/index.ts, web/apps/photos/tests/upload.test.ts, web/packages/gallery/services/file-data.ts, web/packages/new/photos/components/gallery/reducer.ts, web/packages/new/photos/services/ml/index.ts, web/packages/new/photos/services/pull.ts, web/packages/new/photos/services/user-details.ts
Keep some leeway so that the first CLIP query in a session also gets resolved (on app starts after the model has been downloaded).
=> [desktop] Improve first CLIP query behaviour

server/quickstart.sh
This PR fixes the infinite looping due to mc config not being found in latest server images, which is replaced in favor of mc alias set, responsible for creating buckets in post_start hook. This should fix the issue that users run into while using our quickstart script
=> [server][quickstart] migrate to mc alias set for creating bucket

mobile/lib/generated/intl/messages_ar.dart, mobile/lib/generated/intl/messages_de.dart, mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/intl/messages_es.dart, mobile/lib/generated/intl/messages_fr.dart, mobile/lib/generated/intl/messages_id.dart, mobile/lib/generated/intl/messages_it.dart, mobile/lib/generated/intl/messages_ja.dart, mobile/lib/generated/intl/messages_lt.dart, mobile/lib/generated/intl/messages_nl.dart, mobile/lib/generated/intl/messages_no.dart, mobile/lib/generated/intl/messages_pl.dart, mobile/lib/generated/intl/messages_pt.dart, mobile/lib/generated/intl/messages_pt_BR.dart, mobile/lib/generated/intl/messages_pt_PT.dart, mobile/lib/generated/intl/messages_ro.dart, mobile/lib/generated/intl/messages_ru.dart, mobile/lib/generated/intl/messages_tr.dart, mobile/lib/generated/intl/messages_uk.dart, mobile/lib/generated/intl/messages_vi.dart, mobile/lib/generated/intl/messages_zh.dart, mobile/lib/generated/l10n.dart, mobile/lib/l10n/intl_en.arb, mobile/lib/ui/settings/ml/machine_learning_settings_page.dart
"Indexing is paused. It will automatically resume when device is ready."
"Indexing is paused. It will automatically resume when the device is ready. The device is considered ready when its battery level, battery health, and thermal status are within a healthy range."
=> [mob][photos] Better copy for describing why device is not ready for local indexing

mobile/apps/photos/lib/utils/delete_file_util.dart
If the number of files to be deleted exceeds 20,000, the deletion will be performed in batches, with a maximum of 20,000 files per batch. If a batch of 20,000 files fails, it will retry with 10,000 files (half the previous batch size). If failures continue, the batch size will keep reducing until it is over 2,000 files.
Tested and works as expected.
=> [mob][photos] Fix free up space failing when trying to delete lot of files at one shot

mobile/apps/photos/lib/ui/viewer/gallery/hooks/pick_person_avatar.dart, mobile/apps/photos/lib/ui/viewer/people/people_page.dart
Prevent showing duplicate files in people page due to a face getting incorrectly tagged when a correct face is already there.
=> [mob][photos] Fix duplicate people files

mobile/apps/photos/lib/services/collections_service.dart
If others file contains two files with same hash, we are returning same FileID twice for add or copy operation. This change fixes that behaviour.
=> [mob/photos] [fix] Handle duplicate fileID during addOrCopy

server/migrations/102_trash_vaccume_and_analyze_threshold.down.sql, server/migrations/102_trash_vaccume_and_analyze_threshold.up.sql
Attempt to increase refresh rate for autovacuum to ensure that the query planner use the index.
Based on slow query logs, and analyze command, it looks like the index is not being used because the table stats are out of date. And the default auto_vacumm only runs after 10% of rows have changed. 
Tested on local machine.
```
SELECT unnest(reloptions) AS option
FROM pg_class
WHERE relname = 'trash';
```
Once deployed, will monitor slow query logs and CPU usage.
=> [server][db] Tweak autovacuum threshold for trash table

mobile/apps/auth/lib/app/view/app.dart, mobile/apps/auth/macos/Runner/AppDelegate.swift
After closing app or hidding the window on macos the dock icon still appears even when the app is in tray which shouldn't happen this fixes it
=> [auth] Auto hide dock icon macos

mobile/apps/photos/lib/ui/viewer/file/zoomable_image.dart
On Android 16 with flutter upgrade, we are seeing  `Could not decompress image.` error for heic images taken from Iphone 16.
Instead of showing broken image, rendering the compressed version of the image on UI.
Also, increased the minWidth/minWidth from default 1920/1080 to 8000/800
Refer: https://pub.dev/packages/flutter_image_compress#minwidth-and-minheight
> If your image width is smaller than minWidth or height smaller than minHeight, scale will be 1, that is, the size will not change.
```
E/FlutterJNI( 7914): Failed to decode image
E/FlutterJNI( 7914): java.io.IOException: getPixels failed with error invalid input
E/FlutterJNI( 7914):     at android.graphics.ImageDecoder.nDecodeBitmap(Native Method)
E/FlutterJNI( 7914):     at …
```
=> [mob] Gracefully handle decompress image exception

mobile/apps/auth/lib/utils/lock_screen_settings.dart
When switching between tabs on mobile, a white flash appear when lockscreen is enable.
This PR fixes that by setting the background color to black for both light and dark theme.
=> [auth] Show black color as default background color for privacy-screen

server/config/compose.yaml
this pins the postgres container to a specific version of debian to prevent issues with updated glibc in newer deb release
https://github.com/docker-library/postgres/issues/1356
=> pin to specific release of debian to avoid collation mismatch

cli/cmd/admin.go, cli/internal/api/admin.go, cli/pkg/admin_actions.go, docs/docs/self-hosting/installation/config.md, server/configurations/local.yaml, server/pkg/utils/email/email.go
Implement TLS/SSL encryption for sending emails via SMTP. When an SMTP provider explicitly requires TLS/SSL communication the current implementation runs in a timeout and fails. A new configuration parameter for smtp was added to enable TLS/SSL communication.
This would solve #5958 
I built a local docker image of my branch. The email provider I was using is mailbox.org and using the tls configuration. Registering a new user then resulted in a sent email containing the verification code.
I did not test a setup without TLS/SSL.
=> [server] Add optional TLS/SSL encryption for SMTP

mobile/apps/photos/lib/ui/viewer/gallery/component/gallery_file_widget.dart
Using `ColorFiltered` with `Blendmode.darken` introduces a performance [issue](https://github.com/flutter/flutter/issues/174118) with flutter's new rendering engine Impeller. 
The fix uses an alternative method to that maintains the same UI appearance as before.
=> [mob][photos] Fix jank when scrolling gallery when lot of selected items are in view

mobile/apps/photos/lib/ui/viewer/file/thumbnail_widget.dart
In Gallery, even if thumbnails are stored in LRU cache, there was a delay in rendering thumbnails when scrolling fast enough. Pre-caching these thumbnails to flutter's `ImageCache` right before they're rendered has made the rendering fast enough for seamless UX.
https://github.com/user-attachments/assets/c47958fb-fbda-4e1f-9ce7-26b51ca87938
https://github.com/user-attachments/assets/cbaf4427-f52f-4544-a0c2-820eb2b43953
=> [mob][photos] Pre-cache thumbnails fetched from LRU cache to Flutter's ImageCache for faster rendering

mobile/apps/auth/assets/custom-icons/_data/custom-icons.json, mobile/apps/auth/assets/custom-icons/icons/activision.svg
Reverts ente-io/ente#6950
I rushed a bit, sorry. The PR wasn't meant to be merged yet (if ever) and it won't work right now anyway. It was meant to create conversation on the topic and then possibly merged and there may be concerns to this as a company may not want their logo/wordmark altered but I'm not well versed in this topic (idk maybe I'm overthinking this).
Discussion: #6951
=> Revert "[auth] Add smaller Activision icon"

mobile/apps/photos/lib/services/video_preview_service.dart, mobile/apps/photos/lib/ui/viewer/file/file_app_bar.dart
- Modified `_checkFileForPreviewCreation` method to accept `isManual` parameter
- Bypass 500MB file size and 60 second duration limits when user manually triggers video stream processing
- Maintains size/duration restrictions for automatic streaming to preserve device performance
=> [mob][photos] bypass size/duration limits for manual video stream requests

mobile/apps/locker/lib/app.dart, mobile/apps/locker/lib/main.dart
DynamicFAB theme was not getting applied from the commons package. This PR fix that issue.
**Before**
**After**
=> [locker] Refactor theme handling in Locker to fix DynamicFAB style

mobile/apps/photos/lib/db/ml/db.dart, mobile/apps/photos/lib/services/machine_learning/compute_controller.dart
- Add ability to block computeController temporarily
- Block computeController when vectorDB migration is running
=> [mob][photos] Run vectorDB migration is memory safe way

mobile/apps/locker/android/app/src/main/AndroidManifest.xml, mobile/apps/locker/android/app/src/main/kotlin/io/ente/locker/MainActivity.kt, mobile/apps/locker/lib/l10n/app_en.arb, mobile/apps/locker/lib/l10n/app_localizations.dart, mobile/apps/locker/lib/l10n/app_localizations_en.dart, mobile/apps/locker/lib/ui/settings/security_section_widget.dart, mobile/packages/lock_screen/lib/lock_screen_settings.dart
Authentication service was not working on android as  `local_auth` requires the use of a `FragmentActivity` instead of an `Activity` in `MainActivity.kt` 
Also updated `AndroidManifest.xml` file to include the USE_BIOMETRIC permissions:
=> [locker] Fix authentication not popping up on android

mobile/apps/photos/lib/ui/sharing/manage_links_widget.dart, mobile/apps/photos/lib/ui/sharing/qr_code_dialog_widget.dart, mobile/apps/photos/lib/ui/sharing/share_collection_page.dart, mobile/apps/photos/pubspec.yaml
- Add QR code sharing feature for album links behind internal user flag
- Integrate QR option in manage links and share collection pages  
- Auto-close dialog after share operation for better UX
- **New QrCodeDialogWidget**: Custom dialog with album name, QR code, and ente branding
- **Share functionality**: Captures QR as image and shares with album context
- **Feature gating**: Hidden behind `flagService.internalUser` for internal testing
- **UI integration**: Available in both share collection page and manage links page
- **Dependencies**: Added `qr_flutter: ^4.1.0` for QR generation
- ✅ QR code generation works for album URLs
- ✅ Share functionality captures and exports QR as image
- ✅ Dialog auto-closes after share operation
- ✅ Feature properly hidden behind internal user flag
- ✅ …
=> [mob][internal] Add QR code sharing feature for album links

docs/docs/self-hosting/administration/object-storage.md
This change was prompted by a support question in the self-hosted Discord channel[1], where users struggled to find this information. Previously, the details were only available in the installation guide, which users typically don't revisit when trying to enable features post-installation.
[1] https://discord.com/channels/948937918347608085/1414631496039403712
=> docs: Add details on enabling replication

mobile/apps/photos/ios/Podfile.lock, mobile/apps/photos/lib/core/cache/image_cache.dart, mobile/apps/photos/lib/core/cache/lru_map.dart, mobile/apps/photos/lib/core/cache/thumbnail_in_memory_cache.dart, mobile/apps/photos/lib/core/configuration.dart, mobile/apps/photos/lib/services/account/user_service.dart, mobile/apps/photos/scripts/internal_changes.txt
Description:
- Allow logout to proceed locally when server call fails with custom endpoints
- Add comprehensive cache clearing on logout (in-memory, service, and video caches)
- Clear volatile password and temporary directories during logout
- Preserve strict error handling for production endpoints
Tests:
=> [mob][photos] improve logout handling

.gitignore
- Added pattern to ignore CLAUDE.local.md files anywhere in the repository
- Uses `**/CLAUDE.local.md` pattern to match files in root and all subdirectories
=> [ente] Add CLAUDE.local.md to gitignore

mobile/apps/photos/lib/services/video_preview_service.dart, mobile/apps/photos/scripts/internal_changes.txt
Description:
- Fixes infinite retry loop when network is unavailable during video preview generation
- Improves log levels to reduce noise in production
Tests:
=> [mob][photos] stop processing streams on network issues

mobile/apps/photos/lib/services/account/user_service.dart, mobile/apps/photos/lib/ui/collections/album/row_item.dart, mobile/apps/photos/lib/ui/components/buttons/chip_button_widget.dart, mobile/apps/photos/lib/ui/home/memories/memory_cover_widget.dart, mobile/apps/photos/lib/ui/sharing/share_collection_page.dart, mobile/apps/photos/lib/ui/tools/similar_images_page.dart, mobile/apps/photos/lib/ui/viewer/search/result/people_section_all_page.dart, mobile/apps/photos/lib/ui/viewer/search_tab/people_section.dart, mobile/apps/photos/scripts/internal_changes.txt
Use of the `ColorFiltered` flutter widget appears to give issues for HEIC files viewed on Android, where their meta data seems to make the widget flip the child. In this case, it means image thumbnails were getting flipped on selection. Fixed the issue by no longer using the `ColorFiltered` widget and instead relying on a simple combo of Stack and Container with background color. 
Tested in debug mode on my pixel phone, for all UI changes involved.
=> [mob][photos] Fix issue with flipped thumbnails
