ente-io/ente

web/apps/photos/src/components/pages/gallery/PreviewCard.tsx
Fixes: https://github.com/ente-io/ente/issues/3293
=> [web] Show checkbox on hover

cli/internal/api/authenticator.go, cli/internal/api/models/authenticator.go, cli/main.go, cli/pkg/mapper/authenticator.go, cli/pkg/model/constants.go, cli/pkg/secrets/key_holder.go, cli/pkg/sync.go, cli/pkg/sync_authenticator.go
=> [cli] Add support for exporting Ente authenticator codes

auth/pubspec.yaml
=> [auth] Bump version v3.1.8

cli/main.go
=> [cli] Bump version

.github/workflows/auth-release.yml
=> [infra] Use JAVA 17 for auth release workflow

auth/pubspec.yaml
=> [auth] Bump auth version

server/cmd/museum/main.go, server/pkg/controller/file.go
=> [server] Slow down crons

server/pkg/controller/filedata/delete.go
=> [server] Increase waittime on delete error

docs/docs/auth/migration-guides/export.md
=> [docs] Update auth export.md

mobile/lib/ui/home/grant_permissions_widget.dart
This was added to debug an issue. The issue is resolved, so removing it.
=> [mob][photos] Remove trigger to send logs from grant permissions screen

web/apps/photos/src/components/PhotoFrame.tsx, web/packages/new/photos/services/download.ts
Fixes: https://github.com/ente-io/ente/issues/2581
=> [web] Transcode videos if they are smaller than 100 MB

mobile/lib/generated/intl/messages_fr.dart, mobile/lib/generated/intl/messages_id.dart, mobile/lib/generated/intl/messages_it.dart, mobile/lib/generated/intl/messages_pl.dart, mobile/lib/generated/intl/messages_sv.dart, mobile/lib/services/search_service.dart, mobile/pubspec.yaml
=> [mob] HotFix: Show discover section for all users

mobile/lib/ui/settings/lock_screen/custom_pin_keypad.dart
=> [mob][photos] Add onPressed State Color for Custom Keyboard in App Lock

auth/lib/ui/settings/lock_screen/custom_pin_keypad.dart
=> [auth] Add onPressed color for Custom Keyboard in App Lock

cli/main.go, cli/pkg/mapper/authenticator.go
=> [cli] Handle decryption for new libsodium wrapper

docs/docs/photos/features/referral-program/index.md
=> [doc] Update Referral.md

web/apps/photos/src/utils/billing/index.ts, web/packages/base/locales/en-US/translation.json
This title is not adding anything to the dialog
=> [web] Remove unnecessary translation

desktop/CHANGELOG.md
https://github.com/ente-io/ente/pull/3319
=> [desktop] Add CHANGELOG entry for shared export

auth/lib/locale.dart, auth/lib/ui/settings/language_picker.dart
=> [auth][l10n]: Add Bulgarian translation

auth/lib/models/code.dart, auth/lib/ui/code_widget.dart, auth/lib/ui/settings/security_section_widget.dart
=> [auth] Minor fixes 

docs/docs/auth/faq/index.md
=> Update auth faq.md

mobile/lib/models/metadata/file_magic.dart
=> [mob] Safe parse h/w from public magicMetadata

web/apps/photos/src/pages/gallery.tsx, web/packages/base/locales/en-US/translation.json
- Stay on empty albums after ops
- Modify empty state message
=> [web] Empty state tweaks

auth/lib/l10n/arb/app_en.arb, auth/lib/ui/settings/security_section_widget.dart
=> [auth] Request authentication to view passkeys

auth/lib/models/code.dart, auth/lib/ui/code_widget.dart, auth/pubspec.yaml
=> [auth] Misc bugs fix

mobile/lib/services/machine_learning/semantic_search/clip/clip_image_encoder.dart, mobile/lib/utils/image_ml_util.dart, mobile/plugins/onnx_dart/android/src/main/kotlin/io/ente/photos/onnx_dart/OnnxDartPlugin.kt, mobile/plugins/onnx_dart/lib/onnx_dart.dart, mobile/plugins/onnx_dart/lib/onnx_dart_method_channel.dart, mobile/plugins/onnx_dart/lib/onnx_dart_platform_interface.dart
Switched to new clip ONNX model on mobile, where preprocessing is done inside ORT. This means it's more performant and more advanced image processing.
Tested in debug mode on my Pixel 8.
=> Clip with preprocessing inside ONNX on mobile

auth/lib/onboarding/view/onboarding_page.dart, auth/lib/services/preference_service.dart, auth/lib/ui/settings/security_section_widget.dart, auth/lib/ui/settings_page.dart
=> [auth] Auth minor improvements & bug fixes

auth/lib/locale.dart, auth/lib/ui/settings/language_picker.dart
=> [auth] Enable l10n for Vietnamese, Arabic, Greek, & Slovak

web/apps/photos/src/components/Collections/GalleryBarAndListHeader.tsx, web/apps/photos/src/components/PhotoFrame.tsx, web/apps/photos/src/components/PhotoViewer/FileInfo/index.tsx, web/apps/photos/src/components/PhotoViewer/index.tsx, web/apps/photos/src/pages/gallery.tsx, web/packages/new/photos/components/Gallery/BarImpl.tsx, web/packages/new/photos/components/Gallery/PeopleHeader.tsx, web/packages/new/photos/components/PeopleList.tsx, web/packages/new/photos/services/ml/cluster.ts, web/packages/new/photos/services/ml/index.ts, web/packages/new/photos/services/ml/people.ts, web/packages/new/photos/services/ml/worker-types.ts, web/packages/new/photos/services/ml/worker.ts
Nearing readiness for beta release
=> [desktop] People - Enable for internal

web/apps/photos/src/components/Collections/GalleryBarAndListHeader.tsx, web/apps/photos/src/pages/gallery.tsx, web/packages/new/photos/components/Gallery/BarImpl.tsx, web/packages/new/photos/components/Gallery/PeopleHeader.tsx, web/packages/new/photos/components/Gallery/index.tsx, web/packages/new/photos/components/ItemCards.tsx, web/packages/new/photos/components/PeopleList.tsx, web/packages/new/photos/services/download.ts, web/packages/new/photos/services/ml/index.ts
=> [desktop] People - Empty state

mobile/lib/services/machine_learning/ml_service.dart, mobile/lib/services/magic_cache_service.dart, mobile/lib/utils/file_uploader_util.dart
=> [mob] Fix: Enable video upload without thumbnail for shared files

docs/docs/auth/migration-guides/authy/index.md
=> Update Authy Migration formatting

desktop/CHANGELOG.md, web/apps/photos/src/services/upload/takeout.ts, web/apps/photos/src/services/upload/upload-service.ts, web/packages/new/photos/types/file.ts
Fixes https://github.com/ente-io/ente/issues/3537
=> [web] Parse description from Google Takeout metadata JSON

web/packages/accounts/pages/verify.tsx, web/packages/accounts/services/redirect.ts
Ref: 59bf51346cd01e17f07d93c100ffab423a07cb54
=> [web] Fix recover redirect

mobile/ios/Podfile, mobile/ios/Podfile.lock, mobile/ios/Runner.xcodeproj/project.pbxproj, mobile/lib/ui/common/web_page.dart, mobile/lib/ui/payment/payment_web_page.dart, mobile/lib/ui/tools/collage/collage_save_button.dart, mobile/lib/ui/tools/editor/image_editor_page.dart, mobile/pubspec.lock, mobile/pubspec.yaml
Checked for any regressions.
Read through and checked all breaking changes in change logs of updated dependencies.
=> [mob][photos] Fix build failing with xcode 16 update

auth/ios/Podfile.lock, auth/lib/core/logging/super_logging.dart, auth/lib/ui/settings/language_picker.dart, auth/pubspec.lock, auth/pubspec.yaml, auth/windows/flutter/generated_plugin_registrant.cc, auth/windows/flutter/generated_plugins.cmake
=> [auth] update dependencies for ios

mobile/lib/ui/tabs/home_widget.dart, mobile/lib/utils/diff_fetcher.dart, mobile/pubspec.yaml
=> Media extension fix for deeplinks

web/apps/photos/src/components/PhotoFrame.tsx, web/apps/photos/src/components/PhotoList/index.tsx, web/apps/photos/src/pages/gallery.tsx
Fixes https://github.com/ente-io/ente/issues/3603
=> [web] Reset scroll state on mode/person change

web/apps/photos/src/components/PhotoFrame.tsx, web/apps/photos/src/components/pages/gallery/PreviewCard.tsx
web client : Add the favorite icon to a memory thumbnail in the gallery, looking just like in the Android app
- favorite a picture
- in the gallery, check that the favorite icon is showed n the picture thumbnail, as an overlay
=> [web] add fav icon to picture thumbnails

web/apps/auth/src/pages/auth.tsx, web/apps/auth/src/pages/change-email.tsx, web/apps/auth/src/pages/change-password.tsx, web/apps/auth/src/pages/credentials.tsx, web/apps/auth/src/pages/generate.tsx, web/apps/auth/src/pages/login.tsx, web/apps/auth/src/pages/passkeys/finish.tsx, web/apps/auth/src/pages/passkeys/recover.tsx, web/apps/auth/src/pages/recover.tsx, web/apps/auth/src/pages/signup.tsx, web/apps/auth/src/pages/two-factor/recover.tsx, web/apps/auth/src/pages/two-factor/setup.tsx, web/apps/auth/src/pages/two-factor/verify.tsx, web/apps/auth/src/pages/verify.tsx
Introduced since the deployment this morning.
=> [web] [auth] Fix crash due to incorrect context

mobile/lib/utils/image_ml_util.dart
Change decode method for heic for ML to using flutter_image_compress.
Tested in debug mode on my pixel 8.
=> [mob][photos] Decode heic using flutter compress

web/apps/photos/src/components/MemberSubscriptionManage.tsx, web/apps/photos/src/pages/gallery.tsx, web/apps/photos/src/pages/shared-albums.tsx, web/packages/base/hooks.ts, web/packages/new/photos/components/AddPersonDialog.tsx, web/packages/new/photos/components/DevSettings.tsx, web/packages/new/photos/components/PeopleList.tsx, web/packages/new/photos/components/RecoveryKey.tsx, web/packages/new/photos/components/SearchBar.tsx, web/packages/new/photos/components/WhatsNew.tsx, web/packages/new/photos/components/gallery/BarImpl.tsx, web/packages/new/photos/components/gallery/PeopleHeader.tsx, web/packages/new/photos/services/ml/people.ts
Did this while sketching out a people suggestion approach, though it is conceptually unrelated.
=> [web] Rename the breakpoint hook 

docs/docs/auth/faq/index.md
Fixes many inconsistencies and grammatical errors in the Auth FAQs.
=> Improvements to the Auth FAQs

auth/lib/ui/utils/icon_utils.dart
The alt names are not being lowercased or striped of whitespace.
=> [auth] Alt names not being formatted when processing

mobile/lib/generated/intl/messages_all.dart, mobile/lib/generated/intl/messages_be.dart, mobile/lib/generated/intl/messages_de.dart, mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/intl/messages_es.dart, mobile/lib/generated/intl/messages_fr.dart, mobile/lib/generated/intl/messages_he.dart, mobile/lib/generated/intl/messages_id.dart, mobile/lib/generated/intl/messages_it.dart, mobile/lib/generated/intl/messages_ja.dart, mobile/lib/generated/intl/messages_lt.dart, mobile/lib/generated/intl/messages_nl.dart, mobile/lib/generated/intl/messages_no.dart, mobile/lib/generated/intl/messages_pl.dart, mobile/lib/generated/intl/messages_pt.dart, mobile/lib/generated/intl/messages_ro.dart, mobile/lib/generated/intl/messages_ru.dart, mobile/lib/generated/intl/messages_sl.dart, mobile/lib/generated/intl/messages_sv.dart, mobile/lib/generated/intl/messages_th.dart, mobile/lib/generated/intl/messages_tr.dart, mobile/lib/generated/intl/messages_uk.dart, mobile/lib/generated/intl/messages_zh.dart, mobile/lib/generated/l10n.dart, mobile/lib/main.dart
=> [mob] Fix init for discovery section

mobile/lib/db/ml/db.dart, mobile/lib/models/ml/face/face.dart, mobile/lib/ui/viewer/file/native_video_player_controls/seek_bar.dart, mobile/lib/ui/viewer/gallery/gallery.dart
=> [mob] Handle int value for face[blur] json

mobile/lib/models/ml/face/face.dart, mobile/lib/services/machine_learning/face_ml/person/person_service.dart
=> [mob] Minor improvements for ml sync

mobile/lib/ui/tools/editor/video_editor_page.dart
Back doesn't work when in video editor.
=> [mob][photos] fix video editor back button

mobile/pubspec.yaml
=> [mob] Bump version v0.9.48

mobile/lib/ui/account/delete_account_page.dart, mobile/lib/ui/account/sessions_page.dart, mobile/lib/ui/actions/collection/collection_sharing_actions.dart, mobile/lib/ui/common/progress_dialog.dart, mobile/lib/ui/components/action_sheet_widget.dart, mobile/lib/ui/components/dialog_widget.dart, mobile/lib/ui/home/grant_permissions_widget.dart, mobile/lib/ui/payment/payment_web_page.dart, mobile/lib/ui/settings/about_section_widget.dart, mobile/lib/ui/settings/account_section_widget.dart, mobile/lib/ui/settings/debug/debug_section_widget.dart, mobile/lib/ui/settings/security_section_widget.dart, mobile/lib/ui/settings_page.dart, mobile/lib/ui/sharing/add_participant_page.dart, mobile/lib/ui/tabs/home_widget.dart, mobile/lib/ui/viewer/file_details/exif_item_widgets.dart, mobile/lib/ui/viewer/gallery/gallery_app_bar_widget.dart, mobile/lib/utils/delete_file_util.dart, mobile/lib/utils/dialog_util.dart, mobile/lib/utils/email_util.dart, mobile/pubspec.yaml
Closes #3613 
Resolves issues in #3524 which are reproducible after a modal is closed (like bottom sheets, dialogs etc).
=> [mob][photos] Fix system back gesture closing the app when triggered after closing a modal

docs/docs/self-hosting/index.md
This PR includes some minor updates with the installation of dependencies. I tried setting up ente on a fresh server and I did not notice that I did not have all the dependencies until I was getting stopped by errors at every step. 
Any tests needed for docs ?
=> Adding steps to install dependencies

web/packages/new/photos/services/ml/people.ts
Use a median based suggestion mechanism.
=> [desktop] People suggestions - WIP - Part x/x

web/apps/photos/src/components/Upload/UploadTypeSelector.tsx, web/apps/photos/src/components/pages/gallery/PlanSelector.tsx, web/apps/photos/src/pages/_app.tsx, web/packages/base/components/MiniDialog.tsx, web/packages/base/components/utils/dialog.tsx, web/packages/base/locales/en-US/translation.json, web/packages/new/photos/components/gallery/index.tsx, web/packages/new/photos/types/context.ts
=> [web] Remove unused / unnecessary code

desktop/src/main/services/ml-worker.ts, infra/ml/YOLOv5Face/yoloface_onnx.ipynb, mobile/lib/services/machine_learning/face_ml/face_detection/face_detection_service.dart, mobile/lib/services/remote_assets_service.dart
Renamed a initializer inside YOLOv5Face model as it was causing issues on iOS. Using this updated version on all platforms out of precaution and consistency. 
Tested on Neeraj's phone that the issue is no longer reproducible.
=> Yolo splits

docs/docs/.vitepress/sidebar.ts, docs/docs/about/index.md, docs/docs/photos/faq/machine-learning.md, docs/docs/photos/features/machine-learning.md
FAQ section in help.ente.io on Machine Learning features.
=> FAQ on Machine Learning in help docs

mobile/pubspec.yaml
=> [mob] Bump version v0.9.50

server/pkg/api/admin.go
=> [server] Remove freshToken req for account recovery

web/apps/photos/src/services/collectionService.ts, web/apps/photos/src/services/watch.ts, web/apps/photos/src/utils/collection.ts, web/apps/photos/tests/upload.test.ts, web/packages/new/photos/components/gallery/reducer.ts, web/packages/new/photos/services/collection/index.ts, web/packages/new/photos/services/collection/ui.ts, web/packages/new/photos/services/file.ts, web/packages/new/photos/services/magic-metadata.ts
Cleanup pending from part 1 and 2
=> [web] Start moving gallery state into a reducer - Part 3/x 

auth/assets/custom-icons/_data/custom-icons.json
The PR #3482 broke the [lint for auth](https://github.com/ente-io/ente/actions/runs/11096891779/job/31533991573?pr=3482). This PR fixes that and also formats the document.
=> [auth] fix formatting in custom_icons

mobile/lib/db/ml/clip_db.dart, mobile/lib/db/ml/db.dart, mobile/lib/models/file/file.dart, mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart, mobile/lib/utils/exif_util.dart, mobile/lib/utils/file_uploader_util.dart, mobile/lib/utils/panorama_util.dart
=> [mob][perf] Avoid XMP extraction on main thread

server/cmd/museum/main.go, server/ente/admin.go, server/pkg/api/admin.go, server/pkg/middleware/request_logger.go
=> [server] Add API to terminate userSession

mobile/lib/core/error-reporting/super_logging.dart
=> [mob] Reduce noise from sentry

cli/cmd/account.go
=> [cli] Improve error message

cli/pkg/account.go, cli/pkg/sign_in.go
=> [cli] Fix login for auth app when passkey is enabled

mobile/pubspec.yaml
=> [mob] Bump version v0.9.53

auth/assets/custom-icons/_data/custom-icons.json
=> Update custom-icons.json for impact.com

web/apps/photos/src/components/Sidebar/Preferences.tsx
https://github.com/ente-io/ente/issues/3634#issuecomment-2448388285
=> [web] Fix capitalization for the uk-UA lang

desktop/.github/workflows/desktop-release.yml
https://github.com/actions/runner-images/issues/6039#issuecomment-1209531257
=> [desktop] Fix build failures due to apt failures

mobile/lib/module/upload/service/multipart.dart
=> [mob] Handle 404 for multipart failure

mobile/lib/ui/viewer/people/add_person_action_sheet.dart
=> [mob] Fix nav bug during person label assignment

server/pkg/controller/filedata/replicate.go
=> [server] Log additional details on replication failure

auth/pubspec.yaml
=> [auth] Bump version v4.1.0

mobile/lib/utils/date_time_util.dart, mobile/test/utils/date_time_util_test.dart
Related to https://github.com/ente-io/ente/issues/3851
=> [mob] Fix date parsing for batched photos from signal

web/apps/photos/src/components/Sidebar/Preferences.tsx, web/apps/photos/src/components/Upload/Uploader.tsx, web/apps/photos/src/pages/_app.tsx, web/apps/photos/src/pages/shared-albums.tsx, web/apps/photos/src/services/logout.ts, web/apps/photos/src/services/upload/uploadManager.ts, web/apps/photos/src/services/userService.ts, web/apps/photos/src/types/user/index.ts, web/packages/media/upload.ts, web/packages/new/photos/services/migrations.ts, web/packages/new/photos/services/settings.ts, web/packages/new/photos/types/context.ts, web/packages/shared/storage/localStorage/index.ts
This is in prep for moving the public albums app to be standalone.
=> [web] Improve handling of the CF Upload proxy flag

web/package.json
=> [web] Remove unused yarn invocations

mobile/lib/ui/payment/subscription_plan_widget.dart
=> [mob][photos] UI tweaks on pricing page

server/ente/filedata/filedata.go, server/pkg/api/file_data.go, server/pkg/controller/filedata/controller.go, server/pkg/repo/filedata/repository.go
=> [server] refactor fd status API

mobile/lib/db/file_updation_db.dart, mobile/lib/db/files_db.dart, mobile/lib/ui/viewer/file/exif_info_dialog.dart
If number of iterations are high, concatenating a list of values to a string using `str1 += str2` can block the UI thread. 
Using `List.join()` is a much more efficient way to do this.
=> [mob][photos] Concatenate strings more efficiently

server/ente/storagebonus/storge_bonus.go
=> [server] Fix BF handling for bonus calculation

mobile/lib/module/upload/service/multipart.dart
=> [mob] Handle 401 during multipart failure

mobile/lib/utils/file_uploader.dart
=> [mob] Clean up multipart upload on put or update error

server/pkg/controller/file.go
=> [server] Add validation for object_keys

infra/staff/src/App.tsx, infra/staff/src/components/ChangeEmail.tsx, infra/staff/src/components/CloseFamily.tsx, infra/staff/src/components/DeleteAccont.tsx, infra/staff/src/components/Disable2FA.tsx, infra/staff/src/components/DisablePasskeys.tsx, infra/staff/src/components/FamilyComponentTable.tsx, infra/staff/src/components/StorageBonusTableComponent.tsx, infra/staff/src/components/UpdateSubscription.tsx, infra/staff/yarn.lock
=> [staff] Suraface error as alert & send token via header

auth/lib/models/code_display.dart, auth/lib/store/code_store.dart, auth/lib/ui/home_page.dart, auth/lib/ui/reorder_codes_page.dart
This pull request introduces functionality to enable custom sorting for TOTP codes in the app. Users can now drag and drop codes to rearrange their order. The updated order is synced across all devices.
=> [auth] Implement Custom Sorting

web/apps/photos/src/components/Collections/GalleryBarAndListHeader.tsx, web/apps/photos/src/components/FullScreenDropZone.tsx, web/apps/photos/src/components/Sidebar/Preferences.tsx, web/apps/photos/src/pages/gallery.tsx, web/apps/photos/src/styles/global.css, web/packages/base/components/mui/Container.tsx, web/packages/new/photos/components/gallery/BarImpl.tsx, web/packages/new/photos/components/gallery/PeopleHeader.tsx, web/packages/new/photos/components/gallery/index.tsx, web/packages/new/photos/components/sidebar/MLSettings.tsx
=> [desktop] Move out of labs

server/pkg/repo/storagebonus/bf_addon.go
=> [server] Handle error in bonus reversal

mobile/lib/db/ml/db.dart, mobile/lib/models/ml/face/person.dart, mobile/lib/services/machine_learning/face_ml/face_clustering/face_clustering_service.dart, mobile/lib/services/machine_learning/face_ml/face_clustering/face_db_info_for_clustering.dart, mobile/lib/services/machine_learning/face_ml/feedback/cluster_feedback.dart, mobile/lib/services/machine_learning/face_ml/person/person_service.dart, mobile/lib/services/machine_learning/ml_service.dart, mobile/lib/ui/viewer/people/add_person_action_sheet.dart, mobile/lib/ui/viewer/people/person_cluster_suggestion.dart
Remotely safe faceIDs of a certain person that are rejected by the user.
=> Ml sync fix

mobile/lib/services/machine_learning/face_ml/person/person_service.dart
Fix ConcurrentModificationError
=> [mob][photos] Fix ConcurrentModificationError

web/apps/auth/public/_headers, web/apps/photos/public/_headers, web/packages/new/photos/services/ffmpeg/web.ts, web/packages/new/photos/services/search/worker.ts
- And don't block on cities fetch during remoteSync
=> [web] Switch to assets

server/ente/errors.go, server/ente/user.go, server/pkg/controller/user/userauth.go
=> [server]Throw err if account registration is completed

web/apps/auth/src/pages/auth.tsx, web/packages/base/locales/en-US/translation.json
Fixes: https://github.com/ente-io/ente/discussions/4134
=> [web][auth] Improve empty state

server/ente/user.go, server/pkg/controller/user/user_delete.go, server/pkg/repo/userauth.go
=> [server][delete] return list of apps being used

server/ente/errors.go, server/ente/user.go, server/pkg/controller/replication3.go, server/pkg/controller/user/userauth.go
=> [server] Sign up completion check during login + update discord alert

mobile/lib/events/people_changed_event.dart, mobile/lib/ui/viewer/gallery/hooks/pick_person_avatar.dart
=> [mob] Refresh UI when person is changed

server/pkg/controller/user/user_details.go
=> [server] Fix usage cal in user_details

web/apps/photos/package.json, web/docs/dependencies.md, web/packages/accounts/package.json, web/packages/accounts/services/srp.ts, web/yarn.lock
=> [web] Document UUID dependency

mobile/lib/services/machine_learning/face_ml/person/person_service.dart
Quick fix for suggestion undo issue.
=> [mob][photos] Quick fix undo

mobile/lib/services/collections_service.dart, mobile/lib/utils/diff_fetcher.dart, server/cmd/museum/main.go, web/apps/cast/src/services/render.ts, web/apps/photos/src/services/publicCollectionService.ts
...instead of adding it to ad-hoc API requests.
---
Tests: Smoke tested photos, shared albums and cast on localhost.
=> [API] Add Cache-control: no-store to API responses

infra/staff/src/App.tsx, infra/staff/src/components/TokenTableComponent.tsx, infra/staff/src/components/UserComponent.tsx
=> [Staff] Update support dashboard

docs/docs/photos/faq/export.md, docs/docs/photos/migration/export/index.md
=> [doc] Add metadata q to export faq

infra/staff/src/App.tsx, infra/staff/src/components/ToggleEmailMFA.tsx, infra/staff/src/components/UserComponent.tsx
=> [staff] Update staff dashboard

mobile/lib/ui/home/status_bar_widget.dart
=> [mob][photos] Fix ml banner

auth/lib/l10n/arb/app_en.arb, auth/lib/services/passkey_service.dart, auth/lib/services/user_service.dart, auth/lib/ui/passkey_page.dart, mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/l10n.dart, mobile/lib/l10n/intl_en.arb, mobile/lib/services/passkey_service.dart, mobile/lib/services/user_service.dart, mobile/lib/ui/account/passkey_page.dart, mobile/lib/ui/account/two_factor_authentication_page.dart
=> [mob] Enable fallback to TOTP if both passkey & totp are enabled

mobile/lib/services/update_service.dart, mobile/lib/ui/notification/update/change_log_page.dart, mobile/pubspec.yaml
=> [mob][photos] Update change log

mobile/lib/ui/viewer/people/save_or_edit_person.dart, mobile/pubspec.yaml
=> [mob] Bump version v0.9.65

mobile/lib/l10n/l10n.dart, mobile/lib/ui/settings/language_picker.dart
=> [mob] Enable translation for Ukrainian & Vietnamese

auth/lib/ui/account/login_page.dart, mobile/lib/ui/account/login_page.dart
=> [mob][auth] Send login purpose during ott

server/configurations/local.yaml, server/pkg/middleware/auth.go
Fix code that didn't even compile, + document https://github.com/ente-io/ente/pull/4228
=> [server] Fix and document the internal.admin flag

server/cmd/museum/main.go, server/pkg/api/admin.go, server/pkg/controller/file.go, server/pkg/controller/replication3.go, server/pkg/repo/object_copies.go
=> [server] Enhance alerts + defer replication attemp on size error

auth/lib/ui/home_page.dart, auth/macos/Podfile.lock
Fixes #[3153](https://github.com/ente-io/ente/discussions/3153) and #[3272](https://github.com/ente-io/ente/discussions/3272)
=> [auth][search] fix focus on search icon tap

server/pkg/controller/replication3.go
=> [server] Add missing nil check

mobile/lib/ui/viewer/people/save_or_edit_person.dart
=> [mob] SaveOrEditPerson: Dismiss keyboard on tapping outside

web/apps/auth/src/services/remote.ts
.map is not defined on an iterator
=> [web] auth / fix iteration on Safari

auth/lib/l10n/arb/app_en.arb, auth/lib/services/preference_service.dart, auth/lib/services/user_service.dart, auth/lib/ui/code_widget.dart, auth/lib/ui/components/buttons/icon_button_widget.dart, auth/lib/ui/home_page.dart, auth/lib/ui/reorder_codes_page.dart, auth/lib/ui/sort_option_menu.dart
=> [auth] Fix sorting + add option to sort by recently and most frequently used

auth/lib/ui/code_widget.dart, auth/lib/ui/home_page.dart, auth/pubspec.yaml
=> [auth] Keep favorite enteries on top in all cases except custom sort

auth/devtools_options.yaml, auth/lib/l10n/arb/app_en.arb, auth/lib/ui/home_page.dart, auth/lib/ui/reorder_codes_page.dart, auth/lib/ui/sort_option_menu.dart, auth/pubspec.yaml
=> [auth] Minor fixes for custom order

mobile/lib/ui/components/bottom_action_bar/bottom_action_bar_widget.dart, mobile/lib/ui/tools/editor/image_editor_page.dart, mobile/lib/ui/viewer/gallery/collection_page.dart
=> [mob][photos] Fix safe area issues

server/compose.yaml
Fixes one small typo in the docker-compose code
N/A
=> fixes minor typo in docker-compose comments

auth/lib/app/view/app.dart, auth/lib/l10n/arb/app_en.arb, auth/lib/services/update_service.dart, auth/lib/ui/code_widget.dart, auth/lib/ui/components/bottom_action_bar_widget.dart, auth/lib/ui/components/code_selection_actions_widget.dart, auth/lib/ui/home_page.dart, auth/pubspec.yaml
=> [auth] Revert pin to favorite change

auth/pubspec.yaml
=> [auth] Bump version v4.1.5

auth/lib/app/view/app.dart
Fixes https://github.com/ente-io/ente/issues/4293
=> [auth] Fix theme switch for windows & linux

auth/assets/custom-icons/_data/custom-icons.json, auth/assets/custom-icons/icons/ubiquiti.svg, auth/lib/ui/sort_option_menu.dart, auth/lib/ui/utils/icon_utils.dart, auth/pubspec.lock, auth/pubspec.yaml
Fixes https://github.com/ente-io/ente/issues/3875
=> [auth] Fixed bad custom icon json & altName matching

mobile/lib/emergency/emergency_page.dart, mobile/pubspec.yaml
=> [mob] Bump version v0.9.70

mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/l10n.dart, mobile/lib/l10n/intl_en.arb, mobile/pubspec.yaml
=> [mob] Fix copy

server/pkg/controller/emergency/controller.go, server/pkg/controller/emergency/email.go
=> [server] Fix recovery email

server/Dockerfile, server/go.mod, server/pkg/controller/mailing_lists.go
=> [server] Upgrade go version to 1.23

desktop/src/main.ts
Fixes: https://github.com/ente-io/ente/issues/4358
=> [desktop] Add workaround for back button on Stripe checkout

auth/pubspec.yaml
=> [auth] Bump version v4.1.7

auth/lib/core/constants.dart, auth/lib/ui/settings/support_section_widget.dart
=> [auth] Update feature request url

auth/lib/onboarding/view/setup_enter_secret_key_page.dart, auth/lib/ui/components/custom_icon_widget.dart, auth/lib/ui/custom_icon_page.dart, auth/pubspec.lock, auth/pubspec.yaml
=> [auth] Align icon to show on top center of Code Edit Screen & Bump Version

web/packages/new/photos/services/ml/worker.ts
https://github.com/ente-io/ente/issues/4087#issuecomment-2525073128
=> [web] Retry on failures in fetching already indexed items

web/apps/photos/src/pages/gallery.tsx, web/packages/new/photos/components/gallery/index.tsx, web/packages/new/photos/components/gallery/reducer.ts, web/packages/new/photos/services/search/types.ts
...and other actions which the search results are being shown.
=> [web] Automatically update search results on deletes

auth/lib/ui/settings/data/data_section_widget.dart
=> [auth] Remove Contact Support option when no duplicate code found

mobile/lib/theme/effects.dart, mobile/lib/ui/home/memories/memories_widget.dart, mobile/lib/ui/home/memories/memory_cover_widget.dart
Change seen and unseen memory states.
(New state on the right)
=> [mob][photos] Memories widget UI changes

mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/l10n.dart, mobile/lib/l10n/intl_en.arb, mobile/lib/ui/home/grant_permissions_widget.dart
=> [mob] Update permission dialog

auth/assets/custom-icons/_data/custom-icons.json, auth/pubspec.yaml
Error:  **Invalid radix-16 number (at character 3) 0xFF#4687FF**
=> [auth] fix formatting of hex value in custom-icons.json

auth/ios/Podfile.lock, auth/lib/ui/custom_icon_page.dart, auth/lib/ui/settings/data/html_export.dart, auth/lib/ui/utils/icon_utils.dart, auth/linux/flutter/generated_plugin_registrant.cc, auth/linux/flutter/generated_plugins.cmake, auth/macos/Flutter/GeneratedPluginRegistrant.swift, auth/pubspec.lock, auth/pubspec.yaml, auth/windows/flutter/generated_plugin_registrant.cc, auth/windows/flutter/generated_plugins.cmake
=> [auth] Improve icon path matching

server/cmd/museum/main.go, server/pkg/controller/emergency/controller.go, server/pkg/controller/emergency/recovery.go
=> [server] Disable 2fa on legacy account recovery

server/cmd/museum/main.go, server/configurations/local.yaml, server/ente/remotestore.go, server/ente/user.go, server/pkg/api/user.go, server/pkg/controller/remotestore/controller.go, server/pkg/controller/user/userauth.go
For the cast dialog, that we show on the app, before making the API call to pair. Have parked that change for now.
=> [server] Return various app urls as part of relevant API response.

server/ente/user.go, server/pkg/controller/user/userauth.go
Related https://github.com/ente-io/ente/pull/4491
=> [server] Rename accountUrl -> accountsUrl

mobile/lib/services/collections_service.dart, mobile/lib/ui/tabs/home_widget.dart, mobile/lib/ui/viewer/file/file_widget.dart, mobile/lib/ui/viewer/file/zoomable_live_image_new.dart, mobile/lib/utils/diff_fetcher.dart
Fixed these issues:
- Unrelated files coming up (these are local device files) in public link when opened in-app.
- Max number of files in link capped to 2000.
- Sort order not working.
=> [mob][photos] In-app public link fixes

auth/lib/ui/code_timer_progress.dart, auth/lib/ui/code_widget.dart, auth/macos/Runner.xcodeproj/project.pbxproj, auth/pubspec.lock, auth/pubspec.yaml
Related https://github.com/ente-io/ente/issues/2003#issuecomment-2563380828
=> [auth] Reduce progress bar refresh rate to lower CPU usage

auth/lib/ui/utils/icon_utils.dart, auth/pubspec.yaml
- Update contract for Simple Icons: https://github.com/simple-icons/simple-icons/pull/12415
- Tested manually on Simulator
=> [auth] Fix icons

desktop/CHANGELOG.md, desktop/docs/dependencies.md, desktop/docs/dev.md, desktop/docs/release.md, desktop/package.json, desktop/src/main.ts, desktop/src/main/services/ml.ts, desktop/src/preload.ts, desktop/yarn.lock, web/docs/README.md, web/package.json, web/packages/new/photos/pages/duplicates.tsx, web/yarn.lock
And then some.
Sibling of https://github.com/ente-io/ente/pull/4542
=> [desktop] Prettier upgrade

server/pkg/controller/file.go
=> [server] Speed up deletion

server/configurations/local.yaml, server/pkg/controller/user/userauth.go
=> [server] Skip sending ott during signup when registrations are disabled

mobile/lib/generated/intl/messages_de.dart, mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/intl/messages_es.dart, mobile/lib/generated/intl/messages_fa.dart, mobile/lib/generated/intl/messages_fr.dart, mobile/lib/generated/intl/messages_he.dart, mobile/lib/generated/intl/messages_id.dart, mobile/lib/generated/intl/messages_it.dart, mobile/lib/generated/intl/messages_ja.dart, mobile/lib/generated/intl/messages_lt.dart, mobile/lib/generated/intl/messages_nl.dart, mobile/lib/generated/intl/messages_no.dart, mobile/lib/generated/intl/messages_pl.dart, mobile/lib/generated/intl/messages_pt.dart, mobile/lib/generated/intl/messages_ro.dart, mobile/lib/generated/intl/messages_ru.dart, mobile/lib/generated/intl/messages_sv.dart, mobile/lib/generated/intl/messages_th.dart, mobile/lib/generated/intl/messages_tr.dart, mobile/lib/generated/intl/messages_uk.dart, mobile/lib/generated/intl/messages_vi.dart, mobile/lib/generated/intl/messages_zh.dart, mobile/lib/generated/l10n.dart, mobile/lib/l10n/intl_en.arb, mobile/lib/ui/collections/button/hidden_button.dart, mobile/lib/ui/collections/button/trash_button.dart
=> [mob] Add authentication for trashed section

auth/lib/ui/code_timer_progress.dart
=> [auth] Fix progress bar

auth/lib/ui/components/dialog_widget.dart, auth/lib/ui/tools/lock_screen.dart, auth/lib/utils/dialog_util.dart
https://github.com/user-attachments/assets/3f6d3726-d333-4dc3-ba67-3c100d00d93f
=> [auth] Export Code Lockscreen fix 

auth/lib/ui/custom_icon_page.dart, auth/lib/ui/reorder_codes_page.dart
Fix issue [4568](https://github.com/ente-io/ente/issues/4568)
=> [auth] Dragable scrollbar for long scrolling list of codes

auth/lib/ui/home_page.dart, auth/pubspec.yaml
=> [auth] Fix key binding for search focus on mac

server/mail-templates/on_login.html, server/pkg/controller/email/email_notification.go, server/pkg/controller/user/twofactor.go, server/pkg/controller/user/userauth.go
- Add functionality for sending Email Notification on Login to User's Ente Account.
=> [server] Email Notification on User Login. 

desktop/CHANGELOG.md, web/apps/photos/src/services/upload/upload-service.ts, web/packages/media/file-metadata.ts, web/packages/new/photos/services/exif.ts
- Implements https://github.com/ente-io/ente/discussions/3857#discussioncomment-11764990
- Tested on the samples provided therein.
=> [web] Parse description from image metadata

mobile/lib/db/ml/db.dart, mobile/lib/ui/viewer/people/save_or_edit_person.dart
=> [mob][photos] Fix sync issue adding cluster

auth/README.md, mobile/README.md
=> [mob][auth] Add certificate fingerprint

server/pkg/controller/access/access.go, server/pkg/controller/access/file.go, server/pkg/controller/filedata/controller.go, server/pkg/controller/filedata/preview_files.go, server/pkg/controller/filedata/video.go, server/pkg/repo/collection.go
Will test happy cases and update here
=> [server] Enable metadata r/w for shared files

server/ente/public_collection.go
=> [server] Fixed typo

mobile/lib/db/ml/db.dart, mobile/lib/services/machine_learning/face_ml/person/person_service.dart, mobile/lib/services/search_service.dart
Better logs the case where clusters are mapped to non-existant Persons, and deletes the mapping in such cases
=> Better logging and handling of inconsistent person cluster mappings

mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/l10n.dart, mobile/lib/l10n/intl_en.arb, mobile/lib/ui/settings/ml/machine_learning_settings_page.dart, mobile/lib/utils/ml_util.dart, mobile/pubspec.yaml
=> [mob] Improve index fetch when localIndexing is disabled

mobile/lib/ui/settings/backup/backup_item_card.dart, mobile/lib/utils/file_uploader.dart
=> [mob] Fix stuck uploads due to lock & surface upload error on backup status

auth/ios/Podfile.lock, auth/lib/ui/settings/data/import/two_fas_import.dart, auth/pubspec.lock, auth/pubspec.yaml
=> [auth] Fix 2fas import

auth/lib/ui/home/home_empty_state.dart, auth/lib/ui/home_page.dart, auth/pubspec.yaml
=> [auth] Bump version & hide import from gallery for external users

auth/lib/l10n/arb/app_en.arb, auth/lib/services/user_service.dart, mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/l10n.dart, mobile/lib/l10n/intl_en.arb, mobile/lib/services/user_service.dart
=> [auth][mob] Gracefully handle registration error

auth/linux/packaging/enteauth.appdata.xml
=> [auth] Update flatpak version

auth/lib/ui/home_page.dart
=> [auth] Fix app bar Icon spacing

auth/lib/theme/colors.dart, auth/lib/theme/ente_theme.dart, auth/lib/ui/home_page.dart, auth/lib/utils/lock_screen_settings.dart
=> [auth] Fix privacy screen color for dark mode

auth/lib/ente_theme_data.dart, auth/lib/onboarding/view/onboarding_page.dart, auth/lib/onboarding/view/setup_enter_secret_key_page.dart, auth/lib/ui/home/home_empty_state.dart
=> [auth] Fix content not scrolling when font size set to large

auth/macos/Runner/Configs/AppInfo.xcconfig, auth/pubspec.yaml
=> [auth] Update version

.github/workflows/auth-release.yml
=> [auth] Update Github build action

.github/workflows/auth-release.yml
=> [auth] Fix workflow for Ubuntu build

auth/lib/models/code.dart, auth/lib/onboarding/view/view_qr_page.dart, auth/lib/ui/settings/data/export_widget.dart, auth/lib/ui/settings/data/import/google_auth_import.dart, auth/pubspec.yaml
Fixes https://github.com/ente-io/ente/issues/4404
=> [auth] Fix export with invalid algo name

mobile/lib/models/ml/face/person.dart, mobile/lib/services/machine_learning/face_ml/feedback/cluster_feedback.dart, mobile/lib/ui/viewer/people/person_cluster_suggestion.dart, mobile/lib/ui/viewer/people/save_or_edit_person.dart
=> [mob][photos] Fix issue with null person data

mobile/lib/services/machine_learning/face_ml/person/person_service.dart
=> [mob][photos] Remove cluster bug

mobile/lib/ui/settings/ml/machine_learning_settings_page.dart
=> [mob][photos] Update if pause is over

mobile/lib/generated/intl/messages_de.dart, mobile/lib/generated/intl/messages_es.dart, mobile/lib/generated/intl/messages_fr.dart, mobile/lib/generated/intl/messages_it.dart, mobile/lib/generated/intl/messages_lt.dart, mobile/lib/generated/intl/messages_pt.dart, mobile/lib/generated/intl/messages_uk.dart, mobile/lib/generated/intl/messages_vi.dart, mobile/pubspec.yaml
=> [mob] Bump version v0.9.79

mobile/lib/ui/viewer/search/result/person_face_widget.dart
=> [mob][photos] Fix hidden file for face

mobile/lib/models/search/search_types.dart, mobile/lib/services/search_service.dart
=> [mob] Update moments section for internal users

auth/lib/main.dart, auth/lib/services/window_listener_service.dart
Related 
https://github.com/ente-io/ente/issues/2004
https://github.com/ente-io/ente/issues/2326
=> [auth] Potential fix for segfault on Linux due to bad window size

mobile/lib/models/ml/face/person.dart
Fix regression causing the Person entities to not load properly on mobile.
=> [mob][photos] Fix regression with Persons

mobile/pubspec.yaml
=> [mob][photos] Bump for release

server/cmd/museum/main.go, server/mail-templates/legacy/recovery_reminder.html, server/pkg/controller/emergency/controller.go, server/pkg/controller/emergency/email.go, server/pkg/controller/emergency/recovery.go, server/pkg/controller/emergency/recovery_contact.go, server/pkg/repo/emergency/recovery.go
- Sends email when account is ready to be recovered
- Keep sending reminder email every 7 days, till T-2 day when a recovery attempt is in waiting.
Did monkey testing locally by modifying the DB time
=> [server] Legacy email reminder

auth/lib/onboarding/view/setup_enter_secret_key_page.dart, auth/pubspec.yaml
Related to https://github.com/ente-io/ente/issues/4736
Tested locally
=> [auth] Fix manual code setup

desktop/build/io.ente.photos.appdata.xml
Add AppStream MetaInfo for https://github.com/flathub/flathub/pull/6032, similar to [enteauth.appdata.xml](https://github.com/ente-io/ente/blob/main/auth/linux/packaging/enteauth.appdata.xml).
=> [desktop] Add MetaInfo

mobile/lib/services/machine_learning/ml_service.dart, mobile/lib/ui/viewer/file_details/face_widget.dart
Trigger clustering when user presses on unclustered face from file info.
=> Cluster trigger

auth/lib/services/user_service.dart, mobile/lib/services/user_service.dart
=> [auth][mob] Add padding during SRP authn

server/configurations/local.yaml, server/pkg/utils/email/email.go
=> [server] Make SMTP sender name configurable

desktop/build/io.ente.photos.appdata.xml
https://docs.flathub.org/blog/introducing-app-brand-colors/#adding-brand-colors
=> [desktop] Include branding colors in Flathub MetaInfo

server/pkg/controller/user/srp.go
=> [server] Fix error type for bad request

web/packages/base/crypto/libsodium.ts
Sibling of https://github.com/ente-io/ente/pull/4771
=> [web] Update mem & ops limits

auth/lib/main.dart, auth/lib/services/window_listener_service.dart
=> [auth] Minor fixes

mobile/pubspec.yaml
=> [mob] Bump version

auth/ios/Podfile.lock, auth/linux/flutter/generated_plugin_registrant.cc, auth/linux/flutter/generated_plugins.cmake, auth/macos/Flutter/GeneratedPluginRegistrant.swift, auth/pubspec.yaml, auth/windows/flutter/generated_plugin_registrant.cc, auth/windows/flutter/generated_plugins.cmake
=> [auth] Bump version v4.3.0

desktop/scripts/beforeBuild.js
These issues only surface when running on the CI, hence the PR splurge.
=> [desktop] Fix incomplete build being generated - Take 2

mobile/android/app/src/main/AndroidManifest.xml, mobile/ios/Runner/Info.plist, mobile/pubspec.yaml
=> [mob] Opt of out flutter default deeplink

mobile/ios/Runner.xcodeproj/project.pbxproj, mobile/ios/Runner/Info.plist
=> [mob] Use different bundle for iOS debug variant

auth/lib/ui/code_widget.dart, auth/lib/ui/reorder_codes_page.dart
=> [auth] Hide [Share/QR/Edit/Trash] popup in code reorder screen

mobile/lib/models/ml/face/person.dart, mobile/lib/services/machine_learning/face_ml/feedback/cluster_feedback.dart, mobile/lib/services/machine_learning/face_ml/person/person_service.dart, mobile/lib/services/machine_learning/ml_service.dart, mobile/lib/ui/viewer/people/people_app_bar.dart, mobile/lib/ui/viewer/people/save_or_edit_person.dart
Make PersonData.assigned and PersonData.rejectedFaceIds non-nullable to fix issue.
=> Person assigned

web/packages/media/file-metadata.ts, web/packages/new/photos/services/exif.ts, web/packages/utils/ensure.ts
A customer sent us a sample file from the wild where this was the case.
=> [web] Handle NaN in the Exif locations

mobile/lib/main.dart, mobile/lib/services/machine_learning/face_ml/person/person_service.dart, mobile/lib/ui/sharing/album_share_info_widget.dart, mobile/lib/ui/sharing/more_count_badge.dart, mobile/lib/ui/sharing/user_avator_widget.dart
If the user (contact specifically) is linked to a person, use the person's face as user's avatar in the `UserAvatarWidget` 
Tested everything myself.
=> [mob][photos] Use face when available for user avatar

.github/workflows/auth-internal-release.yml, .github/workflows/auth-lint.yml, .github/workflows/auth-release.yml, auth/assets/custom-icons/_data/custom-icons.json, auth/macos/Podfile.lock, auth/pubspec.lock, auth/pubspec.yaml
=> [auth] Downgrade flutter

mobile/lib/module/upload/service/multipart.dart
=> [mob] Handle 401/404 failure during individual multipart upload

web/apps/photos/src/components/Sidebar/SubscriptionCard.tsx
=> [web] Storage card light mode 

desktop/src/main.ts, desktop/src/preload.ts, web/apps/photos/src/pages/_app.tsx, web/packages/base/types/ipc.ts
Ref: https://github.com/electron/electron/issues/20322
=> [desktop] Don't assume a particular position for the open URL arg

auth/lib/services/user_service.dart, auth/lib/ui/two_factor_recovery_page.dart, mobile/lib/services/user_service.dart, mobile/lib/ui/account/two_factor_recovery_page.dart
Resolves https://github.com/ente-io/ente/issues/3935
=> [auth][mob] Fix 2FA recovery flow

mobile/lib/generated/intl/messages_pl.dart, mobile/lib/generated/l10n.dart, mobile/lib/l10n/intl_en.arb, mobile/lib/l10n/intl_pl.arb
=> [mob] Fix bad translation

mobile/lib/utils/file_uploader.dart, mobile/lib/utils/file_uploader_util.dart
=> [mob] Reduce noise from logs

web/packages/media/file.ts, web/packages/new/photos/components/gallery/reducer.ts, web/packages/new/photos/services/files.ts
Fixes https://github.com/ente-io/ente/issues/4893, https://github.com/ente-io/ente/discussions/4000
Related https://github.com/ente-io/ente/discussions/3047
=> [web] Match mobile behaviour for archived files in all

desktop/scripts/beforeBuild.js
Regression introduced yesterday - d37675cc5768357b155e504d2d08656d099eb73f
=> [desktop] Fix ARM build

web/apps/photos/src/components/Collections/CollectionShare.tsx, web/apps/photos/src/components/Export.tsx, web/apps/photos/src/components/ExportPendingList.tsx, web/apps/photos/src/components/PhotoViewer/FileInfo.tsx, web/apps/photos/src/components/PhotoViewer/index.tsx, web/packages/base/components/Titlebar.tsx, web/packages/base/components/mui/SidebarDrawer.tsx, web/packages/base/components/utils/mui-theme.d.ts, web/packages/base/components/utils/theme.ts, web/packages/new/photos/components/PlanSelector.tsx, web/packages/new/photos/components/SearchBar.tsx, web/packages/new/photos/components/gallery/PeopleHeader.tsx
=> [web] Light mode changes - Revert the dialog blur 

mobile/lib/ui/tabs/home_widget.dart, mobile/lib/utils/collection_util.dart
1. Don't show the permission dialog if self-hosted ente
2. Show dialog only once
=> [mob][photos] Ask "open public album link in app" permission once

desktop/docs/dependencies.md, desktop/src/main/services/ffmpeg.ts, desktop/src/main/services/ml.ts, web/apps/photos/src/services/upload/thumbnail.ts, web/docs/dependencies.md, web/docs/heic.md, web/packages/base/types/ipc.ts, web/packages/gallery/services/ffmpeg/index.ts, web/packages/gallery/services/ffmpeg/web.ts, web/packages/gallery/utils/convert.ts, web/packages/media/heic-convert.ts, web/packages/new/photos/services/ml/math.ts
From webassembly.org
> WebAssembly (abbreviated _Wasm_) is ...
=> [meta] Use preferred casing of Wasm

mobile/lib/l10n/intl_de.arb, mobile/lib/l10n/intl_es.arb, mobile/lib/l10n/intl_fr.arb, mobile/lib/l10n/intl_it.arb, mobile/lib/l10n/intl_ja.arb, mobile/lib/l10n/intl_nl.arb, mobile/lib/l10n/intl_pl.arb, mobile/lib/l10n/intl_pt.arb, mobile/lib/l10n/intl_ro.arb, mobile/lib/l10n/intl_sv.arb, mobile/lib/l10n/intl_uk.arb, mobile/lib/l10n/intl_vi.arb, mobile/lib/l10n/intl_zh.arb
This reverts commit 930224a2e57d567d3e843cb0ada2e21f78128634, reversing changes made to 3de324f342363805e38dce843779639ffa88972c.
=> Revert "[mobile] New translations (#4938)"

mobile/lib/db/ml/db.dart
=> [mob] Fix personAvatar when low score face is manually assigned

desktop/CHANGELOG.md, web/apps/photos/src/services/upload/takeout.ts, web/apps/photos/src/services/upload/uploadManager.ts, web/apps/photos/tests/upload.test.ts
Ref: https://github.com/ente-io/ente/pull/4956
=> [web] Tweaks to handling of the new .supplemental-metadata

web/apps/photos/src/components/PhotoViewer/ImageEditorOverlay.tsx, web/packages/base/components/loaders.tsx, web/packages/base/components/utils/mui-theme.d.ts, web/packages/base/components/utils/theme.ts, web/packages/new/photos/components/PlanSelector.tsx, web/packages/new/photos/components/gallery/BarImpl.tsx, web/packages/new/photos/components/gallery/reducer.ts, web/packages/new/photos/services/collection/ui.ts
=> [web] Stack indicators on the album thumbnail

mobile/lib/ui/common/bottom_shadow.dart, mobile/lib/ui/common/loading_widget.dart, mobile/lib/ui/tabs/home_widget.dart, mobile/lib/ui/viewer/people/cluster_page.dart
=> [mob] Fix bad state error

mobile/lib/models/search/search_types.dart, mobile/lib/services/search_service.dart, mobile/pubspec.yaml
=> [mob][photos] Memories fix

web/apps/photos/src/components/Collections/AlbumCastDialog.tsx, web/apps/photos/src/components/FilesDownloadProgress.tsx, web/apps/photos/src/components/PhotoViewer/FileInfo.tsx, web/apps/photos/src/components/PhotoViewer/ImageEditorOverlay.tsx, web/apps/photos/src/components/PhotoViewer/index.tsx, web/apps/photos/src/pages/_app.tsx, web/packages/base/components/MiniDialog.tsx, web/packages/base/components/mui/SidebarDrawer.tsx, web/packages/new/photos/components/PhotoViewer.tsx, web/packages/new/photos/components/utils/z-index.tsx
\+ continue with the custom title bar prep
=> [web] Use lighter scrim for overlays atop photo viewer

server/pkg/controller/file.go
=> [server] Speed up file deletion

server/cmd/museum/main.go, server/pkg/controller/file.go
=> [server] Delete more items in single run

mobile/lib/ui/viewer/gallery/gallery.dart, mobile/lib/utils/file_uploader.dart
=> [mob] Avoid reloading all files from DB on Upload events

mobile/ios/Podfile.lock, mobile/lib/models/file/file.dart, mobile/lib/models/metadata/file_magic.dart, mobile/lib/ui/viewer/file_details/creation_time_item_widget.dart, mobile/lib/utils/exif_util.dart, mobile/lib/utils/file_uploader.dart, mobile/lib/utils/file_uploader_util.dart, mobile/lib/utils/share_util.dart
=> [mob] Fix exif time parsing

web/apps/photos/package.json, web/yarn.lock
https://github.com/react-dropzone/react-dropzone/issues/1411
=> [desktop] Fix drag and drop

web/packages/new/photos/services/exif.ts
- Prefer file tag over Exif/XMP
- Use both dim/orient from same source
Tested with a portrait (HEIC) photo taken on an iPhone. Such files have an orientation with in the Exif section.
```
$ exiftool -u -G IMG_xxxx.HEIC | grep Orient            
[EXIF]          Orientation                     : Rotate 90 CW
```
=> [web] Account for Exif orientation when extracting width and height

auth/lib/services/window_listener_service.dart
=> [auth] Increase default  window height

cli/main.go
=> [cli] Skip CLI init for docs,versions & help commad

mobile/lib/core/error-reporting/super_logging.dart, mobile/lib/services/machine_learning/ml_indexing_isolate.dart, mobile/lib/ui/settings/ml/ml_user_dev_screen.dart
Extra debug options related to ML
=> Ram logging

web/apps/photos/eslint.config.mjs, web/packages/accounts/components/two-factor/VerifyTwoFactor.tsx, web/packages/accounts/services/srp-remote.ts, web/packages/base/http.ts, web/packages/shared/components/VerifyMasterPasswordForm.tsx
...to match how the old HTTPService ones would've behaved.
=> [web] Improve logging of new HTTP errors

mobile/pubspec.yaml
=> [mob][photos] bump for internal release

mobile/lib/services/collections_service.dart
=> [mob] Fix collection attribute motification

mobile/lib/ui/settings/advanced_settings_screen.dart
=> [mob] Remove internal flag

docs/docs/.vitepress/sidebar.ts, docs/docs/photos/faq/video-streaming.md
=> feat: create video-streaming.md

.github/workflows/server-publish.yml
Fixes for https://github.com/ente-io/ente/pull/5088
=> [server] Fix publish workflow

mobile/lib/ui/tools/editor/video_editor_page.dart
Previously video editor was giving subpar quality videos, this fixes it and also re-encodes videos using libx264 mp4 format.
This will also increase the time to process the edited video.
=> [mob] video editor fixes

mobile/lib/main.dart
Remove internal user flag for media kit
=> [mob] remove internal user flag for media kit

mobile/lib/utils/share_util.dart
=> [mob] Share only image for live photos

auth/assets/custom-icons/_data/custom-icons.json, auth/assets/custom-icons/icons/gateio.svg
Add new icon to ente auth (gateio.svg)
and Add Gate.io icon to custom-icons.json
=> [auth] Add Gate.io icon

server/pkg/api/family.go
=> [sever] Minor fixes in modify-storage endpoint

server/pkg/api/collection.go, server/pkg/controller/collections/diff.go, server/pkg/repo/collection.go
We still have some traffic from old mobile client v0.7.xx that is making call to the v1 endpoint.
=> [server] Clean up old logic for collection diff

web/apps/photos/src/components/SubscriptionCard.tsx, web/packages/new/photos/services/user-details.ts
Sibling of https://github.com/ente-io/ente/pull/5123
=> [web] Update storage card when family member's storage limit is configured

.github/workflows/auth-internal-release.yml, .github/workflows/auth-release.yml, auth/lib/core/network.dart, auth/lib/ui/account/login_pwd_verification_page.dart, auth/lib/utils/dialog_util.dart, auth/pubspec.lock, auth/pubspec.yaml
=> [auth] Upgrade dio

docs/docs/photos/faq/security-and-privacy.md
=> [docs] Update

server/pkg/repo/collection.go, server/pkg/repo/collection_files.go
Moving few methods related to collection_files in diff file.
=> [server] Minor refactor

server/migrations/97_file_data_user_update_idx.down.sql, server/migrations/97_file_data_user_update_idx.up.sql
=> [server] Add index on file_data(user_id,updated_at)

web/apps/photos/src/components/PhotoViewer/index.tsx
Fixes: https://github.com/ente-io/ente/issues/5125
=> [web] Fix rendering of files without extension

server/pkg/controller/filedata/controller.go
=> [server] Wait for fileData put & fail fetch if more than 5 object fails

server/pkg/controller/filedata/controller.go
=> [server] Add missing bucketId

server/pkg/controller/filedata/controller.go
=> [server] Prefer b6 for read

server/pkg/controller/filedata/controller.go
=> [server] Swallow file data fetch err

server/pkg/controller/user/userauth.go
=> [server] Panic instead of fatal err

server/pkg/controller/filedata/controller.go, server/pkg/controller/filedata/replicate.go
=> [server] Read embeddings from different bucket & logging improvements

docs/docs/photos/faq/hidden-and-archive.md
Removed Hiding is currently only supported in the Ente mobile app, and items hidden from the mobile app will not be visible in the web and desktop app.
=> docs-edit hiding

mobile/lib/db/file_updation_db.dart, mobile/lib/services/local_file_update_service.dart, mobile/lib/ui/viewer/file/zoomable_live_image_new.dart
=> [mob] Clean up migration for livePhoto

mobile/lib/services/local/local_sync_util.dart, mobile/lib/services/local_sync_service.dart
=> [mob] Clean up deprecated invalidFileIDs

mobile/lib/services/video_memory_service.dart, mobile/lib/ui/viewer/actions/file_selection_actions_widget.dart
This PR introduces a feature that takes a list of images as input and generates a video output. Each image is displayed for 2 seconds before transitioning to the next image with smooth animations (fade, slide, etc.).
=> [mob][photos] Video memory

mobile/android/app/proguard-rules.pro, mobile/ios/Podfile.lock, mobile/lib/ui/viewer/file/video_widget_media_kit_common.dart, mobile/lib/ui/viewer/file/video_widget_native.dart
Fix Share functionality in android due to the R8 minify not working well, had to add a proguard rule.
Also fix the caption in android for streams.
Also fix the buffering indicator for media kit player.
=> [mob][fix] share & description in android

mobile/lib/core/error-reporting/super_logging.dart, mobile/lib/utils/device_info.dart
Logging the Android version will make it easier to identify if an issue is linked to certain Android version(s).
=> [mob][photos] Log android version along with device name

web/.prettierignore, web/.prettierrc.json
The crowdin action reverts this otherwise
=> [web] Ask prettier to not modify objectWrap in translations

web/packages/gallery/components/viewer/FileViewer.tsx, web/packages/gallery/components/viewer/photoswipe.ts
=> [web] Handle deletion of last slide

auth/lib/models/code.dart, auth/lib/onboarding/view/setup_enter_secret_key_page.dart, auth/lib/ui/algorithm_selector_widget.dart, auth/lib/ui/settings/data/import/bitwarden_import.dart
This PR add support to edit the number of digits (between 1 to 10) for the 2FA codes and also give an option to select algorithms
=> [auth] Add support for editing number of digits & algorithm

mobile/lib/db/device_files_db.dart, mobile/lib/services/sync/import/diff.dart, mobile/lib/services/sync/import/local_assets.dart, mobile/lib/services/sync/import/model.dart, mobile/lib/services/sync/local_sync_service.dart
=> [mob] Refactor local import

docs/docs/photos/faq/general.md
=> docs-ios backup

mobile/lib/ui/viewer/file_details/favorite_widget.dart
https://github.com/user-attachments/assets/99f0e0cd-d38a-4f7b-ad3e-c75ed43c6d0b
=> [mob][photos] Update favourite icon in File's app bar

mobile/lib/ui/viewer/file/zoomable_image.dart
=> [mob] Render image with high filter quality

server/pkg/controller/family/admin.go
=> [server] Update from address for family related emails

mobile/lib/db/ml/base.dart, mobile/lib/db/ml/db.dart, mobile/lib/db/ml/db_model_mappers.dart, mobile/lib/models/base_location.dart, mobile/lib/models/memories/clip_memory.dart, mobile/lib/models/memories/memories_cache.dart, mobile/lib/models/memories/people_memory.dart, mobile/lib/models/memories/smart_memory.dart, mobile/lib/models/memories/smart_memory_constants.dart, mobile/lib/models/ml/face/face_with_embedding.dart, mobile/lib/services/location_service.dart, mobile/lib/services/machine_learning/face_ml/person/person_service.dart, mobile/lib/services/machine_learning/ml_service.dart, mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart, mobile/lib/services/memories_cache_service.dart, mobile/lib/services/search_service.dart, mobile/lib/services/smart_memories_service.dart, mobile/lib/ui/home/memories/memories_widget.dart, mobile/lib/ui/home/memories/memory_cover_widget.dart, mobile/lib/ui/settings/debug/ml_debug_section_widget.dart, mobile/plugins/ente_feature_flag/lib/src/service.dart
=> [mob][photos] Memories

mobile/ios/Podfile.lock, mobile/ios/Runner.xcodeproj/project.pbxproj
=> [mob] Fix ios debug build

mobile/lib/services/home_widget_service.dart, mobile/pubspec.yaml
=> fix: fetch memories

auth/lib/services/user_service.dart, mobile/lib/services/account/user_service.dart
=> [auth][mob] Fix change-password flow immediately after login

mobile/lib/services/sync/local_sync_service.dart
=> [mob] Avoid redundant event

web/apps/photos/src/components/Export.tsx, web/apps/photos/src/components/ExportInProgress.tsx, web/apps/photos/src/services/collectionService.ts, web/apps/photos/src/services/export/index.ts, web/apps/photos/src/services/upload/upload-service.ts, web/apps/photos/src/services/upload/uploadManager.ts, web/apps/photos/src/utils/collection.ts, web/apps/photos/src/utils/file/index.ts, web/packages/build-config/tsconfig-next.json, web/packages/build-config/tsconfig-typecheck.json, web/packages/media/collection.ts, web/packages/media/file-metadata.ts, web/packages/media/file-type.ts, web/packages/new/photos/components/FileDateTimePicker.tsx, web/packages/new/photos/services/collection.ts, web/packages/utils/array.ts, web/packages/utils/parse.ts, web/packages/utils/promise.ts, web/packages/utils/transform.ts, web/packages/utils/tsconfig.json
Part 2 of https://github.com/ente-io/ente/pull/5353
=> [web] Enum cleanup (towards enabling isolatedDeclarations) 

mobile/lib/utils/standalone/data.dart
=> [mob] Fix formatBytes for TB unit

mobile/lib/app.dart, mobile/lib/services/home_widget_service.dart, mobile/lib/ui/settings/debug/ml_debug_section_widget.dart
Resync memories on widget tap.
=> [mob][photos] resync memories on widget tap

.github/workflows/server-publish.yml, server/docs/publish.md
In prep for its new baby sibling, ghcr/web.
=> [server] Change server/ghcr => ghcr/server

mobile/lib/services/memories_cache_service.dart
=> [mob][photos] Fix widget infinite load

mobile/lib/services/magic_cache_service.dart, mobile/lib/services/memories_cache_service.dart
=> [mob][photos] Memory final fix

mobile/lib/services/home_widget_service.dart, mobile/lib/services/language_service.dart, mobile/lib/services/memory_home_widget_service.dart, mobile/lib/services/search_service.dart, mobile/lib/services/smart_memories_service.dart, mobile/lib/ui/home/memories/memory_cover_widget.dart, mobile/pubspec.yaml
Remove filler title and use proper locals.
=> [mob] remove filler as a title and use years ago instead

auth/assets/custom-icons/_data/custom-icons.json, auth/assets/custom-icons/icons/patient_access.svg
Hi, sincere apologies if there are any issues I’ve created. I’m new to pull requests. I attach a Patient Access icon for Ente Auth. If everything goes well I (if it’s okay) will be happy to help in the future.
Kind regards,
Jack
=> [auth][icon] Patient Access

mobile/lib/generated/intl/messages_de.dart, mobile/lib/generated/intl/messages_es.dart, mobile/lib/generated/intl/messages_fr.dart, mobile/lib/generated/intl/messages_it.dart, mobile/lib/generated/intl/messages_ja.dart, mobile/lib/generated/intl/messages_nl.dart, mobile/lib/generated/intl/messages_pt.dart, mobile/lib/generated/intl/messages_zh.dart, mobile/plugins/ente_feature_flag/lib/src/service.dart
=> [mob] Fix npe in featureFlag service

mobile/lib/ui/viewer/file_details/upload_icon_widget.dart
=> [mob] Log sync status when uploadIcon is hidden

.github/workflows/codeql.yml
Here is the original autogenerated template on which this is based:
```yaml
#
#
#
name: "CodeQL Advanced"
on:
push:
branches: [ "main" ]
pull_request:
branches: [ "main" ]
schedule:
- cron: '22 1 * * 1'
jobs:
analyze:
name: Analyze (${{ matrix.language }}) # Runner size impacts CodeQL analysis time. To learn more, please see:
runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
permissions:
security-events: write
packages: read
actions: read
contents: read
strategy: fail-fast: false matrix: include:
- language: actions build-mode: none
- language: c-cpp build-mode: autobuild - language: go build-mode: autobuild - language: java-kotlin build-mode: autobuild - language: javascript-typescript build-mode: none - language: ruby build-mode: none - language: swift …
```
=> [meta] Create custom codeql.yml

mobile/lib/db/ml/db.dart, mobile/lib/services/isolate_functions.dart, mobile/lib/services/isolate_service.dart, mobile/lib/services/machine_learning/face_thumbnail_generator.dart, mobile/lib/services/machine_learning/ml_computer.dart, mobile/lib/services/machine_learning/ml_constants.dart, mobile/lib/services/machine_learning/semantic_search/query_result.dart, mobile/lib/services/machine_learning/semantic_search/semantic_search_service.dart, mobile/lib/services/smart_memories_service.dart, mobile/lib/utils/face/face_box_crop.dart
Made changes to more efficiently handle image embeddings caching, keeping them cached only in MLComputer and only for limited times when the user needs it.
=> [mob][photos] Image embedding caching perf

server/ente/billing.go, server/migrations/98_increase_free_storage.down.sql, server/migrations/98_increase_free_storage.up.sql
=> [server] Up free storage

mobile/lib/ente_theme_data.dart, mobile/lib/l10n/l10n.dart, mobile/lib/ui/sharing/pickers/link_expiry_picker_page.dart, mobile/lib/ui/viewer/date/date_time_picker.dart, mobile/lib/ui/viewer/date/edit_date_sheet.dart, mobile/pubspec.yaml
Switched to our own date picker in the last place we were using package (link expiry page) and removed package. 
=> [mob][photos] Remove datepicker dependency

mobile/lib/ui/viewer/people/link_email_screen.dart, mobile/lib/ui/viewer/people/people_util.dart, mobile/lib/ui/viewer/people/save_or_edit_person.dart
Simplified the action of assigning "me" by sticky-ing the users email on top (in case "me" is not assigned).
=> [mob][photos] Improve tag "me" flow

docs/docs/photos/faq/subscription.md
Corrected the free storage from 5 GB to 10 GB.
=> Updated subscription FAQ

web/apps/photos/src/components/FileList.tsx
https://github.com/ente-io/ente/pull/5498
=> [web] Fix assignment typo in previous PR

.github/workflows/server-publish-ghcr.yml, .github/workflows/web-publish-ghcr.yml
Continuation of https://github.com/ente-io/ente/pull/5456
=> [meta] Update workflow permissions

server/configurations/local.yaml, server/pkg/utils/config/config.go
=> [server] Replace EnvVarKeyReplacer "-" with "_"

docs/docs/self-hosting/guides/external-s3.md
Took me all night to figure this one out. Hopefull no one has to deep dive like this.
Ref to why it changed: https://github.com/minio/minio/tree/master/docs/config#api
=> Update `mc` command for cors

desktop/src/main.ts
Ref: https://github.com/ente-io/ente/discussions/4521
=> [desktop] Show/hide the window on tray icon double click on Linux/Win

mobile/pubspec.yaml
f-droid is at `1.0.1` so have to go from `1.0.0` to  `1.0.2`
=> [mob][photos] Bump up to v1.0.2

web/apps/photos/src/styles/photoswipe.css, web/packages/gallery/components/viewer/photoswipe.ts
=> [web] Video streaming WIP - Part x/x

docs/docs/self-hosting/troubleshooting/docker.md, docs/docs/self-hosting/troubleshooting/misc.md
=> [docs] Document some self hosting questions 

docs/docs/.vitepress/sidebar.ts, docs/docs/self-hosting/troubleshooting/docker.md
Updates for https://github.com/ente-io/ente/pull/5574
=> [docs] Self hosting updates

mobile/lib/services/machine_learning/ml_result.dart
=> [mob][photos] log avatar faceID issue

web/apps/photos/src/services/logout.ts, web/apps/photos/src/services/upload/uploadManager.ts, web/packages/gallery/components/viewer/photoswipe.ts, web/packages/gallery/services/video.ts
And start WIP work on playlist generation.
=> [web] Video streaming touchup

mobile/lib/services/memories_cache_service.dart
Only smart memories if local indexing is on
=> [mob][photos] Only smart memories if local indexing is on

web/apps/photos/src/services/upload/date.ts, web/apps/photos/tests/upload.test.ts
Tested on the sample provided by the customer.
=> [web] Add support for iOS date format

mobile/lib/l10n/l10n.dart, mobile/lib/ui/settings/language_picker.dart
=> [mob] Add support for pt_PT

auth/assets/custom-icons/_data/custom-icons.json, auth/assets/custom-icons/icons/mbin.svg
Add a custom icon for the [Mbin](https://joinmbin.org/) fediverse software. SVG sourced from the linked page and modified to remove background. Additional `altNames` for some popular or important Mbin instances: `kbin` (several instances), `thebrainbin` (popular instance) and `gehirneimer` (Mbin co-developer bentigorlich's instance).
Untested
=> [auth] Add Mbin custom icon

auth/lib/ui/settings/data/import/aegis_import.dart
Fixes https://github.com/ente-io/ente/issues/5438 https://github.com/ente-io/ente/issues/5324 https://github.com/ente-io/ente/issues/5188 https://github.com/ente-io/ente/issues/5064
Tested locally
=> [Auth] Fix import from aegis

cli/README.md
In my case to change export directory was necessary to add "--app"
=> [cli] Update documentation for change of export directory

web/apps/photos/src/services/upload/remote.ts, web/packages/gallery/components/viewer/data-source.ts, web/packages/gallery/services/download.ts, web/packages/gallery/services/file-data.ts, web/packages/gallery/services/video.ts
Behind a ff flag, meant for testing https://github.com/ente-io/ente/pull/5601
=> [web] Public album streaming

server/cmd/museum/main.go, server/pkg/api/cast.go, server/pkg/api/file_data.go, server/pkg/api/public_collection.go, server/pkg/controller/file.go, server/pkg/controller/filedata/controller.go, server/pkg/controller/filedata/preview_files.go
=> [server] Preview public albums

mobile/pubspec.yaml
=> [mob] Bump version 1.0.4

mobile/lib/db/files_db.dart, mobile/lib/db/ml/db.dart, mobile/lib/services/collections_service.dart, mobile/lib/ui/viewer/file_details/albums_item_widget.dart, mobile/lib/ui/viewer/gallery/gallery_app_bar_widget.dart, mobile/lib/utils/ml_util.dart
=> [mob] Refactor & remove unused methods

server/pkg/controller/filedata/s3.go
=> [server] Add retry while putting metadata obj in s3

server/cmd/museum/main.go
=> [server] increase max pg connection 30 -> 45

web/apps/photos/src/components/Upload.tsx, web/apps/photos/src/components/UploadProgress.tsx, web/apps/photos/src/components/WatchFolder.tsx, web/packages/base/locales/en-US/translation.json
=> [web] Use top level as fallback for leaf files to avoid confusing error

server/pkg/controller/user/userauth.go
=> [server] don't send OTT if registration is disabled Fixes #5684

auth/ios/Podfile.lock, auth/pubspec.lock, auth/pubspec.yaml, auth/windows/flutter/generated_plugin_registrant.cc, auth/windows/flutter/generated_plugins.cmake
Fix build failing on iOS 18.4 by [upgrading sentry](https://github.com/getsentry/sentry-dart/issues/2771#issuecomment-2717968324)
=> [auth] Fix auth not building for iOS 18.4

mobile/ios/Podfile.lock, mobile/lib/db/files_db.dart, mobile/lib/services/preview_video_store.dart, mobile/lib/ui/home/status_bar_widget.dart, mobile/lib/ui/settings/backup/backup_item_card.dart, mobile/lib/ui/settings/backup/backup_status_screen.dart, mobile/lib/utils/file_util.dart
=> [mob] streaming hot fixes

desktop/eslint.config.mjs, desktop/src/main/services/ffmpeg.ts, desktop/src/main/services/image.ts, desktop/src/main/stream.ts, desktop/src/main/utils/common.ts, desktop/src/main/utils/temp.ts, web/apps/photos/src/services/upload/remote.ts, web/packages/base/http.ts, web/packages/gallery/components/viewer/photoswipe.ts, web/packages/gallery/services/convert.ts, web/packages/gallery/services/download.ts, web/packages/gallery/services/ffmpeg/index.ts, web/packages/gallery/services/video.ts, web/packages/gallery/utils/native-stream.ts, web/packages/utils/promise.ts
Stream generation works during live uploads (behind a dev feature flag).
=> [desktop] HLS gen - WIP - Part x/x

mobile/lib/services/memories_cache_service.dart, mobile/lib/ui/viewer/actions/file_selection_actions_widget.dart
Fixes 'Not person' null response
=> [mob][photos] Fixes 'Not person' null response

mobile/lib/core/configuration.dart, mobile/lib/ui/settings/developer_settings_widget.dart, mobile/lib/ui/settings_page.dart, mobile/lib/ui/tabs/home_widget.dart
=> [mob] Hide ref promo banner for non-ente instance

mobile/lib/services/machine_learning/machine_learning_controller.dart, mobile/lib/utils/email_util.dart
=> [mob] Fix Splash screens stuck issues during dev with iOS simulator

mobile/lib/services/preview_video_store.dart, mobile/lib/ui/settings/backup/backup_status_screen.dart
=> [mob] re-encode audio ffmpeg & update backup status screen

mobile/lib/ui/viewer/file/thumbnail_widget.dart, mobile/lib/ui/viewer/search/result/person_face_widget.dart, mobile/lib/utils/face/face_box_crop.dart, mobile/pubspec.yaml
Use custom task queue instead of pool package for face thumbnail generation
=> [mob][photos] Faces queue

server/pkg/controller/user/user.go
=> [server] Fix jwt token expiry time

auth/pubspec.lock, auth/pubspec.yaml
The dependency was overridden for [this change](https://github.com/juliansteenbakker/flutter_secure_storage/pull/673) which is merged now and available from flutter_secure_storage version 9.1.0.
=> [Auth] Remove dependency override

mobile/lib/models/gallery_type.dart, mobile/lib/services/collections_service.dart, mobile/lib/services/sync/trash_sync_service.dart, mobile/lib/ui/viewer/actions/file_selection_actions_widget.dart, mobile/lib/utils/delete_file_util.dart
- Fix issue where user is not able to delete own files in a shared album
- Fix issue where deletion of not yet uploaded files leads to showing grey boxes in gallery
=> [mob][photos] Deletion fixes

server/cmd/museum/main.go, server/pkg/controller/file.go
=> [server] Use access ctrl for verifying access

mobile/lib/services/memories_cache_service.dart
Fixed regression in memories update scheme.
=> [mob][photos] Fix memories update regression

mobile/lib/utils/face/face_box_crop.dart
Change logging flow for face thumbnail generation
=> Face thumbnail logging

mobile/pubspec.yaml
=> [mob] Bump version v1.0.7

mobile/android/build.gradle, mobile/lib/generated/intl/messages_de.dart, mobile/lib/generated/intl/messages_es.dart, mobile/lib/generated/intl/messages_eu.dart, mobile/lib/generated/intl/messages_fr.dart, mobile/lib/generated/intl/messages_no.dart, mobile/lib/generated/intl/messages_pt_BR.dart, mobile/lib/ui/viewer/file/preview_status_widget.dart, mobile/pubspec.lock, mobile/pubspec.yaml
=> [mob] fix ffmpeg-kit android compilation

mobile/lib/generated/intl/messages_en.dart, mobile/lib/l10n/intl_en.arb, mobile/lib/ui/tabs/home_widget.dart
Fix [issue with sharing to Ente](https://github.com/ente-io/ente/discussions/5755)
=> [mob][photos] Fix share to Ente

mobile/pubspec.yaml
=> [mob] Bump version v1.0.8+1038

mobile/pubspec.yaml
Bumping version to prepare for next release.
=> [mob] Bump version v1.0.9

mobile/lib/ui/home/status_bar_widget.dart
=> [mob] Navigate to BackupSettings when tapping "Waiting for network" status

mobile/lib/core/network/network.dart, mobile/lib/generated/l10n.dart, mobile/pubspec.yaml
Big file uploads fail when using NativeAdapter, this PR:
=> [mob] remove NativeAdapter to support big file upload

server/pkg/api/file_data.go, server/pkg/utils/handler/handler.go
=> [server] Fix invalid 5xx error for bad requests

server/pkg/api/user.go, server/pkg/controller/user/srp.go
=> [server]  Improve logs

server/pkg/controller/discord/discord.go, server/pkg/middleware/rate_limit.go
=> [server] Reduce alert noise

server/ente/collection.go
=> [server] Enable sharing for fav

mobile/lib/models/gallery_type.dart, mobile/lib/ui/viewer/gallery/gallery_app_bar_widget.dart
=> [mob] Enable sharing for fav collection

auth/lib/l10n/arb/app_en.arb, auth/lib/onboarding/view/setup_enter_secret_key_page.dart
=> [auth] Auth reorder widgets

server/pkg/controller/user/srp.go, server/pkg/controller/user/user.go, server/pkg/controller/user/userauth.go, server/pkg/middleware/rate_limit.go, server/pkg/utils/rate_limit.go
=> [server] Improve handling of errors

mobile/lib/generated/intl/messages_ar.dart, mobile/lib/generated/intl/messages_cs.dart, mobile/lib/generated/intl/messages_de.dart, mobile/lib/generated/intl/messages_en.dart, mobile/lib/generated/intl/messages_es.dart, mobile/lib/generated/intl/messages_fa.dart, mobile/lib/generated/intl/messages_fr.dart, mobile/lib/generated/intl/messages_id.dart, mobile/lib/generated/intl/messages_it.dart, mobile/lib/generated/intl/messages_ja.dart, mobile/lib/generated/intl/messages_lt.dart, mobile/lib/generated/intl/messages_nl.dart, mobile/lib/generated/intl/messages_no.dart, mobile/lib/generated/intl/messages_pl.dart, mobile/lib/generated/intl/messages_pt_BR.dart, mobile/lib/generated/intl/messages_pt_PT.dart, mobile/lib/generated/intl/messages_ro.dart, mobile/lib/generated/intl/messages_ru.dart, mobile/lib/generated/intl/messages_tr.dart, mobile/lib/generated/intl/messages_uk.dart, mobile/lib/generated/intl/messages_vi.dart, mobile/lib/generated/intl/messages_zh.dart, mobile/lib/generated/l10n.dart, mobile/lib/l10n/intl_en.arb, mobile/lib/services/preview_video_store.dart, mobile/lib/ui/viewer/file/video_widget.dart, mobile/lib/utils/exif_util.dart, mobile/lib/utils/ml_util.dart
- This PR removes the check for local streaming video settings
- [Internal users] added support for playing video stream for shared files.
In order to cache the playlist and encrypted video stream, we will need make backend API changes. Once those are done, we will remove the internal user flag.
=> [mob] Play streamable video whenever available

.github/workflows/mobile-internal-release-rust.yml
Add Github Action for mobile release that includes the use of rust
=> [infra] github actions internal release with rust

server/ente/filedata/filedata.go, server/pkg/api/file_data.go, server/pkg/api/public_collection.go, server/pkg/controller/filedata/controller.go
=> [server] Sending 204 instead of 404 for no data

server/pkg/controller/filedata/controller.go
- Sibling of https://github.com/ente-io/ente/pull/5880
- Tested using https://github.com/ente-io/ente/pull/5885
=> [server] 204 minor fix

mobile/lib/services/preview_video_store.dart, mobile/lib/ui/viewer/file/video_widget.dart
Title
- Verified from logs that shared stream videos are getting cached correctly.
=> [mob] Cache video streams for shared files

web/packages/gallery/services/file-data.ts, web/packages/new/photos/services/ml/ml-data.ts, web/packages/new/photos/services/ml/worker.ts
Ref: https://github.com/ente-io/ente/pull/5895
=> [desktop] Incorporate mldata version check

web/packages/gallery/services/ffmpeg/web.ts
https://emscripten.org/docs/api_reference/Filesystem-API.html#workerfs
=> [web] Use wasm workerfs to directly mount blob instead of reading it in memory

server/ente/filedata/filedata.go, server/ente/filedata/putfiledata.go, server/pkg/controller/filedata/controller.go, server/pkg/repo/passkey/passkey.go
=> [server] Version check support during ml data put

mobile/lib/ui/home/landing_page_widget.dart
=> [mob] Increase resumable upload rollout 20 -> 50%

mobile/lib/extensions/user_extension.dart, mobile/lib/models/collection/collection.dart, mobile/lib/utils/person_contact_linking_util.dart
=> [mob] Show person's name for shared fav collection

auth/lib/locale.dart, mobile/lib/l10n/l10n.dart
Fixes https://github.com/ente-io/ente/issues/5655
=> [mob][auth] Fix: respect system locale preference

mobile/lib/services/machine_learning/face_ml/face_filtering/face_filtering_constants.dart, mobile/lib/ui/viewer/file_details/face_widget.dart, mobile/lib/ui/viewer/file_details/faces_item_widget.dart
=> [mob][photos] Show detected faces with lower score on UI

auth/assets/custom-icons/_data/custom-icons.json, auth/assets/custom-icons/icons/bonify.svg
Icon was not displaying.
| before | after |
| --- | --- |
|![Screenshot From 2025-05-16 02-40-15](https://github.com/user-attachments/assets/59d84c64-3bc5-4b03-8704-ccabb4dc80af)|![Screenshot From 2025-05-16 03-01-49](https://github.com/user-attachments/assets/ade3df70-043a-4ac8-abca-d0f2d8cf4f59)|
=> [auth] fix bonify icon

mobile/lib/l10n/intl_en.arb, mobile/lib/ui/viewer/file/native_video_player_controls/seek_bar.dart
=> [mob] Change seekBar color for video to backgroundElevatedLight

.github/workflows/auth-release.yml
Fixes https://github.com/ente-io/ente/issues/5901
=> [auth][Fix] Add cronetHttpNoPlay flag for playstore builds

mobile/lib/models/preview/playlist_data.dart, mobile/lib/services/preview_video_store.dart, mobile/lib/ui/viewer/file/video_widget_media_kit.dart, mobile/lib/ui/viewer/file/video_widget_media_kit_common.dart, mobile/lib/ui/viewer/file/video_widget_native.dart
=> [mob] Fix seekBar duration for videos with missing duration in metadata

mobile/lib/extensions/user_extension.dart, mobile/lib/services/machine_learning/face_ml/person/person_service.dart
=> [mob][Fix] Fallback to email forname if personService init is pending

web/packages/new/photos/services/search/worker.ts
Fixes: https://github.com/ente-io/ente/issues/5942
=> [web] Unicode search

cli/internal/api/login.go, cli/pkg/sign_in.go
=> [cli] Specify ott purpose

server/cmd/museum/main.go
https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Range
=> [server] Whitelist range header

auth/linux/packaging/enteauth.appdata.xml, auth/pubspec.lock, auth/pubspec.yaml, auth/scripts/release_tag.sh
=> [auth] Script to creating tag & modifying flatback metadata

server/pkg/controller/filedata/video.go
=> [server] Fix err handling during stream upload

web/packages/base/crypto/ente-impl.ts, web/packages/base/crypto/libsodium.ts, web/packages/base/crypto/worker.ts, web/packages/gallery/services/upload/upload-service.ts
=> [web] Hash functions - Document and namespace

server/migrations/99_alter_file_data_column_type.down.sql, server/migrations/99_alter_file_data_column_type.up.sql
=> [server] Change file_data.obj_size column type

server/pkg/controller/file.go
=> [server] Increase file size limit 5 -> 10 GiB

server/pkg/repo/passkey/passkey.go
=> Fix: Return correct status code for maxPassKey err

.github/workflows/mobile-internal-release.yml
=> [meta] Update mobile-internal-release.yml

web/apps/photos/src/services/upload-manager.ts, web/packages/gallery/services/upload/index.ts, web/packages/gallery/services/upload/remote.ts, web/packages/gallery/services/upload/upload-service.ts, web/packages/new/photos/services/user.ts
Finishes the set of changes from https://github.com/ente-io/ente/pull/5997 and https://github.com/ente-io/ente/pull/6002.
=> [web] Multipart changes - Finish

mobile/lib/ui/tools/editor/image_editor_page.dart
Increase the width of the container to prevent text overflow
=> [mob] Minor UI patch

server/ente/filedata/filedata.go, server/pkg/controller/filedata/preview_files.go, server/pkg/controller/filedata/s3.go
=> [server] Add multipart upload support for preview data

desktop/package.json, desktop/src/main.ts, desktop/yarn.lock, web/apps/payments/package.json, web/apps/photos/package.json, web/package.json, web/packages/accounts/package.json, web/packages/base/package.json, web/packages/build-config/package.json, web/packages/gallery/package.json, web/packages/new/package.json, web/yarn.lock
=> [desktop][web] Dependency updates

desktop/src/main/services/ffmpeg-worker.ts
https://trac.ffmpeg.org/wiki/Scaling#AvoidingUpscaling
=> [desktop] HLS - Avoid upscaling

mobile/lib/db/files_db.dart, mobile/lib/services/filter/db_filters.dart, mobile/lib/services/filter/shared.dart, mobile/lib/ui/home/home_gallery_widget.dart
=> [mob] Fix: Hide both shared and collect files

mobile/lib/services/machine_learning/ml_indexing_isolate.dart, mobile/lib/services/machine_learning/ml_service.dart, mobile/lib/services/memories_cache_service.dart, mobile/lib/ui/viewer/people/cluster_page.dart
- Expose flag for when ML and Memories is running
- UI fix for deleting all files in cluster 
- Log times ML models are loaded
Tested in debug mode on my pixel 8.
=> [mob][photos] Minor ML improvements

web/apps/photos/src/components/Upload.tsx, web/apps/photos/src/services/upload-manager.ts, web/apps/photos/tests/upload.test.ts, web/packages/gallery/export-dirs.ts, web/packages/gallery/services/upload/index.ts, web/packages/gallery/services/upload/metadata-json.ts, web/packages/gallery/services/upload/upload-service.ts, web/packages/new/photos/services/export-migration.ts, web/packages/new/photos/services/export.ts, web/packages/new/photos/utils/native-fs.ts
Fixes: 
- https://github.com/ente-io/ente/discussions/5920
- https://github.com/ente-io/ente/discussions/5950
=> [web] Use path prefix as context when collating metadata and live photos

mobile/lib/ui/collections/collection_list_page.dart, mobile/lib/ui/collections/flex_grid_view.dart, mobile/lib/utils/standalone/task_queue.dart
Plus some improvements from @ashilkn
=> [mob][photos] All albums screen UI/UX and performance improvements

server/pkg/controller/filedata/s3.go
=> [server] Fix: Typo in bucket name for filedata multipart url

server/pkg/middleware/rate_limit.go
=> [server] Update limit

server/pkg/api/authenticator.go
=> [Server] Return epochTime in microSeconds

auth/linux/packaging/enteauth.appdata.xml, auth/pubspec.yaml
=> [auth] Bump auth version 4.4.0

mobile/lib/services/memories_cache_service.dart, mobile/lib/services/notification_service.dart
Auto dismiss 'On this day' notification at the end of the day. Only on Android since there's no API for this on iOS.
Tested in debug mode on my pixel 8 phone.
=> timeout on this day notification android at eod

mobile/lib/services/collections_service.dart, mobile/lib/ui/viewer/file_details/added_by_widget.dart, mobile/lib/ui/viewer/gallery/component/gallery_file_widget.dart
User avatar in gallery file element and 'added by' field in file info were missing for files in public links opened via deeplink. This PR fixes this issue.
=> [mob][photos] Fix missing 'Added by' indicator in gallery file element and file info for when opening public links via deeplink

server/pkg/repo/filedata/repository.go
=> [server] Defer file data replication for 10min

mobile/lib/l10n/intl_fr.arb, mobile/lib/ui/viewer/file/file_details_widget.dart, mobile/lib/ui/viewer/file_details/exif_item_widgets.dart, mobile/lib/utils/exif_util.dart, mobile/lib/utils/file_uploader_util.dart, mobile/pubspec.lock, mobile/pubspec.yaml
Current exif package seems to be abandoned.
This fork for the exif package has few fixes & support for more formats.
New package: https://github.com/mgenware/exif_reader
Old package: https://github.com/bigflood/dartexif
Compiled and verified that I am able to view exif for few images.
=> [mob] Switch to exif_reader 

mobile/lib/ui/viewer/gallery/hooks/add_photos_sheet.dart, mobile/pubspec.lock, mobile/pubspec.yaml
Also increased the items in grid, as there's no scrollbar (pkg does not support it yet afaik)
=> [mob] Remember last scroll offset while adding assets from device

mobile/plugins/ente_crypto/lib/src/crypto.dart
For 3.38 GB file on iPhone 11
Old Hashing took 24792 ms
Hashing v2 took 10365 ms
Also tested it on a smaller file
```dart
// Returns the hash for a given file, chunking it in batches of hashChunkSize
Future<Uint8List> cryptoGenericHash(Map<String, dynamic> args) async {
final int startTime = DateTime.now().millisecondsSinceEpoch;
final sourceFile = File(args["sourceFilePath"]);
final sourceFileLength = await sourceFile.length();
final inputFile = sourceFile.openSync(mode: FileMode.read);
final state =
Sodium.cryptoGenerichashInit(null, Sodium.cryptoGenerichashBytesMax);
var bytesRead = 0;
bool isDone = false;
while (!isDone) {
var chunkSize = hashChunkSize;
if (bytesRead + chunkSize >= sourceFileLength) {
chunkSize = sourceFileLength - bytesRead;
isDone = true;
}
final buffer = await …
```
=> [mob] Use file stream to improve hashing speed

docs/docs/overview/community.md, docs/docs/overview/contribute.md, docs/docs/overview/help.md
=> [docs] Minor update

mobile/lib/module/download/manager.dart
=> [mob] Minor fixes for resumable download

web/apps/photos/src/services/collectionService.ts, web/packages/media/collection.ts, web/packages/media/file-metadata.ts, web/packages/media/file.ts, web/packages/media/magic-metadata.ts, web/packages/new/photos/services/collection.ts, web/packages/new/photos/services/files.ts, web/packages/utils/transform.ts
Still iterating on the code structure for this
=> [web] Code improvements

docs/docs/index.md
Added Ente's Bluesky and Instagram accounts
/
=> [docs] Added socials to docs

mobile/lib/services/magic_cache_service.dart, mobile/lib/services/memories_cache_service.dart, mobile/lib/services/search_service.dart, mobile/lib/utils/cache_util.dart
- Fixes issues with chinese characters
- Runs decoding in computer
=> [mob][photos] Improve caching for memories and magic

desktop/CHANGELOG.md, web/apps/photos/src/components/Sidebar.tsx, web/packages/gallery/services/upload/upload-service.ts, web/packages/gallery/services/video.ts
=> [desktop][web] Increase file size limit to 10 GB

mobile/lib/utils/file_uploader.dart
=> [mob] Increase fileSize limit to 10GiB

mobile/ios/Podfile.lock, mobile/ios/Runner.xcodeproj/project.pbxproj, mobile/lib/main.dart, mobile/lib/services/collections_service.dart, mobile/lib/services/machine_learning/ml_service.dart, mobile/lib/services/preview_video_store.dart, mobile/lib/services/sync/remote_sync_service.dart, mobile/lib/services/video_preview_service.dart, mobile/lib/ui/settings/advanced_settings_screen.dart, mobile/lib/ui/viewer/file/file_app_bar.dart, mobile/lib/ui/viewer/file/video_widget.dart, mobile/lib/ui/viewer/file_details/preview_properties_item_widget.dart
Tested locally and verified that I am able to play video preview
=> [mob] Add support for playing preview for shared public links

mobile/lib/services/machine_learning/compute_controller.dart
=> [mob] Fix: use OS specific logic for computing device health

mobile/lib/core/error-reporting/super_logging.dart, mobile/lib/core/network/ente_interceptor.dart
We can use this to trace the request on the server (if it actually reached server).
=> [mob] Log req id on network error

server/pkg/controller/filedata/video.go, server/pkg/repo/object_cleanup.go
=> [server] Gracefully handle client retry

mobile/lib/services/video_preview_service.dart
=> [mob][photos] fix streaming

mobile/lib/services/video_preview_service.dart
=> [mob][photos] use correct tonemap logic

cli/config.yaml.example, cli/internal/api/login_type.go, cli/main.go, cli/pkg/sign_in.go
Removed the need for specifying account's app url as server returns the same in the response to auth challenge.
=> [cli] Improve support handling passkey login for selfhost

auth/assets/custom-icons/_data/custom-icons.json, auth/assets/custom-icons/icons/ibkr.svg
Add custom icon for  IBKR (Interactive Brokers) investing platform
=> [Auth] Add custom icon - IBKR

auth/assets/custom-icons/_data/custom-icons.json, auth/assets/custom-icons/icons/zitadel.svg
The Zitadel icon is not available.
=> [auth] Added Zitadel icon

mobile/lib/services/memories_cache_service.dart, mobile/lib/ui/home/memories/all_memories_page.dart
Enable swiping between memory blocks when opening a memory from notification.
=> [mob][photos] Memory notification improvement

auth/pubspec.lock, auth/pubspec.yaml
Fixes https://github.com/ente-io/ente/issues/5789 https://github.com/ente-io/ente/issues/4523 https://github.com/ente-io/ente/issues/4099 https://github.com/ente-io/ente/issues/4270
=> [auth] fix unknown hard error on windows

mobile/lib/ui/viewer/people/people_page.dart, mobile/lib/ui/viewer/search/result/contact_result_page.dart, mobile/lib/ui/viewer/search/result/magic_result_screen.dart, mobile/lib/ui/viewer/search/result/search_result_page.dart
Fixes:
- Person gallery not reloading on adding new clusters to person. 
- Recommended filters disappears when setState is called without actually reloading the gallery.
=> [mob][photos] Fixes related to people page and recommended filters

mobile/lib/services/machine_learning/ml_service.dart, mobile/lib/ui/home/status_bar_widget.dart, mobile/lib/ui/tabs/home_widget.dart, mobile/plugins/ente_feature_flag/lib/src/service.dart
- Fix incorrectly showing ml consent bar
- Fix ml not starting on first login of second device
=> [mob][photos] Fix incorrectly showing ml consent bar

server/mail-templates/ott.html
This PR reduces ambiguity in OTT verification where some users replies to our mail for verification instead of entering the code in the application
=> [email] reduce ambiguity in OTT verification

auth/assets/custom-icons/icons/ibkr.svg
Fix the icon added in #6329 not displaying.
| before | after |
| ---- | ---- |
| ![Screenshot From 2025-06-26 13-13-24](https://github.com/user-attachments/assets/6873aaa9-da8a-4f2d-92a4-a8c2117e05da) | ![Screenshot From 2025-06-26 13-13-50](https://github.com/user-attachments/assets/6a5b142e-bbbb-4b54-80b9-71ddeae6c02b) |
=> [auth] fix ibkr icon

docs/docs/self-hosting/guides/tailscale.md
=> [docs] Fixed typos in tailscale.md

auth/lib/utils/auth_util.dart, mobile/lib/utils/auth_util.dart
Fallback to Pin/Passcode on iOS if fail to detect TouchID/FaceID
=> [auth][mob] Fall back to Passcode if FaceId not detected on iOS

auth/pubspec.yaml
=> [mob][auth] Bump up auth version to 4.4.1

mobile/lib/services/entity_service.dart, mobile/lib/services/machine_learning/face_ml/person/person_service.dart, mobile/lib/ui/sharing/user_avator_widget.dart
=> [mob] Use cached mapping for person avatar

mobile/lib/events/details_sheet_event.dart, mobile/lib/events/toggle_memory_animation_event.dart, mobile/lib/ui/actions/file/file_actions.dart, mobile/lib/ui/home/memories/full_screen_memory.dart
Play/pause memory animation when file bottom sheet is close/open respectively
=> [mob][photos] Handle play/pause animation in memory when bottom sheet open

mobile/lib/ui/notification/update/change_log_page.dart
=> [mob] Minor copy change

mobile/lib/services/update_service.dart, mobile/lib/ui/notification/update/change_log_page.dart
=> [mob] Update change log order

mobile/apps/photos/lib/ui/collections/flex_grid_view.dart
https://github.com/user-attachments/assets/1238695a-8e4a-44b3-99f1-569eacddcf1c
=> [mobile] Fix hero animation for `on Ente` section

mobile/apps/photos/lib/services/sync/remote_sync_service.dart
_shouldThrottleSync logic was changed to return True when multiPart was disabled. This resulted in incorrect throttling when user had disabled multipart and app was in fg.
=> [mob] Fix throttling when multipart is disabled

mobile/apps/photos/ios/EntePeopleWidget/EntePeopleWidget.swift, mobile/apps/photos/lib/ui/common/linear_progress_dialog.dart, mobile/apps/photos/lib/ui/huge_listview/draggable_scrollbar.dart, mobile/apps/photos/lib/ui/tabs/nav_bar.dart, mobile/apps/photos/lib/ui/viewer/file/native_video_player_controls/seek_bar.dart, mobile/apps/photos/lib/ui/viewer/file/video_widget_media_kit_common.dart, mobile/apps/photos/lib/ui/viewer/people/person_gallery_suggestion.dart
=> [mob][photos] hotfixes

mobile/apps/photos/lib/ui/collections/album/vertical_list.dart, mobile/apps/photos/lib/ui/tabs/shared/all_quick_links_page.dart
=> [mob][photos] haptic fixes

server/pkg/controller/user/user_details.go
=> [server] Handle expiry buffer in user_detail computation

mobile/apps/photos/lib/models/memories/memories_cache.dart, mobile/apps/photos/lib/models/memories/people_memory.dart, mobile/apps/photos/lib/services/memories_cache_service.dart, mobile/apps/photos/lib/ui/viewer/people/person_gallery_suggestion.dart, mobile/apps/photos/lib/ui/viewer/people/save_or_edit_person.dart
- Fix bug where clicking on birthday notifications opens the person page (as fallback) and not the person memory (as intended)
- Minor UI fixes 
=> [mob][photos] Birthday redirect fix

mobile/apps/photos/lib/ui/payment/store_subscription_page.dart
=> [mob] Improve error handling on subscription page

web/apps/photos/src/components/FileList.tsx, web/apps/photos/src/components/FileListWithViewer.tsx, web/apps/photos/src/pages/gallery.tsx, web/apps/photos/src/pages/shared-albums.tsx
Mostly done, only minor touchups remain
=> [web] File list refactoring and cleanup - Part 3

.github/workflows/auth-release.yml, mobile/apps/auth/ios/Podfile.lock, mobile/apps/auth/linux/packaging/enteauth.appdata.xml, mobile/apps/auth/pubspec.yaml
=> [auth] Fix appimage tool path in github workflow

server/pkg/controller/filedata/controller.go
=> [server][file data] Use primary bucket as preferred bucket to read

web/apps/auth/src/pages/auth.tsx
=> [web] Update download link for auth apps

server/pkg/repo/trash.go
=> [server] Use IS FALSE to match partial index

mobile/apps/photos/lib/db/files_db.dart
=> [mob][photos] Fix query to remove dup enteries

mobile/apps/photos/lib/db/files_db.dart, mobile/apps/photos/lib/services/sync/remote_sync_service.dart, mobile/apps/photos/pubspec.lock
This also now runs query only once in a session.
=> [mob][photos] Fix db query & swallow error

mobile/apps/auth/assets/custom-icons/_data/custom-icons.json, mobile/apps/auth/assets/custom-icons/icons/lifemiles.svg
Add custom SVG icon for [LifeMiles](https://www.lifemiles.com/) to support branding in UI components.
=> [auth] add custom icon for lifemiles

docs/docs/self-hosting/administration/users.md, docs/docs/self-hosting/installation/config.md, docs/docs/self-hosting/troubleshooting/docker.md
This PR updates troubleshooting for Docker, adds information for configuration of DB and fixes a dead link for configuration section.
=> [docs]  refactor troubleshooting for docker

desktop/.github/workflows/desktop-release.yml, desktop/.prettierrc.json, docs/.prettierrc.json, docs/docs/auth/migration/index.md, docs/docs/photos/faq/desktop.md, docs/docs/photos/faq/security-and-privacy.md, docs/docs/photos/features/cast/index.md, docs/docs/photos/features/family-plans.md, docs/docs/photos/features/watch-folders.md, docs/docs/photos/migration/from-local-hard-disk.md, docs/docs/photos/troubleshooting/files-not-uploading.md, infra/staff/.prettierrc.json, infra/workers/.prettierrc.json, web/.prettierrc.json
Ref:
- https://prettier.io/blog/2017/12/05/1.9.0#markdown
- https://github.com/ente-io/ente/pull/6642#issuecomment-3118225419
=> Prettier: Make it work better with markdown

mobile/apps/photos/lib/utils/image_ml_util.dart
Revert error on rotated image decoding for indexing
=> [mob][photos] Revert error on rotated image decoding for indexing

mobile/apps/photos/lib/db/ml/db.dart, mobile/apps/photos/lib/ui/viewer/people/person_face_widget.dart
Fixes issue in face thumbnail generation when the file is not present.
=> [mob][photos] Missing cover fix

mobile/apps/photos/lib/ui/viewer/file/detail_page.dart
=> [mob][photos] Keep fullscreen between swipes

mobile/apps/auth/assets/custom-icons/icons/ubiquiti.svg
Updated Ubiquiti icon to new design, fix #6726
=> updated ubiquiti auth custom icon

mobile/apps/photos/lib/db/upload_locks_db.dart, mobile/apps/photos/lib/utils/file_uploader.dart
=> [mob][photos] Log info about lock

mobile/apps/photos/lib/main.dart
=> [mob][photos] Reduce logs on startup

mobile/apps/auth/assets/custom-icons/_data/custom-icons.json, mobile/apps/auth/assets/custom-icons/icons/capcom.svg
- added an icon for capcom
- added a json entry for capcom
=> [auth] add icon for capcom

server/cmd/museum/main.go, server/pkg/middleware/collection_link.go, server/pkg/middleware/file_link.go
=> [server] Fix typo in file link grouping

mobile/apps/auth/lib/utils/toast_util.dart
This fixes https://github.com/ente-io/ente/issues/324
=> [auth] Fix "Copied to Clipboard" text behind clipboard

.github/workflows/mobile-daily-internal.yml, mobile/apps/photos/scripts/changes.txt
=> [mob] Add daily release workflow for photos

.github/workflows/mobile-daily-internal.yml, .github/workflows/mobile-internal-release-rust.yml, mobile/apps/photos/pubspec.yaml
=> [mob] Use Github workflow's run_number for bumping up the versionCode

infra/services/caddy/Caddyfile, infra/services/caddy/README.md, infra/services/caddy/caddy.service
For custom domain TLS provisioning
=> [infra] Caddy

server/pkg/middleware/collection_link.go
=> [server] Fail request on customDomain mismatch

mobile/apps/photos/lib/db/files_db.dart, mobile/apps/photos/scripts/internal_changes.txt
=> [m][photos] Fix for duplicate entries for local file

docs/docs/self-hosting/installation/config.md
=> [docs] Lint

mobile/apps/auth/assets/custom-icons/_data/custom-icons.json, mobile/apps/auth/assets/custom-icons/icons/mobile01.svg
Custom icon for [Mobile01](https://www.mobile01.com/)
- Add optimised SVG file
- Add entry to custom-icons.json
=> Add custom icon for Mobile01

mobile/packages/configuration/lib/base_configuration.dart
When using Auth without backup, it was giving a error `Offline key is missing` 
**Reason**: During the `init` of `BaseConfiguration` if the `tokenKey` is not set, we clear all the keys in the secure storage, and in this process the `offlineAuthSecretKey` was also getting cleared 
**Fix** Fixed by skipping the deletion of `offlineAuthSecretKey`  
[Test Video](https://wormhole.app/qz3mol#Dlhr0NRpVQVQsrid2X-quA)
=> [auth] Fix missing token

mobile/apps/photos/lib/l10n/intl_en.arb, mobile/apps/photos/lib/ui/settings/streaming/video_streaming_settings_page.dart, mobile/apps/photos/lib/utils/bg_task_utils.dart
=> [mob][photos] fixes

mobile/apps/photos/lib/core/constants.dart
=> [mob][photos] Revert diskLoadDeferDuration to 500ms

.github/workflows/mobile-release.yml
- Disk space cleanup
- Generate rust bindings
=> [infra] Release action changes

mobile/packages/network/lib/network.dart
This should fix this error https://github.com/ente-io/ente/pull/6768#discussion_r2310164866
=> Fixing dev build on macos

web/packages/new/photos/services/search/worker.ts
=> [web] Fix European date format search support

mobile/apps/photos/CLAUDE.md
=> [mob][photos] Add claude.md

mobile/apps/photos/CLAUDE.md
=> [mob][photos] Update claude md documentation

server/cmd/museum/main.go, server/mail-templates/discount_coupon.html, server/mail-templates/discount_coupon_kagi.html, server/mail-templates/discount_coupon_test.html, server/migrations/105_add_discount_coupons.down.sql, server/migrations/105_add_discount_coupons.up.sql, server/pkg/api/discountcoupon.go, server/pkg/controller/discountcoupon/controller.go, server/pkg/middleware/rate_limit.go, server/pkg/repo/discountcoupon/repository.go
Tested locally for happy cases
=> [server] Support for coupons

docs/docs/photos/features/deduplicate.md
=> [Docs] Similar images help entry

mobile/apps/photos/lib/models/search/search_types.dart, mobile/apps/photos/lib/services/search_service.dart, mobile/apps/photos/lib/ui/viewer/search/search_widget.dart
Lower cluster size threshold on discover page
=> [mob][photos] Lower cluster size threshold on discover page

docs/docs/self-hosting/administration/reverse-proxy.md
```
$ sudo systemctl caddy reload
Unknown command verb 'caddy', did you mean 'cat'?
```
=> Fix command to reload Caddy

mobile/apps/photos/AGENTS.md, mobile/apps/photos/CLAUDE.md
symlink for [agents.md](https://agents.md)
=> [mob][photos] symlink for agents.md

server/ente/remotestore.go, server/ente/remotestore_test.go, server/pkg/middleware/collection_link.go
=> [server] Improve support for idn domains

server/cmd/museum/main.go, server/configurations/local.yaml
Ref: https://github.com/ente-io/ente/issues/7122
Tested locally
=> [server] Support for changing server port

mobile/apps/photos/lib/ui/viewer/gallery/gallery_app_bar_widget.dart, mobile/apps/photos/plugins/ente_feature_flag/lib/src/service.dart, mobile/apps/photos/scripts/internal_changes.txt
1. Enable debug mode or be an internal user
2. Open any album/collection
3. Tap overflow menu (3 dots)
4. Select "Guest View (i)"
5. Verify all album photos open in guest view
6. Verify authentication required to exit
=> [mobile/photos] Add collection-level guest view

mobile/apps/photos/lib/ui/viewer/gallery/gallery_app_bar_widget.dart
=> [mob] Change order for guest view

server/pkg/controller/replication3.go, server/pkg/utils/file/file.go
Currently, we only create tempFiles based on objectKeys and we control the values of same. This is just an additional check for future in case we decide to create more temporary files via same method. 
In future, ideally we should switch to os.CreateTemp method that would ensure these files are created under the temp directory.
=> [server] Add additional validation for tempFileName

mobile/apps/photos/lib/ui/viewer/gallery/large_files_page.dart, mobile/apps/photos/scripts/internal_changes.txt
=> [mob] Fix sorting for large files

mobile/apps/photos/analysis_options.yaml, mobile/apps/photos/lib/utils/file_uploader.dart
- Track bytes downloaded
- Fix formatter
=> [mob][photos] add upload progress tracking to file uploader

docs/docs/self-hosting/installation/upgrade.md
=> [docs] fix typo

mobile/apps/locker/ios/Podfile.lock, mobile/apps/locker/ios/Share Extension/Info.plist
Fix info.plist to accept the incoming files for iOS. And put the max count of incoming files to 100.
=> [locker] Update Podfile.lock and Info.plist f

.github/workflows/locker-internal-release.yml, mobile/apps/locker/android/app/build.gradle
Add GitHub Actions workflow for internal release of Locker mobile app
=> [locker] Setup for Internal release

mobile/apps/photos/lib/ui/tools/similar_images_page.dart, mobile/apps/photos/scripts/internal_changes.txt
From "Same - Close - Related" to "Close - Similar - Related"
=> [mob][photos] Change similar images copy

mobile/apps/photos/AGENTS.md
=> [mob][photos] Add repository guidelines

mobile/apps/photos/ios/Podfile.lock, mobile/apps/photos/lib/l10n/intl_en.arb, mobile/apps/photos/lib/services/collections_service.dart, mobile/apps/photos/lib/ui/sharing/manage_links_widget.dart, mobile/apps/photos/plugins/ente_feature_flag/lib/src/model.dart, mobile/apps/photos/plugins/ente_feature_flag/lib/src/service.dart, mobile/apps/photos/scripts/internal_changes.txt
=> [mob][photos] Add Copy embed HTML feature for internal users

docs/docs/photos/features/sharing-and-collaboration/custom-domains/index.md, web/CLAUDE.md, web/apps/photos/src/components/Sidebar.tsx, web/apps/photos/src/pages/shared-albums.tsx
- Fix Trip albums not redirecting to albums.ente.io on fresh load
=> [web] Fix Trip album redirects from custom domains

docs/docs/self-hosting/installation/config.md, server/cmd/museum/main.go, server/config/example.yaml, server/configurations/local.yaml, server/ente/remotestore.go, server/pkg/controller/remotestore/controller.go, web/packages/new/photos/services/settings.ts
=> [server] Config for embed albums

.github/workflows/mobile-daily-internal.yml
=> [meta] Update mobile workflow

.github/workflows/claude.yml
=> [workflow] remove depth from claude.yml

.github/workflows/claude-code-review.yml, .github/workflows/claude.yml
We have to explicitly mention depth 0 for actions checkout.
=> [workflow] set fetch-depth to 0 in claude workflows

mobile/apps/photos/lib/utils/lock_screen_settings.dart
=> [mob][photos] Avoid redundant call to disable privacyScreen

.github/workflows/claude.yml
Addresses https://github.com/ente-io/ente/pull/7385#discussion_r2413482965
=> [meta] Fix Claude workflow to properly checkout PR branches from forks - Take 2

.github/workflows/claude.yml
Take 3! https://github.com/ente-io/ente/pull/7386
=> [meta] Use gh pr checkout to properly fetch PR branches for Claude action
